### ISSUE TITLE
Удобный интерфейс выбора загружаемых файлов.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#10]
Понятно из названия для опц. модов и тому подобного. С точки зрения api.

**Comment by Zaxar163** [comment]
Раз взялся.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/4ef4df0911c0b60e3be1e9f8da2372831be639fa
https://github.com/GravitLauncher/Launcher/commit/b32a613fd521476ab718c1c6793057d9b92d5a63
https://github.com/GravitLauncher/Launcher/commit/77978b0f742c8650ee5722e413c752ac7f9353ec
