### ISSUE TITLE
Опциональные моды для определенных ников или hwid

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#120]
Добавление через конфиг определенных опциональных модов (xray для админов)

**Comment by gravit0** [comment]
Небезопасно при текущей системе скачки обновлений

**Comment by Zaxar163** [comment]
WebSockets требуется - станет более менее возможно.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/104ece2be411eed289b8f21f7486da0642c972ef

**Comment by TheXaver** [comment]
Также добавить для определенных ников

**Comment by TheXaver** [comment]
чтобы в конфиге самому можно было для ников настраивать опциональные моды

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/f76146012284e8c50b04241488444965a5fe874a
