### ISSUE TITLE
Другая логика hwid.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#124]
Предположим есть человек серьёзно нарушивший правила. У него было 5 мультиаккаунтов. Забанили по hwid все 5. Потом один из них зашёл с другого hwid - тот hwid тоже забанили. Старый hwid для этого аккаунта тоже в бане причём для всех 5...

**Comment by gravit0** [comment]
Банить на сайте, и до проверки HWID дело не дойдет
HWIDHandler работает только с HWID. Нельзя узнать был ли пользователь забанен по HWID если его HWID сменился
Какие либо специфические фитчи - модулем
