### ISSUE TITLE
Не собирает indexAsset 

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#133]
При выполнении команд
1. unindexAsset asset1.7.10 1.7.10 unindexed 
2. удаляете asset1.7.10 
3. в unindexed/icons и unindexed/minecraft/icons меняете иконки 
4. и потом indexAsset unindexed 1.7.10 asset1.7.10 
5. удаляете unindexed
Не собирает и выдает ошибку
В старом Сашке все ок.
https://hastebin.com/socipareke.rb

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/2a957a630354f56f46f2659af93c6435b037e186
