### ISSUE TITLE
Запуск jar в serverwrapper

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#134]
Добавить строчку конфига для запуска jar с ключом и классами
(полезно для rtoolkit и всяких хостингов)

**Comment by gravit0** [comment]
Используйте classpath + autoloadLibraries + mainclass

**Comment by TheXaver** [comment]
autoloadLibraries берет все jar из папки?

**Comment by gravit0** [comment]
Для этого он и создан
