### ISSUE TITLE
Невалидный username

### ISSUE THREAD

**Issue by X0XCodeZero** [GravitLauncher/Launcher#135]
При запуске клиента или сервера выдаётся Invalid username
UUID этих невалидных никнеймов всегда разные.
пробовал dumpEntryCache, но этих uuid там вообще нету, пробовал загружать дамп с пустыми значениями

{
  "entryCache": {},
  "usernameCache": {}
}

Ситуация аналогичная.
Ников русских нет, лаунчера ни у кого нет. Пробелов тоже нет.

P.S 144.76.155.235 - IP хоста
80.252.131.174 - мой IP

https://hastebin.com/yevokowipi.coffeescript

**Comment by X0XCodeZero** [comment]
P.S.S В логах сначало я запустил сервер, потом через секунд 30 стартанул клиент. Это всё было сделано для наглядного примера.

**Comment by Zaxar163** [comment]
В поддержку в нашей конфе напишите. Информации маловато.
