### ISSUE TITLE
Реализовать runtime вне jar

### ISSUE THREAD

**Issue by sanik** [GravitLauncher/Launcher#138]
Идея реализовать runtime вне jar самого лаунчера что даст возможность обновлаять дизайн при запуске
Тоесть запуск с примитивным окном загрузки и апдейт нормального дизайна
Очень нужная вещь если подумать
Так как большинство ребилда лаунчера делается для того чтобы подправить дизайн
можно оправдать использование js место нормальной java
Да и реализуется легче чем многое что вы реализовали уже

**Comment by gravit0** [comment]
Сильно снижает защиту лаунчера

**Comment by Mr-Krab** [comment]
Что мешает изменять оформление и пересобирать лаунчер? Для этого не нужно перезапускать лаунч-сервер, если конечно изменения не вносятся в js(тут я не проверял, но думаю тоже перезапуск не нужен).

**Comment by TheXaver** [comment]
Как минимум из-за подписи, то есть ты билдешь. скачиваешь exe, подписываешь, обратно на сервер и rebind. Ой как классно

**Comment by gravit0** [comment]
Только эта "классность" - рай для читеров

**Comment by sanik** [comment]
Как именно это снижает защиту?

**Comment by gravit0** [comment]
Позволяет читерам выполнять любой js код в лаунчере
