### ISSUE TITLE
Отправка логов на сервер

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#143]
Предлагаю в режиме дебага сделать кнопку для отправки логов на сервер. Можно также прикрутить поле для заметок, и  отправлять уже лог с комментарием от пользователя.

**Comment by gravit0** [comment]
Эта фитча касается интеграции лаунчера с вашими сервисами
Используйте правки runtime и при необходимости модули, что бы реализовать этот функционал конкретно для вашего проекта
В общем случае эта фитча открывает дыру для DDoS и проведения атаки с заливом php шелла при крайне неправильной настройке веб сервера и PHP

**Comment by TheXaver** [comment]
Можно отправлять и на s3 хранилище или на ftp, и отправлять http запрос, что произошел краш
