### ISSUE TITLE
Продвинутая система модулей

### ISSUE THREAD

**Issue by MicroNovaX** [GravitLauncher/Launcher#146]
В связи с криворукостью пользователей лаунчера, считаю, что необходимо добавить скачку, сборку и установку последних версий модулей прямиком из командной строки лаунчера посредством набора простых команд.

**Comment by daniorio** [comment]
Криворукость пользователя-полностью его вина. Проще добавить страницу на википедии с полным гайдом по сборке лаунчера, включаю модули.

**Comment by MicroNovaX** [comment]
@daniorio с wiki беда, из-за бездарей, которые ей занимаются, улучшений не предвидится.

**Comment by gravit0** [comment]
Не имеет смысла
Если и делать скачку модулей, то только через браузер с системой аля bukkit dev
