### ISSUE TITLE
Проверка актуальной версии

### ISSUE THREAD

**Issue by MicroNovaX** [GravitLauncher/Launcher#147]
Для облегчения контроля актуальности версии лаунчера и для обеспечения уверенности в том, что в установленной на данной момент версии нет известных критических багов, считаю, что необходимо ввести регулярную проверку на актуальность текущей версии, с дальнейшим уведомлением владельца в консоли, и в случае критичности - прямо в лаунчере. 
В случае технической возможности, то и автообновление можно допилить x0

**Comment by gravit0** [comment]
Уже есть в планах

**Comment by Zaxar163** [comment]
Можно реализовать через скачку json о версиях с github.

**Comment by Zaxar163** [comment]
API github такое разрешает.

**Comment by Zaxar163** [comment]
#158
