### ISSUE TITLE
Защита от кражи runtime

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#157]
Предлагаю каким-либо образом защищать рантайм лаунчера от кражи.

**Comment by TheQukallon** [comment]
Поддерживаю.

**Comment by TheQukallon** [comment]
@MicroNovaX Почему же

**Comment by TheXaver** [comment]
Весь дизайн нужно на Java делать,  тогда не украдут,  еще сашок об этом говорил.

**Comment by TheQukallon** [comment]
@TheXaver Ты что, это сложно пиз..... будет.

**Comment by TheXaver** [comment]
А сашок специально сделал runtime с java fx, ведь он провал лаунчер.

**Comment by gravit0** [comment]
Используйте модули для написания дизайна на Java
