### ISSUE TITLE
ip v6

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#160]
Поддержка ip v6

**Comment by cyb3rm4n** [comment]
Стоит обсудить. С одной стороны, в странах СНГ IPv6 даёт малое количество провайдеров, и я сомневаюсь. что игроки из США будут играть на пиратской сборке майнкрафта.

**Comment by gravit0** [comment]
Я поддерживаю переход на IPv6
Ждите обновления, в котором будет возможно ставить несколько адресов для прослушки

**Comment by Zaxar163** [comment]
Вебсокеты реализованы - теперь эта issue на очереди.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/bb611d202200befe68cc4ba155c9b96d1099cef3
