### ISSUE TITLE
Организация скачивания клиента через cdn.

### ISSUE THREAD

**Issue by MrLimb** [GravitLauncher/Launcher#163]
Возможно ли скачивание файлов клиента и прослушка лаунчером CDN, к примеру, Cloudflare? 
// Принимаю критику, если что-либо неверно, укажите.

**Comment by gravit0** [comment]
Возможно только с #18

**Comment by MrLimb** [comment]
На данный момент, это реализовать невозможно?

**Comment by gravit0** [comment]
На текущий момент не реализуемо

**Comment by MrLimb** [comment]
Спасибо. Будем ждать.

**Comment by MrLimb** [comment]
> Я уже открывал isuues по этой теме. Нужно просто скачивание модов по ссылке.

Возможно ли автоматизировать это в данный момент?

**Comment by TheXaver** [comment]
Я ему скинул старый код Сашка для скачивания файлов, посмотрим что будет

**Comment by gravit0** [comment]
HTTP медленное? Вы явно чтото не понимаете в http

**Comment by radioegor146** [comment]
> HTTP медленное? Вы явно чтото не понимаете в http

Ну так как все нормальные люди юзают HTTPS - время хендшейка в нём может занимать больше чем в реализации на сокетах. Но я всё же за HTTPS + уменьшение кол-ва маленьких файлов (например assets пихать в .zip).

**Comment by gravit0** [comment]
Я просто оставлю это здесь: https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%BD%D0%BE%D0%B5_HTTP-%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5
Большинство дистрибутивов Linux скачивают пакеты с зеркалов по HTTP/HTTPS, при этом просадок скорости нет
При прерывании загрузки можно всегда её возобновить

**Comment by Beshelmek** [comment]
Тоже очень жду

**Comment by gravit0** [comment]
Реализовано при использовании вебсокетов
