### ISSUE TITLE
Опциональные моды

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#165]
Не сохраняются опциональные моды.

**Comment by gravit0** [comment]
Можно подробности?

**Comment by daniorio** [comment]
Убираю лишние галки в опц модах, жму "пременить", вхожу на сервер, все работает как надо. 
![default](https://user-images.githubusercontent.com/42574494/52164635-27556500-26fd-11e9-8f76-26bed31adc0a.png)
Выхожу, открываю лаунчер заного. Все галки на первоначальных местах.
![default](https://user-images.githubusercontent.com/42574494/52164658-61266b80-26fd-11e9-8b85-c64e87174261.png)
![default](https://user-images.githubusercontent.com/42574494/52164660-671c4c80-26fd-11e9-80d5-c15b33107e57.png)

**Comment by gravit0** [comment]
У вас кастомный дизайн. Убедитесь что вы правильно перенесли логику с стандартного дизайна

**Comment by daniorio** [comment]
Проверил, со стандартным дизайном не работает

**Comment by Noire86** [comment]
Проверь очередность индексов в профилях. У тебя одинаковые индексы стоят в них.

**Comment by daniorio** [comment]
Да, про индексы не знал. Поставил разные - все заработало великолепно. Думаю, можно закрывать.
