### ISSUE TITLE
Перенос файлов

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#166]
При смене директории лаунчер открывает окно с возможностью перенести файлы в новую директорию. При нажатии на кнопку "перенести" файлы не переносятся, вот такую ошибку кидает с дебагом:
![default](https://user-images.githubusercontent.com/42574494/52165019-bfeee380-2703-11e9-813d-3d82396c28c2.png)
![default](https://user-images.githubusercontent.com/42574494/52165024-c54c2e00-2703-11e9-90c6-8111c61d3e5a.png)

**Comment by gravit0** [comment]
Папка должна быть пуста

**Comment by daniorio** [comment]
Раз так, предлагаю улучшить это дело, и переносить файлы не только в пустые папки. Хотите делайте, хотите не делайте. Более вопросов нет, закрывайте.

**Comment by yaroslav4167** [comment]
Что если создавать в указанном каталоге папку лаунчера, и уже в неё класть файлы. 
Вероятность того, что в выбранном каталоге будет папка с таким же именем - достаточно мала.
