### ISSUE TITLE
Двухфакторная аутентификация

### ISSUE THREAD

**Issue by BlayzerQ** [GravitLauncher/Launcher#167]
Считаю нужным добавление системы двухфакторной авторизации, что позволит лучше защитить аккаунты игроков от несанкционированного входа (Особенно актуально в свете того что большинство пользователей указывает одинаковые пароли как минимум на нескольких проектах, а у этих проектов сливают базы данных, причем в некоторых случаях пароли даже не зашифрованы в БД), этот функционал был бы очень полезен. Я уже когда-то писал в дискорде об этом.

Для начала нужно узнать, включена ли 2FA у пользователя, это можно описать в БД. В DLE например есть готовый функционал для этого, но там отдельная база где хранятся user_id и его пин, ну и другие данные http://joxi.ru/xAeKyLeTpnRXPm.png 
Ну или даже просто сделать отдельным полем в базе с пользователями - это уже можно оставить за настройкой тех кто использует лаунчер. Далее, при авторизации с верным паролем и логином выбивать окно с сообщением о том что включена 2FA (Если она отключена, то этап пропускаем и сразу производим запуск игры) и требуется подтвердить вход пинкодом. После успешного ввода пина двухфакторки так же запускаем игру, в противном случае отменяем процесс авторизации. 
В плане самой реализации примерно так, уже за тех стороной не очень важно как все будет работать, главное сама возможность настроить это, при хорошем раскладе можно все это интегрировать прямо в сервер лаунчера, но это если у гугла все это можно настроить легко, самый нейтральный способ - использование php скрипта или алгоритма на стороне сервера лаунчера, который будет работать с базой.
Есть библиотека для работы с гугл 2fa auth https://github.com/wstrange/GoogleAuth
Вот еще одна библиотека, с примером использования в отдельном приложении 
https://github.com/j256/two-factor-auth
И гайд 
https://www.javacodegeeks.com/2011/12/google-authenticator-using-it-with-your.html

https://www.asaph.org/2016/04/google-authenticator-2fa-java.html

https://www.twilio.com/docs/sms/tutorials/two-factor-authentication-java-servlets

В принципе, думаю этого хватит, там уже повторения по тому что я в гугле находил 
Но думаю что самое оптимальное, как раз использование гугл двухфакторки, ее можно интегрировать прямо в сервер лаунчера, но придется изменить алгоритмы авторизации для поддержки этого, ну и еще проверять в базе включена ли у пользователя эта функция.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/f9129c28d231d6dacbfbd4c3333119b1e5ba9f98
Техническое дополнение, позволяющее это реализовать
Если этого достаточно - можно закрывать. Если нет - допиливайте рантайм сами и выложите в opensource, вместе с AuthProvider

**Comment by LoomeL** [comment]
OK:(?<username>.+):(?<permissions>.+):(?<2fatoken>.+)

**Comment by LoomeL** [comment]
Если ответ 0 то 2fa не настроен для пользователя, если в ответ получаем 2fa ключ, то выводим панель в лаунчере с вводом кода. Проверку можно делать на уровне клиента

**Comment by LoomeL** [comment]
Задача явно не первой важности, если у разработчиков появится желание то реализовать можно.
Не думаю что это сложно сделать.

**Comment by Zaxar163** [comment]
Думаю достаточно - остальное можно доделать модулем.

**Comment by BlayzerQ** [comment]
> Думаю достаточно - остальное можно доделать модулем.

А тебя не смущает return; в preAuth()?

**Comment by Zaxar163** [comment]
@BlayzerQ return убирается наследованием класса и Override.

**Comment by Zaxar163** [comment]
Cледовательно написанием модуля.

**Comment by xxDark** [comment]
> 
> 
> @BlayzerQ return убирается наследованием класса и Override.

Зачем там вообще return, если это пустой метод? И @Override это не аннотация в рантайме, она нужна только для удобства для разработчиков.
