### ISSUE TITLE
Запаковка конфигов

### ISSUE THREAD

**Issue by CakeProgress** [GravitLauncher/Launcher#169]
К примеру, у нас есть папка config, в которой есть огромное количество конфигов, которые скачиваются лаунчером с сервера. Можно сделать эту процедуру более легкой - объеденить все конфиги в один архив и скачивать его, а после - распаковывать лаунчером. (Например config.pkg) Если данного файла нет, а есть просто папка config, то он скачивает ее если он, есть то он скачивает его и распаковывает. Такая функция уже реализована в лаунчере K773, очень удобно и практично. Если будет возможность реализовать за дополнительную плату просьба взяться.

**Comment by Zaxar163** [comment]
А зачем? И так Deflate используется.

**Comment by CakeProgress** [comment]
Ибо, лаунчеры от "sashok" качают по 1 это крайне не удобно если мод в основном построен на конфигах . (Их около 5000) и он качает эти 5000 по 1 файлу, было бы удобнее качать всё 1 файлом проверяя его вес если он изменился, то будет перекачивать.

**Comment by TheXaver** [comment]
Так сделай нормальный мод. а не 5 тыс конфигов. на компе игрока это просто сильно диск грузит

**Comment by gravit0** [comment]
Нет необходимости.
Можете включить compress true в конфиге лаунчсервера
