### ISSUE TITLE
Докачивание java при необходимости

### ISSUE THREAD

**Issue by maximcs1** [GravitLauncher/Launcher#175]
В общем основная проблема которая возникает с лаунчером, это наличие пользователей с 64 bit системой и 32 bit java. Попросту не могут запустить клиент.
Было бы не плохо, еслиб в таком случае лаунчер докачивал java.
Пользователей таких достаточно, спамят ежедневно с такой проблемой.

**Comment by gravit0** [comment]
Реализовывайте, что вам мешает? Необходимое API для этого есть

**Comment by Zaxar163** [comment]
@maximcs1 лучше напиши нормальный пост про настройку Java и через javaMissOSArch предупреждение ссылку на него.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/517ffbd371d6bd0d12055f53eb4611fa7bbabe83
https://github.com/GravitLauncher/Launcher/commit/44a4feacde579859bfb4f48c8144b4b826375a0e
