### ISSUE TITLE
Сохранение нескольких hwid на одного пользователя (feature)

### ISSUE THREAD

**Issue by sasha0552** [GravitLauncher/Launcher#178]
Предлагаю сохранять несколько hwid для одного пользователя, допустим хранить в таблице hwid значения через запятую (например 1,3 значит то что этому пользователю принадлежит hwid в таблице users_hwids 1 и 3). Упростит бан тех кто будет менять именно компы.

**Comment by gravit0** [comment]
Для кастомой логики используйте JsonHWIDProvider.
При смене hwid данные НЕ удаляются, просто перезаписывается значение hwid. Используйте триггеры для отлавливания этого и добавление своей логики в это место
