### ISSUE TITLE
4.3.1.1 Update не выполняет своей функции.

### ISSUE THREAD

**Issue by NITDroid1995** [GravitLauncher/Launcher#179]
Есть настройка в профайле с таким содержимым
`"update": [
    "config/ImmersiveEngineering.cfg",
    "config/GalacticraftAmunRa.cfg",
    "config/ExtraPlanets.cfg",
    "config/MorePlanets.cfg",
    "config/GalaxySpace/core.conf",
    "config/ic2/blast_furnace.ini",
    "config/ic2/block_cutter.ini",
    "config/ic2/compressor.ini",
    "config/ic2/extractor.ini",
    "config/ic2/macerator.ini",
    "config/ic2/metal_former_cutting.ini",
    "config/ic2/metal_former_extruding.ini",
    "config/ic2/metal_former_rolling.ini",
    "config/ic2/ore_washer.ini",
    "config/ic2/thermal_centrifuge.ini",
    "config/ic2/uu_scan_values.ini",
    "servers.dat"
  ],
  "updateExclusions": [
    "mods/VoxelMods",
    "mods/railcraft",
    "mods/ic2"

    
  ],
  "updateShared": [],
  "updateVerify": [
    "libraries",
    "natives",
    "mods",
    "minecraft.jar",
    "forge.jar",
    "liteloader.jar"
  ],
`
Из этой настройки следует, что лаунчер при запуске клиента должен перекачать файлы, которые указаны в update[];
На деле же происходит следующие.
При первом (холодном) запуске лаунчера, он докачивает эти файлы.
Но этот файл может мной изменяться и после изменения происходит syncUpdates.
На втором запуске, лаунчер проверяет НАЛИЧИЕ этого файла в той директории которую я указал. Но вот Он не перекачивает его. Хотя функция Update как раз должна перекачивать файл каждый раз при старте клиента.

**Comment by NITDroid1995** [comment]
Указание этих файлов в updateVerify приводит к этому же результату. Лаунчер проверяет наличие файла в папке, но не проверяет изменения, хотя они были произведены и была прописана команда syncUpdates

**Comment by NITDroid1995** [comment]
При добавлении таким способом происходит тоже самое. Проерка на наличие. Проверка на хэш не происходит.
`  "updateVerify": [
    "libraries",
    "natives",
    "mods",
    "minecraft.jar",
    "forge.jar",
    "liteloader.jar",
    "config/ic2/blast_furnace.ini",
    "config/ic2/block_cutter.ini",
    "config/ic2/compressor.ini",
    "config/ic2/extractor.ini",
    "config/ic2/macerator.ini",
    "config/ic2/metal_former_cutting.ini",
    "config/ic2/metal_former_extruding.ini",
    "config/ic2/metal_former_rolling.ini",
    "config/ic2/ore_washer.ini",
    "config/ic2/thermal_centrifuge.ini",
    "config/ic2/uu_scan_values.ini"
  ],
`

**Comment by gravit0** [comment]
Здесь нет никакой ошибки. Вы не понимаете работу update/updateVerify.
Для проверки на хеш нужно использовать updateVerify.
Скорее всего вы забыли syncProfile сделать

**Comment by NITDroid1995** [comment]
Все-таки зря закрыл)))
`  "updateExclusions": [
    "mods/VoxelMods",
    "mods/railcraft",
    "mods/ic2",
    "config/NEI",
    "config/ClientFixer.cfg"
   ],`
Исключение   "mods/ic2", распростроняется на все папки, у которых название ic2 даже не в папке mods. в моем случае config
Стоило убрать эту строку из исключения и докачка сработала...

**Comment by NITDroid1995** [comment]
FIX dont work)

**Comment by NITDroid1995** [comment]
FIX dont work) again

**Comment by NITDroid1995** [comment]
`Contains RandomThings-2.2.4.jar
Exception in thread "main" java.lang.SecurityException: Forbidden modification: 'test'
    at ru.gravit.launcher.client.ClientLauncher.verifyHDir(Unknown Source)
    at ru.gravit.launcher.client.ClientLauncher.main(Unknown Source)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release`

**Comment by Warnay** [comment]
так как это исправить?
