### ISSUE TITLE
Переход на вебсокеты + channels с netty.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#18]
Обязателен для больших проектов

**Comment by gravit0** [comment]
Подзадача: написать клиент на javax.websockets

**Comment by Zaxar163** [comment]
Ещё задача: разобраться с их форматом.

**Comment by Zaxar163** [comment]
Клиент в 1 приближении: #27

**Comment by Zaxar163** [comment]
Требуется полный переход, удаление протокола сашка.

**Comment by Zaxar163** [comment]
Выполнение вместе с #45.

**Comment by Zaxar163** [comment]
85%

**Comment by gravit0** [comment]
Основная база реализована. Уже можно пользоваться
Конечно предстоит еще много работы, но можно сказать - WebSockets уже с нами
