### ISSUE TITLE
Предложение по улучшению системы бана по железу

### ISSUE THREAD

**Issue by UralMas** [GravitLauncher/Launcher#180]
Ковыряясь в таблице данных железа пользователей (20 000 записей), обнаружил:
1. В строках серийных номеров может большое количество пробелов, как слева от данных, так и справа. Это очень ухудшает производительность поиска по БД, т.к. приходится делать более длинные индексы, чем необходимо.
2. В столбцах серийных номеров может присутствовать всякий мусор, например (это реальные данные):
- unknown
- To be filled by O.E.M.
- To Be Filled By O.E.M.
- Default string
- None
- empty
- INVALID
- N/A
- Not Applicable
- Not Available
- OEM
- System
- System Serial Number
- System Serial Number Unknown
- Unknow
- ÿÿÿÿÿÿÿ
- яяяяяяяяяяяяяяяяяяяя

Наверное, есть ещё такие, не несущие данных, значения.
Данных это не несёт нисколько. Может, вычленять такие значения и заменять на пустые строки?

3. В некоторых строках вместо данных стоит символ, не входящий в диапазон UTF-8 (отображается как квадрат). Данных это тоже не несёт. Может, такие строки заменять на пустые?

Суммируя всё это и сделав эти преобразования в тестовой базе, получилось, что некоторые идентификаторы (строки) имеют следующие значения по железу: totalMemory - 0; serialNumber, HWDiskSerial и processorID - пустые значения. Т.е. банить такие идентификаторы нельзя - забанятся сразу несколько разных пользователей.
Поэтому есть 4-е предложение - не выдавать пользователям, у которых все 4 параметра имеют пустое значение, hwid ID.

**Comment by TheXaver** [comment]
Мусор выдает oshi и с ним ничего нельзя поделать.

**Comment by UralMas** [comment]
А очистить результат oshi перед записью в таблицу нельзя? oshi сразу пишет в БД?

**Comment by gravit0** [comment]
В windows полный бардак с серийными номерами и всем остальным. Все эти значения, не несущие смысла - реальные значения, записанные производителем или сборщиком. Фильтровать такие изменения можно. Используйте модуль для своей, кастомной логики

**Comment by TheXaver** [comment]
Для логики можно использовать jsonhwid, но конфигов нет, и нужно смотреть в исходниках. А так jsonhwid работает

**Comment by gravit0** [comment]
Раз у вас 20к записей вы можете справится с JsonHWIDHandler

**Comment by TheXaver** [comment]
Как вариант с враппером встраивать hwid.
