### ISSUE TITLE
Найден чит-инжект.

### ISSUE THREAD

**Issue by DontFollow** [GravitLauncher/Launcher#181]
Недавно знакомый скинул чит, я опробовал его у себя в лаунчере с Avanguard'ом.
Скидывать его сюда не буду. Разработчики, напишите мне в [ВК](https://vk.com/user.dontfollow).

**Comment by TheXaver** [comment]
новая защита тестится, про авангард нет смысла писать

**Comment by TheXaver** [comment]
Советую закрыть issues

**Comment by DontFollow** [comment]
> новая защита тестится, про авангард нет смысла писать

Скажите, пожалуйста, какие примерные сроки бета-версии новой защиты?

**Comment by TheXaver** [comment]
Давайте перейдем в общение в сервер дискорда
