### ISSUE TITLE
Вызов несуществующего (удалённого) метода в JAConfigurator

### ISSUE THREAD

**Issue by Sirse** [GravitLauncher/Launcher#189]
https://github.com/GravitLauncher/Launcher/blob/7050e0e9ac8b65f09147b1f38a24b08539a9309c/libLauncher/src/main/java/ru/gravit/launcher/modules/ModulesManager.java#L24

https://github.com/GravitLauncher/Launcher/blob/7050e0e9ac8b65f09147b1f38a24b08539a9309c/LaunchServer/src/main/java/ru/gravit/launchserver/binary/JAConfigurator.java#L37-L39

Сломано в #153

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/94d677fe1e2ded7198377105d656fd21ce849c4e
Починил
