### ISSUE TITLE
Radon - дополнительная обфускация.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#190]
Ожидается добавление Radon, ставьте +1 или -1 в зависимости добавлять или нет. Так же пишите своё мнение сюда. Скоро добавлю данный функционал. Но желаю знать ваше мнение.

**Comment by yaroslav4167** [comment]
Если это не добавит дополнительных проблем на подобии жалоб антивирусов и каких-то конфликтов - я за =D

**Comment by Zaxar163** [comment]
До суммарно 10 голосов дожидаюсь и начинаю делать.

**Comment by Will0376** [comment]
за.

**Comment by Zaxar163** [comment]
#191

**Comment by Mr-Krab** [comment]
+1
