### ISSUE TITLE
Хук setProfile.

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#192]
хранение whitelist в mysql

**Comment by gravit0** [comment]
Не вижу смысла и хорошего способа это реализовать.
Делать отдельный handler на этот случай - бессмысленно
А чего то еще динамического и связанного с профилями я не знаю
Не могу представить так же сценарии использования этой фитчи.

Единственное что могу повесить хук на setProfile, тогда сможете обрабатывать сами модулем
