### ISSUE TITLE
Чувствительность команд к регистру

### ISSUE THREAD

**Issue by Sirse** [GravitLauncher/Launcher#196]
Команды чувствительны к регистру, в том числе модули, имплементирующие Reconfigurable.
В какой-то момент получим кучу команд, выглядящих как **config myAweSomeModule eXecUteMuAweSomEActIon**.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/fee94ff368f9fa4928feeeafd93b89526cc88c11
