### ISSUE TITLE
Gitmodules

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#200]
Смена с ssh на https
Не у всех на машинах сделаны ssh ключи и подключены к github. Github без ssh ключа блокирует соединение

**Comment by gravit0** [comment]
SSH ключи в submodules нужны для удобных коммитов в репозиторий.
Для https соеденения требуется каждый раз вводить пароль для пуша
Что не очень удобно для разработчиков, меня и Захара.
Пока закрою, ибо не знаю как сделать это удобным для всех
