### ISSUE TITLE
Некоторые введения.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#206]
1. Сделать автосимлинк/автокопирование (зависит от ОС) Launcher.exe/Launcher.jar при включённом Netty.
2. Сделать поддержку кастомного EXELauncherBinary (для модулей заменяющих Launch4j, в планах сделать 1 такой).
4. Добавить API для хука получения ClientProfile.

**Comment by Zaxar163** [comment]
3. Done.

**Comment by Zaxar163** [comment]
2. Done

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/pull/213
