### ISSUE TITLE
request/json AuthHandler

### ISSUE THREAD

**Issue by sasha0552** [GravitLauncher/Launcher#209]
Так как я в данный момент перехожу на локал (т.е. база не будет доступна из вне) необходимо как либо осуществить связь базы с лаунчсервером. Могу писать любые php скрипты, поэтому прошу сделать request или json AuthHandler.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/pull/218
https://github.com/GravitLauncher/Launcher/commit/ab57e7d2d7f3ebedb9f3b3e0fdc3e200cbcf75cf
