### ISSUE TITLE
Выбор дизайна на js или на java

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#21]
Со всеми вытекающими.

**Comment by gravit0** [comment]
Не критично, приоритет низкий

**Comment by Zaxar163** [comment]
@gravit0 да низкий, но нужно.

**Comment by Zaxar163** [comment]
При попытке это сделать выяснил - требуются большие изменения...

**Comment by Zaxar163** [comment]
Требует #18.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/b49d17a018f71609e0a482574ac6f04b3b4b282e
