### ISSUE TITLE
Добавление отсылки логов о краше лаунчера на удаленный сервер

### ISSUE THREAD

**Issue by AttempGame** [GravitLauncher/Launcher#210]
Добавление отсылки логов о краше лаунчера на удаленный сервер, фтп сервер или какой-то с онлайн дисков по типу (Dropbox, Google Drive, Yandex Drive)

**Comment by radioegor146** [comment]
Не будет ли это уязвимостью? Ведь с учётом того что лаунчер open-source логи то можно и позасирать зная API.

**Comment by Zaxar163** [comment]
Ага

**Comment by radioegor146** [comment]
Сделать генератор фейковых краш-логов :sunglasses:

**Comment by AttempGame** [comment]
Кому это нужно будет, отправление фейковых краш-логов, это маленькая фишка для администраторов.

**Comment by Zaxar163** [comment]
@radioegor146

**Comment by radioegor146** [comment]
Ну смотри. Я такой - *ууу этот админ меня задолбал*, и погнал ему спамить краш-логами.

**Comment by gravit0** [comment]
Я против этого нововведения.
Предположим вы отпраивили логи на сервер. И что? Посмотреть какие ошибки наиболее часто встречающиеся? Как отправить решение проблемы? Может проблема уже решена?
Т.к. никакие разгадывания картинки, выбор светофоров/гидрантов/витрин подключить невозможно нельзя решить проблему с ботами, которые будут отправлять краш логи.
Краш логи при большом их количестве ощутимо весят, что открывает возможность DDoS атаки нацеленной на забивание места на диске.
Если решите все указанные выше проблемы не поднимая сложность разработки до небес - открою issue снова

**Comment by Zaxar163** [comment]
Есть решение с авторизацией - краш лог идёт только от клиента, а => от авторизованного пользователя. А то, что можно сделать на авторизацию и регистрацию...

**Comment by Zaxar163** [comment]
Но беда с дискспейсом - 1к онлайна, и уже диск стало жалко.

**Comment by daniorio** [comment]
Будто сервера с онлайном 1к сами о себе не позаботятся. Если им надо будет, они перепишут эти крашрепорты, у них бюджет огромный. А вот на средние и маленькие проекты живут великолепно. С их онлайном менее сотни никак не засорить диск.

**Comment by radioegor146** [comment]
> Будто сервера с онлайном 1к сами о себе не позаботятся. Если им надо будет, они перепишут эти крашрепорты, у них бюджет огромный. А вот средние и маленькие проекты живут великолепно. С их онлайном менее сотни никак не засорить диск.

Так как раз таки на маленькие сервера и спамят :D

**Comment by Will0376** [comment]
И как они спамят? дебаг-крашем? так его вырезать можно, ну или отсеивать файлы на уровне сервера по содержимому(черный список так сказать.)

**Comment by radioegor146** [comment]
> И как они спамят? дебаг-крашем? так его вырезать можно, ну или отсеивать файлы на уровне сервера по содержимому(черный список так сказать.)



> Сделать генератор фейковых краш-логов



> Ну смотри. Я такой - _ууу этот админ меня задолбал_, и погнал ему спамить краш-логами.

Воть

**Comment by Will0376** [comment]
эм. а ничего, что крашлоги можно сделать по авторизации? как предлагал @Zaxar163

**Comment by radioegor146** [comment]
> эм. а ничего, что крашлоги можно сделать по авторизации? как предлагал @Zaxar163

авторег + удобный api лаунчера (websocket)

**Comment by MrYarik666** [comment]
Можно сделать возможность загрузки только 1 краш-репорта в день с 1 IP адресом и не более 5 крашей на 1 аккаунт в день
Также ограничивать их по размерам, т.к некоторые есть действительно большие, но многие могут этим пользоваться просто ради забивание жесткого диска
Также фильтровать ошибки. Если в краше OutOfMemory - пропускать его(дабы реальными крашами от реальных игроков не забивать место). 
Проверять ли данная ошибка повторялась, думаю можно написать какой-то не супер сложный и не супер ресурсоемкий алгоритм. 
Старые краши, которым больше 1 недели - удалять.  
В целом все проблемы решены. 
p.s Я делал такой краш-репортер модом, и загружал их на pastebin, все отлично срабатывало и хранил только URL'ки :)

**Comment by AttempGame** [comment]
> Можно сделать возможность загрузки только 1 краш-репорта в день с 1 IP адресом и не более 5 крашей на 1 аккаунт в день
> Также ограничивать их по размерам, т.к некоторые есть действительно большие, но многие могут этим пользоваться просто ради забивание жесткого диска
> Также фильтровать ошибки. Если в краше OutOfMemory - пропускать его(дабы реальными крашами от реальных игроков не забивать место).
> Проверять ли данная ошибка повторялась, думаю можно написать какой-то не супер сложный и не супер ресурсоемкий алгоритм.
> Старые краши, которым больше 1 недели - удалять.
> В целом все проблемы решены.
> p.s Я делал такой краш-репортер модом, и загружал их на pastebin, все отлично срабатывало и хранил только URL'ки :)

Идея то реально хорошая, если внедрить это прям в лаунчер и загружать логи на пастебин через апи и хранить ток юрлки)

**Comment by Will0376** [comment]
Нафиг pastebin? есть Hastebin! :D без апи. (класс для залития на него текста и получения ссылки - https://hastebin.com/ojegosimoh.cs )
