### ISSUE TITLE
4.5.0 игнорирует Update Exclusions

### ISSUE THREAD

**Issue by Sirse** [GravitLauncher/Launcher#211]
![изображение](https://user-images.githubusercontent.com/3335371/55648448-8cffc380-580a-11e9-9559-e6b14766a872.png)

`2019.04.06 01:19:52 [ERROR] java.lang.SecurityException: Forbidden modification (ENTRY_CREATE, 1 times): '...\mods\OpenTerrainGenerator'
	at ...`

**Comment by gravit0** [comment]
`...\mods\OpenTerrainGenerator`
Очень странный путь. Windows/Linux? Нужны дополнительные данные о проблеме

**Comment by Sirse** [comment]
При отключении Radon - всё работает.

**Comment by Sirse** [comment]
> 
> 
> `...\mods\OpenTerrainGenerator`
> Очень странный путь. Windows/Linux? Нужны дополнительные данные о проблеме

Вин, просто затёр часть пути точками

**Comment by gravit0** [comment]
Radon? Никаких исключений радон не выбрасывал?

**Comment by Zaxar163** [comment]
Сделай без прогуарда но с радоном. И скинь в #active.

**Comment by Sirse** [comment]
> 
> 
> Radon? Никаких исключений радон не выбрасывал?

Нет, специально сейчас проверил, и при сборке, и при работе молчит
