### ISSUE TITLE
Guard, как папка скачиваемая с сервера.

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#215]
Позволит уменьшить размер jar.

**Comment by TheQukallon** [comment]
А что с защитой станет?)

**Comment by gravit0** [comment]
Не имеет смысла

**Comment by TheXaver** [comment]
Может быть полезно для защит без помощи

**Comment by Sa1ZeR** [comment]
Как минимум, антивирус не будет ругаться так сильно на скачиваемый jar/exe файл

**Comment by gravit0** [comment]
Скачивание исполняемых exe и dll сайтов бесит антивирусы намного больше. Даже если они чистые легко получить клеймо Trojan.Downloader
