### ISSUE TITLE
Sentry Io для логов

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#217]
Можно использовать sentry io для сбора крашей, а также логов защиты, ну и сбор логов запуска

**Comment by Zaxar163** [comment]
Приведи пример реализации.

**Comment by TheXaver** [comment]
Пример привести не могу, но там есть интеграция с log4j

**Comment by TheXaver** [comment]
https://imgur.com/a/g8Ti877 да и просто на java

**Comment by Scheshi** [comment]
У pastebin для такого есть API
https://pastebin.com/api

**Comment by xxDark** [comment]
> 
> 
> У pastebin для такого есть API
> https://pastebin.com/api

Мда.

**Comment by Zaxar163** [comment]
32cfd3b и добавить в start в рантайме вызов Sentry.init(...);, положив библиотеку в launcher-libraries. Так же установить SentryUncaughtExceptionHandler и добавить каллбек для LogHelper.error(exc) (всё это из дизайна делается).
