### ISSUE TITLE
Реализация мультиязычности

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#221]
Если лаунчер выйдет за пределы РФ. Лаунчер и вики. Могу помочь с переводом на английский и немецкий.

**Comment by daniorio** [comment]
Также могу помочь с переводом на английский. Если нужно - только скажите.

**Comment by gravit0** [comment]
Оставляю голосование и обсуждение.
Если я не ошибаюсь все логи на английском языке и не нуждаются в переводе. Переводить консольные логи на русский черевато проблемами с кодировкой.
Наша wiki находится в соседнем репозитории Yii2Project. Если займетесь её дополнением и переводом это сильно поможет этой issue.
Перевод runtime можно сделать как он будет в stable состоянии.

**Comment by yaroslav4167** [comment]
Необходимость в том, что бы лаунчер сам подстраивался под язык в системе при первом запуске. Допустим, если проект ориентирован на большое количество стран. Но так же и имел в настройках принудительный выбор используемого языка интерфейса.
Конечно, можно изначально сделать полностью английский лаунчер. Но.. Думаю.. Это будет не удобно для некоторых пользователей.

**Comment by Zaxar163** [comment]
@yaroslav4167 Начнём с перевода wiki. По рантайму у меня есть 1 идея, чтобы он на 11 заработал, только это его переписать на Java и кое-что убрать.

**Comment by LoomeL** [comment]
А кто в саппорте будет на английском отвечать?

**Comment by Kotikstar** [comment]
Я могу помочь с переводом на Литовский

**Comment by Locomenmod** [comment]
> Я могу помочь с переводом на Литовский

В данный момент перевод лаунчера не актуален. Если только начать с вики.

**Comment by Kotikstar** [comment]
@Locomenmod го

**Comment by LoomeL** [comment]
Я могу сделать вынос сообщений в рантайме в отдельный файл, удобно будет редактировать при создании дизайна

**Comment by Locomenmod** [comment]
> Я могу сделать вынос сообщений в рантайме в отдельный файл, удобно будет редактировать при создании дизайна

Давай. Тогда потихоньку будут переводить.
