### ISSUE TITLE
Вывод примерных ошибок и их решение

### ISSUE THREAD

**Issue by AttempGame** [GravitLauncher/Launcher#225]
После краша лаунчера/не запуска клиента/краша клиента игроку открывался текстовый документ/окно где список проблем и их решение или же лаунчер сам индифицировал ошибку по логам и предоставлял примерное решение данной проблемы, полезно для владельцев мелких проектов

**Comment by Zaxar163** [comment]
Это не то. Тогда уж парсер ошибок, но и он зачем непонятно.

**Comment by gravit0** [comment]
Как в TLauncher? Но и сам TLauncher очень топорно понимает логи и самые стандартные ошибки не понимает.
Думал над этим, но ничего умного не придумал
Закрою пока

**Comment by gravit0** [comment]
Если соберете приличный список ошибок их решений то я форкну Алуриэль и будет она автоматически решать частые проблемы на вашем дискорд сервере
