### ISSUE TITLE
Лаунчер не сохраняет настройки

### ISSUE THREAD

**Issue by bigenergy** [GravitLauncher/Launcher#228]
На версии 4.5.0 перестали сохраняться настройки.
Через несколько запусков тупо требуется авторизация снова, по логам - лаунчер не может прочитать файл настроек.

Баг ловится через раз, как только снова поймаю - отправлю точные логи.
Точнее - логин/пароль сбрасываются, и при каждом заходе в настройки лаунчера, дебаг чекбокс становится чекнутым, даже если его анчекнуть и снова перезапустить лаунчер. С настройкой смены папки аналогичная проблема.

**Comment by gravit0** [comment]
Дебаг чекбокс включится автоматом только если у вас env выставлен в DEBUG
Нужны точные логи

**Comment by gravit0** [comment]
Настройки НЕ будут сохраняться если лаунчер был закрыт через диспетчер задач, крашнулся и (возможно) при запуске клиента без дебага. Таково Settings API Сашка.
В 5.0 конфиги на json и управление настройками частично передано Java коду, что позволит избежать таких проблем.

**Comment by bigenergy** [comment]
> Нужны точные логи

https://pastebin.com/aC6Fd7Ki

**Comment by bigenergy** [comment]
> Дебаг чекбокс включится автоматом только если у вас env выставлен в DEBUG

Не выставлен.

**Comment by gravit0** [comment]
Лог не дает никакой информации, кроме того что
Файл настроек поврежден
Маловероятно что этот баг можно исправить простыми методами

**Comment by gravit0** [comment]
Так же нужны логи запуска, когда происходит запись сбойного файла настроек

**Comment by Zaxar163** [comment]
@gravit0 это ещё баг `кривого обновления`, тогда старый файл настроек становится обузой.

**Comment by bigenergy** [comment]
> Так же нужны логи запуска, когда происходит запись сбойного файла настроек

А больше ничего и не выбрасывает.

**Comment by bigenergy** [comment]
https://hastebin.com/ibapavaveh.sql
Инструкция по ловле:
1) Скачиваем лаунчер
2) Открываем, авторизируемся
3) В настройках лаунчера выставляем любые изменения
4) Стартуем клиент, ловим ошибку записи настроек
5) После следующего запуска лаунчера, лаунчер заявит о поврежденном файле настроек

**Comment by gravit0** [comment]
Пришлите маппинги

**Comment by bigenergy** [comment]
> Пришлите маппинги
[mappings.zip](https://github.com/GravitLauncher/Launcher/files/3119291/mappings.zip)

**Comment by gravit0** [comment]
Проблема в вашем runtime. При обновлении вы некорректно перенесли изменения.
https://github.com/GravitLauncher/Launcher/blob/master/Launcher/runtime/dialog/dialog.js#L229
Вот так должна выглядеть функция doUpdate.
