### ISSUE TITLE
Support 1.14

### ISSUE THREAD

**Issue by Locomenmod** [GravitLauncher/Launcher#229]
Хотелось бы увидеть возможность добавлять клиент для 1.14
`[ERROR] java.lang.IllegalArgumentException: Unknown client version: '1.14'`

**Comment by TheQukallon** [comment]
Хм, а тебе самому собрать клиент в падлу?

**Comment by Mr-Krab** [comment]
@TheQukallon не тупи.

**Comment by Zaxar163** [comment]
Там надо саппорт в профилях добавить.

**Comment by TheQukallon** [comment]
@Mr-Krab Окей, в коде дописать, и почему бы не сделать конфиг отдельный в который можно будет писать 1.8.8, 1.14, и.т.д

**Comment by gravit0** [comment]
Берите конфиг от 1.12 и будет вам счастье
