### ISSUE TITLE
Запуск serverWrapper ошибки

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#242]
License for ServerWrapper GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
2019.05.02 23:38:55 [INFO] Load modules
2019.05.02 23:38:55 [INFO] Loaded 0 modules
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019.05.02 23:38:56 [INFO] ServerWrapper: Project MineCraft, LaunchServer address: ws://launch..su:9274/api. Title: TechnoMystic
2019.05.02 23:38:56 [INFO] Minecraft Version (for profile): 1.7.10
2019.05.02 23:38:56 [INFO] Start Minecraft Server
[23:38:58 INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker

Также заметил, что не проверяется ProjectName

**Comment by gravit0** [comment]
Ошибки slf4j не важны и можно игнорировать
Больше в вашем логе ошибок я не нашел
