### ISSUE TITLE
Пинг серверов с лаунч сервера

### ISSUE THREAD

**Issue by Mr-Krab** [GravitLauncher/Launcher#245]
Лучше сделать так, что бы пинг серверов выполнял лаунч-сервер, так как игровые сервера могут находится за банжей и не слушать сеть. А лаунчер на клиенте брал инфу по онлайну на серверах с лаунч-сервера.
Данные настройки так же думаю в профайле можно сделать в виде дополнительных, если по какой-либо причине это может нарушить работу лаунчера/проверки авторизации.

**Comment by Zaxar163** [comment]
Есть все возможности заменить ServerPinger на проверку онлайна через ваш PHP скрипт на сервере. Для этого нужна модификация runtime не более.
