### ISSUE TITLE
Debug: true При скачивании

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#246]
![image](https://user-images.githubusercontent.com/18555344/57178075-22c35880-6e74-11e9-9ca6-1dc3a2eed2be.png)
При скачивании клиентов и asset'ов получается каша в логировании

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/d33909af1f9afd70b3667a9ef2fe8e7bd0d7b51d

**Comment by TheXaver** [comment]
![image](https://user-images.githubusercontent.com/18555344/57309428-bbfea300-70f0-11e9-82f6-0cf311331ad4.png)
вообще лог скачивания пропал
