### ISSUE TITLE
Регистрация внутри лаунчера

### ISSUE THREAD

**Issue by AttempGame** [GravitLauncher/Launcher#253]
Раньше, в старом сашке была такая вот функция, довольно хорошая вещь для проектов на лаунчере но без сайта, а есть такие вот...

**Comment by gravit0** [comment]
#144 
Решите все те вопросы по которой я закрыл issue
И готовы ли вы сверстать форму регистрации? Готовы ли вы предоставить способ защиты от ботов?
Ну а пока ответа нет я закрою.
Будут ответы - откроем
