### ISSUE TITLE
Выключаемый GravitLauncherStore 

### ISSUE THREAD

**Issue by TheXaver** [GravitLauncher/Launcher#267]
Выключаемый GravitLauncherStore, название говорит за себя

**Comment by sasha0552** [comment]
+1

**Comment by gravit0** [comment]
Этим вы проявляете неуважение к пользователям своего проекта
Вы можете в config.js изменить ProjectStore, то есть расположение Store вашего проекта.
Тогда при поиске другие лаунчеры не найдут ваш проект
Тем не менее будет добавлена команда ручного добавления store файлов через консоль лаунчера.
Тогда другие лаунчеры смогут работать с уже загруженными файлами вашего проекта, но только если пользователь вручную укажет путь до вашей папки с store
Тем не менее вы свою ненависть к другим проектам удволетворите

**Comment by sasha0552** [comment]
@TheXaver создал форк без этого всего, туда походу буду кидать только нормальные коммиты. Меня это не устраивает, неотключаемая "фича".
