### ISSUE TITLE
Противный баг GUI опциональных модов

### ISSUE THREAD

**Issue by yaroslav4167** [GravitLauncher/Launcher#275]
При включении/отключении опциональных модов - обновляется и откидывает на верх.
![WiW8J1lvSl](https://user-images.githubusercontent.com/18057310/58387618-ba4e3e00-8011-11e9-9fe5-7d6a52299985.gif)

**Comment by DrLeonardo95** [comment]
test fix in [https://github.com/GravitLauncher/Launcher/tree/feature/design](url)
need testing
