### ISSUE TITLE
Преложение сделать альтернативную p2p сеть скачивания клиентов

### ISSUE THREAD

**Issue by Beshelmek** [GravitLauncher/Launcher#277]
На больших проектах очень сильно можно разгрузить сеть, а так же повысить скорость скачивания клиентов. 
Можно взять за основу: [rohan23chhabra/p2p](https://github.com/rohan23chhabra/p2p)

**Comment by TheXaver** [comment]
Может быть тогда торрент трекер включить?

**Comment by gravit0** [comment]
Вы вполне лично для своего проекта можете организовать такую сеть сделав торрент файлы и запустив на сервере, машинах модераторов/администраторов раздачу. Будут подключатся активные пользователи и скорость еще увеличится

**Comment by radioegor146** [comment]
Фича ради фичи

**Comment by TheXaver** [comment]
Нуу с 1000 онлайна, cdn получается дорогой, а вот p2p неплохой вариант

**Comment by radioegor146** [comment]
Я думаю что для проекта с 1000 онлайна CDN - не очень дорого (к примеру у Google). Но а вот то что далеко не все пользователи захотят пользоваться P2P ввиду публикации их IP адреса это вполне вероятно.

**Comment by TheXaver** [comment]
$0.02/GB - $0.08/GB for North America and Europe destinations
$0.04/GB - $0.20/GB for other destinations worldwide
а игрок в среднем скачивает по 1 гигабайту
https://cloud.google.com/cdn/

**Comment by radioegor146** [comment]
В крайнем случае владелец может использовать не CDN, а GCS к примеру. Имхо пока что я не видел нигде использование P2P. Даже на достаточно крупных проектах типа VW используется простое хранилище т.к. это проще, безопаснее и надёжнее.

**Comment by TheXaver** [comment]
А если типа торрент трекера?

**Comment by radioegor146** [comment]
> Но а вот то что далеко не все пользователи захотят пользоваться P2P ввиду публикации их IP адреса это вполне вероятно.

**Comment by TheXaver** [comment]
Думаю можно сделать как отключаемую фичу.

**Comment by gravit0** [comment]
Видел p2p скачивание только в WoT.
Другие же проекты с милионами игроков(World of Warcraft) не используют p2p

**Comment by TheXaver** [comment]
нуу Akamai дорогой, а из рашки, кто нормальный..... может быть GcoreLabs, все наверное.

**Comment by radioegor146** [comment]
+ будут (как мне кажется) проблемы при обновлении клиента
А в чём проблема использовать тот же Google Cloud Storage? Чем он плох в данном случае?

**Comment by TheXaver** [comment]
Рашки нет, и несколько локаций в европе, а так cdn у тебя раздача повсюду. а вот любое хранилище только с одной локации. понятное дело. что можно балансить, но для этого и есть cdn.

**Comment by Beshelmek** [comment]
Когда у тебя трафик несколько терабайт в месяц, начинаешь думать по другому.
