### ISSUE TITLE
Не работает консоль в лаунчере после повторной авторизации

### ISSUE THREAD

**Issue by cyber01** [GravitLauncher/Launcher#280]
Если авторизоваться в лаунчере, нажать на кнопку консоли, собственно попасть в консоль, закрыть ее (на кнопку свернуть жму), а нажать кнопку Выйти (чтобы вернуться на экран авторизации), а потом снова авторизоваться - то при нажатии на кнопку консоли ничего не происходит.

Использую собранный из мастера лаунчер. (собирал сегодня свежий).

**Comment by Zaxar163** [comment]
Это не баг, просто невнимательность пользователя, он жмёт на свернут а не закрыть, консоль открывается в отдельном окне. и на неё можно выйти внизу с панели задач. @cyber01

**Comment by Zaxar163** [comment]
Issue Management: Без ответа закрою через 24ч.
