### ISSUE TITLE
Не отображаются updateOptional с permissions:1

### ISSUE THREAD

**Issue by leshasmlesha** [GravitLauncher/Launcher#285]
Не отображается updateOptional c permissions:1

**Comment by leshasmlesha** [comment]
Решение нашёл, надо в runtime'е изменить в файле dialog/scenes/options/options.js строчку 103
c if(modFile.permissions != 0 && ((loginData.permissions.toLong() & modFile.permissions) != 0))
на if(modFile.permissions != 0 && ((loginData.permissions.toLong() & modFile.permissions) = 0))

**Comment by Zaxar163** [comment]
92c4144
