### ISSUE TITLE
Исправление на Wiki Раздел HWIDHandler

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#307]
В способе MySQL строке  "paramsHwids": 

"%macAddr%" заменить на "%MAC%"
в строке "paramsBan":
"%macAddr%" заменить на "%MAC%"
в строке "hwidFieldMacAddr": "macAddr", 
"hwidFieldMacAddr" изменить на "hwidFieldMAC"

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Yii2Project
