### ISSUE TITLE
Улучшение дизайна

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#332]
Заменить весь путь к файлу на конкретное название файла в сцене загрузки. Будет гораздо удобнее и понятнее.
![изображение](https://user-images.githubusercontent.com/42574494/64079854-bfe4af80-ccf5-11e9-9f0c-d0a126aeee99.png)

**Comment by LoomeL** [comment]
Открываешь жс и выпиливаешь название файла, тем более оно никому не нужно

**Comment by daniorio** [comment]
Это еще не все предложения, просьба не закрывать раньше времени. В ближайшие 3 дня распишу тут все недочеты.

**Comment by LoomeL** [comment]
А недочёты с точки зрения говнокода считаются?

**Comment by daniorio** [comment]
До кода я еще не дошел, но кривизну дизайна уже увидел

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64644836-3b441080-d41c-11e9-9753-5d4a82b0e505.png)
Так-с, начнем, пожалуй. Во-первых, кнопки не похожи не кнопки вовсе. Стоит добавить им анимацию нажатая/наведения, чтобы было понятно, с чем мы имеем дело.

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64645001-9a098a00-d41c-11e9-8e34-44e35715c63b.png)
![изображение](https://user-images.githubusercontent.com/42574494/64645021-a1c92e80-d41c-11e9-9985-9141e9063be0.png)
Белые области в панели входа и логина имеют разную дляну, крайне плохо смотрится переход от одной панели к другой.

**Comment by DrLeonardo95** [comment]
> ![изображение](https://user-images.githubusercontent.com/42574494/64644836-3b441080-d41c-11e9-9753-5d4a82b0e505.png)
> Так-с, начнем, пожалуй. Во-первых, кнопки не похожи не кнопки вовсе. Стоит добавить им анимацию нажатая/наведения, чтобы было понятно, с чем мы имеем дело.

Библиотека с анимациями была в ранних версиях, но jfoenix была удалена в связи с не совместимостью, если кто то напишет анимации в JS будет неплохо. @LoomeL 
Не вижу никаких проблем добавить эффекты через css которые кст вроде и так есть.

> ![изображение](https://user-images.githubusercontent.com/42574494/64645001-9a098a00-d41c-11e9-8e34-44e35715c63b.png)
> ![изображение](https://user-images.githubusercontent.com/42574494/64645021-a1c92e80-d41c-11e9-9985-9141e9063be0.png)
> Белые области в панели входа и логина имеют разную дляну, крайне плохо смотрится переход от одной панели к другой.

Это уже вкусовщина, хотя где то соглашусь :)

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64645103-cfae7300-d41c-11e9-9239-7dc5b7a3aa0f.png)
Смотрим дальше. Первое, что бросается в глаза - кривизна картинки. Куда она съехала? Что за непонятные области справа и сверху? Вторая, уже менее явная, но более грубая ошибка - что это за обрубки изображений в правом верхнем и левом нижнем углу экрана?
![изображение](https://user-images.githubusercontent.com/42574494/64645294-42b7e980-d41d-11e9-9d5a-ac9d625411b8.png)

**Comment by DrLeonardo95** [comment]
> ![изображение](https://user-images.githubusercontent.com/42574494/64645103-cfae7300-d41c-11e9-9239-7dc5b7a3aa0f.png)
> Смотрим дальше. Первое, что бросается в глаза - кривизна картинки. Куда она съехала? Что за непонятные области справа и сверху? Вторая, уже менее явная, но более грубая ошибка - что это за обрубки изображений в правом верхнем и левом нижнем углу экрана?
> ![изображение](https://user-images.githubusercontent.com/42574494/64645294-42b7e980-d41d-11e9-9d5a-ac9d625411b8.png)

А вот это я исправлял, я нз куда пропал фикс, так как было 2 коммита с исправлением этого. @gravit0 куда оно опять пропало?

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64645328-5cf1c780-d41d-11e9-9edc-9cf81ffcb09e.png)
Как дополнение хочу добавить вот что: не прорисованы поля пароля и логина. Такое себе дело. Но тут уже каждому свое, как говорится.

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64645526-c245b880-d41d-11e9-80b0-d0d7ce581f55.png)
И вот еще что. Какой смысл заменять текст на кнопке "Удалить клиенты" на "еще раз"? Бесполезно. И, собственно, вот еще что. По-моему, там с сашка еще тянется такая "фича": при нажатии кнопки "Удалить клиенты" запускается счетчик, и после достижения определенного кол-ва кликов он рубит лаунчер. Это тоже нахер не нужно. Но тут надо проверить, в код я еще не лез.

**Comment by daniorio** [comment]
Так же присутствует нелогичное разделение действий, скажем так. Чтобы закрыть настройки, нужно нажать на одну кнопку, а чтобы закрыть окно опциональных модов - надо нажать на другую. Тоже как-то нелогично.
![изображение](https://user-images.githubusercontent.com/42574494/64645847-78110700-d41e-11e9-80ef-373a2b14f738.png)
![изображение](https://user-images.githubusercontent.com/42574494/64645859-7fd0ab80-d41e-11e9-8094-aeff6f35d833.png)
Ну и сама стрелка закрытия окна расположена в неподходящем месте.

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64645957-b0b0e080-d41e-11e9-9b55-02c6448ee75a.png)
А тут слабо было под один стиль?

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64646050-dfc75200-d41e-11e9-9cdf-667924acff90.png)
Тут лучше сделать выравнивание по центру

**Comment by daniorio** [comment]
Относительно диайна вроде бы все, как будет время, гляну код

**Comment by sasha0552** [comment]
> 
> 
> ![изображение](https://user-images.githubusercontent.com/42574494/64645526-c245b880-d41d-11e9-80b0-d0d7ce581f55.png)
> И вот еще что. Какой смысл заменять текст на кнопке "Удалить клиенты" на "еще раз"? Бесполезно. И, собственно, вот еще что. По-моему, там с сашка еще тянется такая "фича": при нажатии кнопки "Удалить клиенты" запускается счетчик, и после достижения определенного кол-ва кликов он рубит лаунчер. Это тоже нахер не нужно. Но тут надо проверить, в код я еще не лез.

да, это с сашка. да и впринципе, не мешает, я считаю что пусть будет.

**Comment by LoomeL** [comment]
С сашка только повторное удаление папки

**Comment by daniorio** [comment]
![изображение](https://user-images.githubusercontent.com/42574494/64920847-b3b42400-d7c4-11e9-806e-aa7d89ea1a5e.png)
Это что б наверняка проверка сработала?

**Comment by daniorio** [comment]
Закрываем эту ишую
