### ISSUE TITLE
Улучшение рантайма

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#334]
1) Мультиязычность https://github.com/GravitLauncher/Launcher/issues/221
2) Изменение структуры:
Сделать все сцены в виде оверлеев или оверлеи в виде сцен, для каждого оверлея добавить свой скрипт инициализации, в dialog сунуть все основные функции, не относящиеся к дизайну, единый css файл для всех оверлеев, добавить в папку с картинками отдельные папки для каждого оверлея.

!!!Перенести все функции в диалог, в остальных скриптах оставить только то, что связано напрямую с дизайном, дабы упростить дальнейшее портирование рантайма на новые версии

**Comment by daniorio** [comment]
Из менее важных функций: отключение лишних оверлеев, таких как консоль и опциональные моды, в конфиге

**Comment by daniorio** [comment]
Красиво оформить все fxml файлы, со всеми переносами
![изображение](https://user-images.githubusercontent.com/42574494/64926358-10cfca00-d805-11e9-894d-dc78cabb1c63.png)

**Comment by daniorio** [comment]
+ https://github.com/GravitLauncher/Launcher/issues/332

**Comment by daniorio** [comment]
https://github.com/GravitLauncher/Launcher/issues/315 И вот это туда же

**Comment by LoomeL** [comment]
Ищем раба :roflanpominki:

**Comment by LoomeL** [comment]
Засовывать все css в один это гон

**Comment by LoomeL** [comment]
Сцены это каркас а оверлеи накладываются поверх в маску

**Comment by LoomeL** [comment]
@daniorio Кстати, гоовновид в *.fxml делает SceneBuilder

**Comment by DrLeonardo95** [comment]
@daniorio 
1. Делать все сцены оверлеями не нужно (некоторые сцены были специально переработаны из оверлея)
2. Совать все в один КСС глупость, кому кажется это удобно, может сам себе сделать.
3. Перенос функций - не вижу в этом смысла, все и так на своих местах.
4. Отключение не нужных сцен можете сделать сами убрав их инициализацию, или банально кнопку :D

**Comment by LoomeL** [comment]
Ну да, сделать из оверлея опций сцену, гениально.

**Comment by LoomeL** [comment]
(нет)

**Comment by DrLeonardo95** [comment]
@LoomeL ¯\_(ツ)_/¯

**Comment by LoomeL** [comment]
А нахуя если не секрет?

**Comment by DrLeonardo95** [comment]
@LoomeL 
1. Выражайся попроще, это не чат.
2. Если не нравится, переделай себе сам, я считаю это правильным решением.

**Comment by LoomeL** [comment]
![image](https://user-images.githubusercontent.com/44950511/66597024-e4b72700-ebbf-11e9-8902-b435bad5a548.png)

**Comment by JoCat** [comment]
> Совать все в один КСС глупость

\+ соглы
Можно оставить только для общих стилей всего рантайма (шрифты, кнопки и проч. хренота)

**Comment by LoomeL** [comment]
![image](https://user-images.githubusercontent.com/44950511/66597126-2647d200-ebc0-11e9-9bef-9df5db26838a.png)

**Comment by LoomeL** [comment]
Прикинь, это ооочень удобно

**Comment by daniorio** [comment]
Ну и зачем было закрывать ишую? Тут как бы и мультиязычность, и много другое нужное, в том числе фикс картинки.

**Comment by LoomeL** [comment]
Забей, это Леонардо

**Comment by LoomeL** [comment]
Привыкай так сказать

**Comment by DrLeonardo95** [comment]
@daniorio 
1. Я пояснил по пунктам свое мнение
2. Срач разводить здесь не нужно

Мультиязычность есть в #221, остальное считаю бессмысленным, кому надо сами сделают себе структуру такую какую им надо, переделывать что-то что и так отлично работает если кому то не угодно - глупо

По поводу оформления кода fxml согласен.
@Zaxar163 как думаешь?
