### ISSUE TITLE
Имитация браузера при получении скинов и плащей

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/Launcher#339]
Так как лаунчер сделан с поддержкой клауда, то почему бы лаунчеру не имитировать обращение к веб-серверу через браузер, дабы в клауде не отключать проверку обращения только через браузер. Так же было бы хорошо, если бы можно было выставлять кастомный юзерагент в конфиге лаунчсервера.

**Comment by Zaxar163** [comment]
cb91f83
