### ISSUE TITLE
Отсутствуют сообщения в рантайме при скачивании zip-архивом

### ISSUE THREAD

**Issue by bigenergy** [GravitLauncher/Launcher#340]
При настройке bindings в конфиге лаунчсервера, рантайм не знает о загрузке zip архива и отображает 0% загрузки, но скачивание и распаковка идут (судя по дебагу).
Версия 5.0.10 dev

**Comment by bigenergy** [comment]
Воспроизводится очень просто, настраиваем в конфиге лаунчсервера bindings
` "bindings": {
        "asset1.12.2" : { "url": "http://ip:port/assets.zip" }
	},`
Пакуем нужную папку клиента в zip, перезапускаем лаунчсервер. Баг воспроизводится на стоковом рантайме, по логам скачивание идет, но процесс в рантайме не отображается.

**Comment by Zaxar163** [comment]
Спасибо, вечером посмотрю.

**Comment by krap0299** [comment]
У меня такая же проблема, юзаю билд #88831831.

**Comment by Zaxar163** [comment]
Это уже рантайм...

**Comment by krap0299** [comment]
Fix будет скоро?

**Comment by krap0299** [comment]
кстати лаунчер ,при распаковке, почему то не распаковывает джарники
[https://downloader.disk.yandex.ru/preview/5eea5eafe53273d330523215d7726a2b202d66de14396d909c4b85ee442d5373/5db04e6c/Tcw8_5_bFDxI0PXw6Pn3STLoUHLSBxPHpZzukVWNoMYcqCrInR3dSqGuII27SsogIz3yeSyXkiFp9eLzJT_ghQ==?uid=0&filename=Screenshot_267.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=338787878&size=2048x2048](url)

**Comment by Zaxar163** [comment]
Давно исправлено.
