### ISSUE TITLE
Криво работает "Сменить директорию загрузки"

### ISSUE THREAD

**Issue by ResponsibleBear** [GravitLauncher/Launcher#344]
Нажимаем кнопку "Сменить директорию загрузки", выбираем новую директорию, в модальном окне нажимаем кнопку "Да, перенести!" получаем ошибку https://pastebin.com/SfdGY1mk ошибка будет повторяться при каждом нажатии кнопки пока не нажмем кнопку "Нет не нужно".

Нажимаем кнопку "Нет не нужно", повторно проделываем все действия и только тогда перенос срабатывает.
Тестировалось на дефолтном рантайме, версия последняя собранная из исходников.

**Comment by Zaxar163** [comment]
Баг как выяснилось JavaFX, мало того старый.

**Comment by saltek1995** [comment]
#353

**Comment by Zaxar163** [comment]
ac737c4ccb0b76276ead391eb55631fac4e172d8
