### ISSUE TITLE
Баг запуска собственной джавы

### ISSUE THREAD

**Issue by WhiteBite** [GravitLauncher/Launcher#345]
Решил перейти на лайст версию 
GravitLauncher (fork sashok724's Launcher) LaunchServer v5.0.9-1 stable (build #1)

При запуске клиента получаю 
`У Вас установлена Java 32, но Ваша система определена как 64. Установите Java правильной разрядности                     `

Все настройки выставил. Новую джаву с сервера он качает, но видимо запускает через старую.

**Comment by gravit0** [comment]
После изменения настроек необходимо перезапускать лаунчсервер и делать build!

**Comment by WhiteBite** [comment]
Было перезапущено все что можно, билд и апдент тоже прописан

**Comment by WhiteBite** [comment]
В данный момент накатил 64-битную джаву. И временно решил проблему, но могу продемонстрировать при необходимости

**Comment by WhiteBite** [comment]
Решается сменой параметра `"warningMissArchJava"` на `false`
