### ISSUE TITLE
Изменение архитектуры рантайма

### ISSUE THREAD

**Issue by Kotikstar** [GravitLauncher/Launcher#347]
Изменение языка выполнения, пересмотр стилей и fxml, нормальный transparent.

**Comment by LoomeL** [comment]
Леонардо скажет. что ты рукожоп и отправит тебя учится или в коммерцию

**Comment by Kotikstar** [comment]
@LoomeL а ты пофикси

**Comment by LoomeL** [comment]
time() = null

**Comment by Kotikstar** [comment]
Надо переделать все и можно убрать форк,
потому что будет уже совсем другой лаунчер

**Comment by Zaxar163** [comment]
Конечно же, предлагаете рантайм на Java - ну вы сами напросились.

**Comment by Zaxar163** [comment]
#332 #334

**Comment by Zaxar163** [comment]
#221 (Реализация мультиязычности) сюда же.

**Comment by LoomeL** [comment]
УРА

**Comment by Kotikstar** [comment]
Хоть раз нас услышали

**Comment by Kotikstar** [comment]
Насчёт мультиязычности, помочь?

**Comment by LoomeL** [comment]
А чем transperent не угодил

**Comment by DrLeonardo95** [comment]
> Леонардо скажет. что ты рукожоп и отправит тебя учится или в коммерцию

@LoomeL за себя говори а не за меня) лол)

**Comment by LoomeL** [comment]
Ещё скажи, что не так

**Comment by daniorio** [comment]
Сколько раз мы поднимали уже вопрос рантайма. Надо делать, а не обсуждать. Правда, у всех time() = null
