### ISSUE TITLE
Task :Launcher:compileJava FAILED

### ISSUE THREAD

**Issue by BCBAdrian** [GravitLauncher/Launcher#349]
https://pastebin.com/tYBNjzQX

Не знаю что и делать. На ВПС никак не хочет собираться, хотя на ПК всё нормально работает. Не могу найти в чём проблема, помогите.. :c

**Comment by TheXaver** [comment]
Установи openjfx и закрывай issues

**Comment by JoCat** [comment]
о боже, тупые вопросы теперь ещё и на гите?))
