### ISSUE TITLE
getuser broken

### ISSUE THREAD

**Issue by WhiteBite** [GravitLauncher/Launcher#357]
Сломалась команда getuser, getallusers 
Не знаю для чего она мне была нужна, но нашёл такую ошибку
![image](https://user-images.githubusercontent.com/19576772/74600361-8d5f2100-50a1-11ea-8c4f-62d78eaa142b.png)

**Comment by Zaxar163** [comment]
У вас не настроен Hibernate DAO, поэтому эта команда не будет работать.
