### ISSUE TITLE
GUI Часть

### ISSUE THREAD

**Issue by dev-master21** [GravitLauncher/Launcher#363]
![image](https://user-images.githubusercontent.com/16816228/76712464-92b49780-6743-11ea-85fb-213e94ed42e0.png)
Вот такая вот ошибочка. Есть какая либо инструкция как это делать? Ничего не нашёл.

**Comment by JoCat** [comment]
`rm -rf /*` попробуй, говорят помогает

**Comment by SakuMai** [comment]
Та же самая ошибка._.

**Comment by KillGam** [comment]
И толку, поставил новый рантайм все собрал по новой и все равно пишет что модуль GUi не найден
