### ISSUE TITLE
[Bugs] Баг при обновлении лаунчера

### ISSUE THREAD

**Issue by Sepera-okeq** [GravitLauncher/Launcher#365]
Когда имеется более новый билд лаунчера на сервере,старый лаунчер на ПК потенциального игрока обновляется криво,создает копии себя и не может толком обновится из-за огромного количества копий и в вследствие этого приходится стопать все процессы на ПК.

Версия лаунчера 5.1.1 stable - 5.3.1 dev (где есть этот баг)

**Comment by ijo42** [comment]
А где ты взял 5.3.1 dev?) Актуальная 5.1.3 dev

**Comment by Scheshi** [comment]
> А где ты взял 5.3.1 dev?)
Миссклик, кринж

**Comment by JoCat** [comment]
#366 #368 Копии
Ошибка аналогичная, беды с LauncherStartScreen.

Решение: не использовать данный модуль

@gravit0 считаю ишью можно закрывать

**Comment by Scheshi** [comment]
Аналогичная ошибка. Помогла установка LaunchServer другой версии.
https://cdn.discordapp.com/attachments/478133900045189122/694736682162847785/LaunchServer.jar
