### ISSUE TITLE
Баги, баги

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#366]
По просьбе radioegor146 и DrLeonardo, помимо видео в канале #general описываю свои проблемы тут:
1. #365 можно наблюдать [данном видео](https://youtu.be/zvDHhm2kSTc).
2. При входе сначала под одними данными пользователя(логин:пароль), выхода с аккаунта и входа под данными другого пользователя, не меняется никнейм в servermenu. Не проверял, какой никнейм будет в игре. Наблюдать данное явление можно на [данном видео](https://www.youtube.com/watch?v=ZiJVplCPz28).
3. При build лаунчера на **Java 11** возникает данная ошибка:

> `2020.03.31 10:16:34 [ERROR] java.lang.RuntimeException: Exception in Application start method
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.lang.AbstractMethodError: Receiver class pro.gravit.launcher.abODeoFlegenDS does not define or inherit an implementation of the resolved method 'abstract void start(javafx.stage.Stage)' of abstract class javafx.application.Application.
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
>         at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
>         ... 1 more`

На **Java 8** после build лаунчер запускается без проблем.

**Comment by gravit0** [comment]
У вас ProGuard не нашел библиотеки javafx и поэтому обфнул те методы, которые не нужно было обфать
В скрипт установки будут добавлены инструкции по установке openjfx и проверки на его наличие

**Comment by gravit0** [comment]
1. Баг не воспроизводится
2. Баг визуальный, в игре будет правильный никнейм

**Comment by Scheshi** [comment]
Продолжаем.
При открытии лаунчера возникает 2 процесса javaw.exe. При закрытии окна лаунчера процесс остается висеть.
Глянуть можно на [данном видео](https://youtu.be/DvtxCh5QxKE).

**Comment by Scheshi** [comment]
> Баг не воспроизводится
Мне интересно как так. У всех воспроизводится, а у Вас нет. Я все прекрасно показал на видео. Вы видите своими глазами.

**Comment by JoCat** [comment]
> Баг визуальный, в игре будет правильный никнейм

То что он "визуальный" не отменяет того что это баг и его нужно фиксить.
Но ток да, это скорее в рантайм репу писать надо было.

Для @Scheshi эт туда:
https://gitlab.com/gravitlauncherteam/launcherjavaruntime/-/issues

**Comment by Scheshi** [comment]
> косяки по рантайму туда:

нихуя страшного, не потеряют, если надо это фиксить.
