### ISSUE TITLE
Не скачивается файл с файлового сервера под nginx

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#367]
Пытаюсь скачать клиент, вылезает ошибка такого вида:
`Exception class java.util.concurrent.CompletionException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://site.org/client/libraries/fastutil-7.1.0.jar?#`
Каким там боком появилось **?#** я не понимаю. Настройка nginx обычная, имеется только автоиндекс.
Важно подметить, что при запуске с Dlauncher.debug все прекрасно качается.
Я не знаю, с лаунчером беды или с нгинксом, но я облазил весь интернет и не нашел ничего.

**Comment by gravit0** [comment]
Прочитайте инструкцию как настроить cloudflare в канале #important "проблемы с доступом при использовании cloudflare

**Comment by Scheshi** [comment]
Ну я же не первый день гравитом пользуюсь, лол.
![image](https://user-images.githubusercontent.com/47576867/78089224-95d29900-737b-11ea-8edc-01a4fef89513.png)

**Comment by gravit0** [comment]
Вы выключили только для корня
Где *, лол?

**Comment by Scheshi** [comment]
Действительно. Пара бессонных ночей за тестом дают о себе знать.
