### ISSUE TITLE
Баги, баги v2

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#368]
Не закрывайте ишуи, я сюда буду кидать все, что нахожу, чтобы по сто раз не открывать новые.
Продолжаем.
При открытии лаунчера возникает 2 процесса javaw.exe. При закрытии окна лаунчера процесс остается висеть.
Глянуть можно на [данном видео](https://youtu.be/DvtxCh5QxKE).
И по #366 : Вы сами своими глазами видите, что баг еще как воспроизводится. И воспроизводится у всех, ибо жалоб в дискорде на это было очень много.

**Comment by gravit0** [comment]
По второму процессу: это не баг. Сначало запускается ClientLauncherWrapper, который затем запускает сам лаунчер с необходимыми ему параметрами. Так еще очень давно, намного раньше 5.0.11
По висящему процессу - баг связан с вашим модулем LauncherStartScreen, который вряд ли хорошо работает и вообще не нужен на 5.1+. Его писала не я и я за него не отвечаю
