### ISSUE TITLE
Кнопка "Сменить директорию загрузки" не переносит

### ISSUE THREAD

**Issue by ijo42** [GravitLauncher/Launcher#373]
LaunchServer: `85400d968bb4e7676b6e140f15a57eda1ce46e90`
LauncherRuntime: `09a828d88ce49ea407a55bd42e6715aad0858116`
Исходная папка: `C:\Users\89082\AppData\Roaming\DirtCraftNotStonks\updates` c двумя клиентами

Шаги к повторению:
1. Нажимаю кнопку _перенести_
2. Перехожу в `C:\Users\89082\AppData\Roaming\DirtCraft`
3. Создаю директорию `upd` через меню windows
4. Кнопка `Выбор папки`

После 3 шага получаю `C:\Users\89082\AppData\Roaming\DirtCraft\upd` в консоль
Папка `C:\Users\89082\AppData\Roaming\DirtCraft\upd` удаляется, но в настройках остается
Как итог, файлы остались не тронуты

**Comment by Zaxar163** [comment]
#374
