### ISSUE TITLE
serverAddress в массив.

### ISSUE THREAD

**Issue by Scheshi** [GravitLauncher/Launcher#377]
Я имею несколько серверов, стоящих на одном профайле. Нужно, чтобы он брал онлайн с нескольких серверов сразу и выводил их в лаунчер.
Предлагаю serverAddress и serverPort запихнуть в массив вида:
```
servers: [
{
"name": "Vanilla",
"address": "localhost",
"port": 25565
},
{
"name": "Anarchy",
"address": "localhost",
"port": 25566
}
```
А после значения массива складывать.
Также можно добавить такие вещи, как visible и permission, если кому-то это будет полезно.

**Comment by gravit0** [comment]
Вывод онлайна либо общий, либо вы сами должны будете сделать дизайн для этого в fxml

**Comment by LoomeL** [comment]
Панимаю, я это еще с 4.x.x предлагал -_-

**Comment by Sepera-okeq** [comment]
А ведь разве указание одинаковых папок в профайле не должно ли исправить? 

т.е
```
  "assetIndex": "1.12.2",
  "dir": "HiTech", 
  "assetDir": "asset1.12", 
  "title": "Cервер1", 
```
```
  "assetIndex": "1.12.2",
  "dir": "HiTech", 
  "assetDir": "asset1.12", 
  "title": "Cервер2", 
```




**P.S :  Да,идея хороша когда у вас несколько серверов одного типа и одного названия.**
В таком случае - такой функционал требуется.

Но как вижу - 
```
servers: [
{
"name": "Vanilla",
"address": "localhost",
"port": 25565
},
{
"name": "Anarchy",
"address": "localhost",
"port": 25566
}
```

Это чутка два разных сервера по тематике.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/b92e9a1d2955682e6be6d75df22def19fbea9642
