### ISSUE TITLE
Модульность лаунчера

### ISSUE THREAD

**Issue by DrLeonardo95** [GravitLauncher/Launcher#382]
**На основе отзывов**
В лаунчере существует лишний функционал из-за которого другая половина отваливается, оправдана ли поддержка Хибирнейта? Обычные запросы - профит, лаунчеру не нужно получать обновления постоянно, это ведь лаунчер - зашел в него, кликнул на клиент - лаунчер закрылся.

**от меня**

> Все технические пункты требуют пересмотра и более модульного подхода, для создания максимально "легкой" версии лаунчера, с базовым фунционалом.
> Самое важное решить технические проблемы на которые жалуются многие, ведь лаунчер должен работать из коробки не заставляя игрока танцевать с бубном в любом случае, либо свести эти случаи к максимальному минимуму.

_Этот issue будет пополнятся._

**Comment by sasha0552** [comment]
Лучше сделать хибернейт по дефолту

**Comment by gravit0** [comment]
Этот issue не несёт в себе смысла. Разбейте его на более мелкие КОНКРЕТНЫЕ предложения, а иначе этот issue ни о чем
