### ISSUE TITLE
Исправления runtime

### ISSUE THREAD

**Issue by DrLeonardo95** [GravitLauncher/Launcher#383]
8. Для сцены servermenu использовать кастомный serverImage-фон. Для каждого игрового сервера своя фоновая картинка.

5. Исправление заголовка названия функции (размер шрифта) и описания функции, это относится к элементам в сценах settings и options
![image](https://user-images.githubusercontent.com/45002341/80211032-8b838200-863d-11ea-8498-84c166cf60ba.png)

**Comment by gravit0** [comment]
Переместите этот issue в репозиторий рантайма
