### ISSUE TITLE
Preloader как модуль по умолчанию

### ISSUE THREAD

**Issue by DrLeonardo95** [GravitLauncher/Launcher#384]
Доработка и установка модуля preloader по умолчанию, что бы при запуске некоторые игроки не "сбивались с толку" долгим запуском игрового клиента.

**Comment by LoomeL** [comment]
У меня один вопрос, на Ху я?

**Comment by gravit0** [comment]
Нет технической возможности. Лаунчер никак не может узнать, получить доступ и вообще как либо взаимодействовать с окном майнкрафта
