### ISSUE TITLE
Проблема с греческими символами

### ISSUE THREAD

**Issue by EvilLordG** [GravitLauncher/Launcher#386]
Не запускается клиент если у тебя папка юзера названа на греческом
Launcher Agent
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.0.10-1 stable
2020.04.16 17:11:57 [INFO] Setting up script engine bindings
2020.04.16 17:11:58 [INFO] 25.181-b13
java.lang.IllegalArgumentException
    at sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
    at sun.instrument.InstrumentationImpl.appendToSystemClassLoaderSearch(Unknown Source)
    at pro.gravit.launcher.OneLINENnPDpng.addJVMClassPath(Unknown Source)
    at pro.gravit.launcher.ONelInEkqBBaPV.main(Unknown Source)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Exception in thread "main" 
Exit code -100
В дебаге была выведена вот эта ошибка...

**Comment by JoCat** [comment]
Вы ставили себе защиту на лаунчер (SimpleGuard)?

**Comment by gravit0** [comment]
Баг на стороне вашей JDK/JRE
Может помочь перенос лаунчера и папки обновлений в папку, не содержащую таких символов.
Может помочь обновление Java или установка другой версии(openjdk/oracle)
В 5.1.X этот метод вообще не вызывается и скорее всего баг не повторится
