### ISSUE TITLE
Команда unindexasset работает не правильно

### ISSUE THREAD

**Issue by ijo42** [GravitLauncher/Launcher#387]
При использовании команды `unindexasset` происходит разындексирование папки ассетов, с этой стороны все нормально, но когда приходит время использовать команду `indexasset` выдаёт ошибки
```
[INFO]  Creating indexed asset dir: 'asset1.12'
[ERROR] java.nio.file.FileAlreadyExistsException: /launchserver/updates/asset1.12
```
Из чего можно сделать вывод, что разындексированная папка не удаляется, хотя команда `indexasset` подразумевает это

**Comment by JoCat** [comment]
нет, сам ручками всё удаляй))

**Comment by ijo42** [comment]
Это не логично, indexasset во время своей работы создаёт папку `output-dir`, предлагаю либо проверять наличие папки, либо удалять папки во время работы команд

**Comment by JoCat** [comment]
Ну по сути проверка на наличие папки там имеется, она тебе и выкинула FileAlreadyExistsException

**Comment by gravit0** [comment]
Ничего не перезаписывается и не должно
