### ISSUE TITLE
Возможность задать default skin + добавить ссылку импорт для элитр.

### ISSUE THREAD

**Issue by Sepera-okeq** [GravitLauncher/Launcher#389]
### **1)** Добавить возможность импорта с сайта скинов для элитр. 
(функционал отдельных скинов для элитр возможен с 1.9)(т.е затронет владельцев сборок 1.12.2 и выше)

### **2)** Возможность задать ссылку на дефолтный скин/плащ/элитры,если скина по нику/плащу/элитры не было обнаружено. 

> про ассеты и редактирование там скина не хочу слышать,ибо это уже чересчур костыльно.

**Comment by gravit0** [comment]
Я не вижу скинов для элитр(дайте мне UUID настоящего mojang аккаунта где скины на элитры отдельно). Нет упоминаний об этой фитче на описании mojang api или где либо еще
Редактирование ассетов - good way, при отсутствии скина запрос на сервер не выполняется. В вашем же случае запрос скина будет всегда, даже у тех у кого он дефолт

**Comment by LoomeL** [comment]
Скинов для элитр нет, это плащ который на них натягивается
