### ISSUE TITLE
Не запускается клиент после скачивания файлов

### ISSUE THREAD

**Issue by nomfodm** [GravitLauncher/Launcher#390]
GravitLauncher (fork sashok724's Launcher) Client Launcher v5.1.4-1 stable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2020.05.13 11:36:18 [INFO] Reading EC keypair
2020.05.13 11:36:18 [INFO] 25.251-b08
2020.05.13 11:36:18 [INFO]  DirWatcher C:\Users\Сергей\AppData\Roaming\NiceServers\updates\asset1.8.9
2020.05.13 11:36:18 [INFO]  DirWatcher C:\Users\Сергей\AppData\Roaming\NiceServers\updates\MiniGames
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/forge.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/liteloader.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/minecraft.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/codecjorbis-20101023.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/codecwav-20101023.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/commons-codec-1.9.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/commons-compress-1.8.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/commons-io-2.4.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/commons-lang3-3.3.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/commons-logging-1.1.3.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/akka-actor_2.11-2.3.3.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/asm-all-5.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/config-1.2.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/launchwrapper-1.12-launcherfixed.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/lzma-0.0.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-actors-migration_2.11-1.1.0.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-compiler-2.11.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-continuations-library_2.11-1.0.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-continuations-plugin_2.11.1-1.0.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-library-2.11.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-parser-combinators_2.11-1.0.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-reflect-2.11.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-swing_2.11-1.0.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/scala-xml_2.11-1.0.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/trove4j-3.0.3.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/forge/vecmath-1.3.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/gson-2.2.4.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/guava-17.0.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/httpclient-4.3.3.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/httpcore-4.3.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/icu4j-core-mojang-51.2.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/jna-3.4.0.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/jopt-simple-4.6.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/jutils-1.0.0.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/libraryjavasound-20101123.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/librarylwjglopenal-20100824.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/log4j-api-2.0-beta9.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/log4j-core-2.0-beta9.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/lwjgl/jinput.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/lwjgl/lwjgl.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/lwjgl/lwjgl_util.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/netty-all-4.0.23.Final.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/oshi-core-1.1.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/platform-3.4.0.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/realms-1.7.39.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/soundsystem-20120107.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/AppData/Roaming/NiceServers/updates/MiniGames/libraries/twitch-6.5.jar
2020.05.13 11:36:18 [INFO] ClassLoader URL: file:/C:/Users/Сергей/Desktop/gravit/updates/Launcher.exe
2020-05-13 11:36:19,309 ERROR Error processing element Queue: CLASS_NOT_FOUND
2020-05-13 11:36:19,357 ERROR Unable to locate appender ServerGuiConsole for logger com.mojang
2020-05-13 11:36:19,358 ERROR Unable to locate appender ServerGuiConsole for logger 
2020-05-13 11:36:19,358 ERROR Unable to locate appender ServerGuiConsole for logger net.minecraft
[11:36:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:36:19] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:36:19] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[11:36:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
2020.05.13 11:36:19 [ERROR] java.lang.NoClassDefFoundError: com/mojang/authlib/exceptions/AuthenticationException
JVM exit code 0
2020.05.13 11:36:19 [INFO] WebSocket client disconnect
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Process exit code 0

**Comment by JoCat** [comment]
Вы как с палаты сбежали уважаемый?
[Вики читать пробовали?](https://launcher.gravit.pro/index.php?r=wiki%2Fpage&page=clientbuild)

**Comment by ijo42** [comment]
Это не ошибка лаунчера, а неправильная настройка, с такими вопросами просьба обращаться в Дискорд https://discord.gg/DJUzZgG
