### ISSUE TITLE
Скин

### ISSUE THREAD

**Issue by LarceRR** [GravitLauncher/Launcher#391]
Скины отображаются некорректно! 
Должно: 
![image](https://user-images.githubusercontent.com/65007305/82472655-310d0280-9ad1-11ea-9c95-702c9dda42f7.png)

Как есть:
![image](https://user-images.githubusercontent.com/65007305/82472526-fb681980-9ad0-11ea-874e-d343201d9f79.png)
P.s. Плащ отображается корректно

**Comment by ijo42** [comment]
контекст будет? версия майнкрафта, лаунчсервер, ядро

**Comment by ijo42** [comment]
C такими вопросами просьба обращаться в Дискорд https://discord.gg/DJUzZgG

**Comment by Zaxar163** [comment]
Это проблема клиента, но не лаунчера. Лаунчер только ссылку клиенту отдаёт (на скин).
