### ISSUE TITLE
Защита от переноса с ПК на ПК файла авторизации

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#405]
При включённой функции логирования железа, чтоб можно было включить проверку. Если авторизация происходит по заполненным данным, смотреть, есть ли этот компьютер уже в логах данного пользователя, если нет, то отменять авторизацию и сбрасывать файл. Попытку подобного входа выводить в лог или ещё куда, на лаунчсервере.

Так же добавлю, что комплектация в этом случае должна совпадать уже с имеющимися логами железа на 100%, с одной из строк. При сбросе авторизации выводить сообщение: "Ваша комплектация ПК была изменена, заново введите логин и пароль"
И важной частью этого, что железо при такой попытке, не должно залогироваться в базу на этот же аккаунт, на который была попытка входа с автозаполнения данных из файла.

Перенесено из дс. За 3 человека

**Comment by gravit0** [comment]
У этого предложения много проблем и неточностей
Для успешного прохождения проверки по железу лаунчер должен выполнить 3-4 запроса
1. Запросить информацию о security политике
2. Сделать запрос на получение verifyKey
3. Подписать verifyKey своим приватным ключём и отправить лаунчсерверу подпись и публичный ключ
4. Если лаунчсервер считает, что этого недостаточно, то в ответе указывает требования предоставить HWID
5. Если лаунчсервер не запросил Hwid процедура проверки считается завершенной. Если же нет - лаунчер собирает hwid и отправляет лаунчсерверу, после чего проверка считается завершенной
Теперь по проблемам:
- Лаунчер не использует токены для доступа(так как потребуется интеграция с CMS которых слишком много). В конфигурации config.json хранится реальный пароль(зашифрованный AES). Что считать файлом авторизации?
- Лаунчер НЕ собирает HWID если его не попросит лаунчсервер. Сбор HWID может занимать секунд 10-30, что много для постоянного использования. Архитектура проверки такова что **HWID собирается только при первом запуске**, а дальше он не нужен - вместо него используются ключи.
- Как вы собрались определять что файл авторизации был перенесен с другого ПК, если и там, и там настоящий пароль
Да, в принципе можно использовать токены. Но это скорее всего будет отдельным issue, так как там очень много нюансов и вопросов

**Comment by microwin7** [comment]
То что защита какая-то нужна, это точно. Обнако я не знал этих нюансов, самой большой проблемой выступает время сбора HWID. Способ реализации лишь мои догадки. Но, что если тогда проверку сделать какую-то на стороне клиента, сохранять файл в bscrypt с каким-то содержимым, которое генерируется из данных ПК, чтобы было индивидуально и шифруется ключом, который будет хранится на стороне лаунчсервера и отправляться в лаунчер, для создание нового bscrypt и последуещей сверки того что хранится в папке и то что только что создалось. По тому же  MAC, его собрать можно быстро как я знаю. Файл о котором я писал выше settings.bin

**Comment by gravit0** [comment]
BCrypt алгоритм хеширования(!) а не шифрования. MAC адрес сетевой карты штука КРАЙНЕ ненадёжная и не может считаться hwid
Вопрос в том для чего эта защита, какую проблему вы хотите решить

**Comment by microwin7** [comment]
Были такие взломы игроков, правда с 2012 по 2015 по большей части. А скинь мне плиз папку, ну а дальше вина игроков или наша, вот вопрос. Проблема старая и не нова. Однако все продвинутые программы защищаются от подобного копирования банального файла

**Comment by gravit0** [comment]
Такой способ защиты малораспространен
Браузеры - Firefox/Chrome хранят все свои данные в файлах. Профили можно бекапить простым копированием
Все Linux программы можно бекапить копированием требуемых файлов
Intelj IDEA все настройки так же хранит в файлах и их можно бекапить
Я не могу вспомнить программу, настройки которой нельзя было бы скопировать с ПК на ПК явным решением разработчиков, а не побочным эффектом от хранения настроек скажем в реестре винды. Даже при использовании реестра в 90% случаев информация в нем никак не шифруется и не привязывается к чему либо

HWID вещь **нестрогая** и, самое главное **несекретная**. Его получить может кто угодно и соответственно расшифровать пароль(если шифровать его с помощью HWID). Сбор HWID до авторизации приведет нас к тому же что было в 5.0.X - авторизация по 10 секунд из за сбора HWID

**Comment by microwin7** [comment]
В таком случае выходит что игра не стоит свеч? Либо может попробовать куда-то сохранять в другое место этот файл, чтоб игроки уже явно понимали, что хотят получить у их какие-то системные файлы, это уже как последний из вариантов

**Comment by gravit0** [comment]
Вне стандартной папки? Ну как минимум это неэтично, прописывать себя куда либо кроме отведённого места
Если уж прямо хочется сказать пользователю "НЕ ЛЕЗЬ" ну напишите вы модуль, который создаст текстовый документ рядом с settings.json
