### ISSUE TITLE
Команда clients некорректно отображает ip за reverse-proxy

### ISSUE THREAD

**Issue by Sirse** [GravitLauncher/Launcher#411]
При работе в dev окружении в логе отображается корректный ip игрока, однако, clients всё равно отображает 127.0.0.1

**Comment by microwin7** [comment]
clients
2020.09.06 00:58:44 [INFO] Command 'clients'
2020.09.06 00:58:44 [INFO] Client name dev2 | ip 127.0.0.1 | connectUUID 9897330c-0665-4b29-8126-a8f7fcfd3e79
2020.09.06 00:58:44 [INFO]  Data: checkSign true | auth_id std
2020.09.06 00:58:44 [INFO]  Permissions: permissions 0 | flags 0 (permissions 0 | flags 0)

**Comment by Sirse** [comment]
X-Real-IP корректно передается? Используется dev версия (в master ветке баг не исправлен)?
