### ISSUE TITLE
Проблема с кодировкой в форме пароля при авторизации

### ISSUE THREAD

**Issue by alowave223** [GravitLauncher/Launcher#412]
Подробнее о проблеме, это работает не в зависимости от локали системы, у меня стоит Ubuntu 20.04 с русской локалью UTF-8, на стороне сайта (будет показан пример на типе авторизации request) тоже все хорошо. Но вот беда, если юзер зарегается хоть с 1 буквой русского языка лаунчер его не пустит, потому что вместо русских букв в запрос приходит знак вопроса в ромбике, проверять мы будем простым способом через echo в скрипте авторизации.

### Скриншот того что авторизация проходит успешно напрямую
![image](https://user-images.githubusercontent.com/49539029/91130298-18098400-e6b4-11ea-86ae-4bf3d3d5130a.png)

Итак, у нас есть уже зарегистрированный юзер с паролем состоящим из **русских** символов, и он вполне рабочий.

Заходим в лаунчер, логинимся и видим что пароль неправильный, хотя вводили все верно.

![image](https://user-images.githubusercontent.com/49539029/91130527-733b7680-e6b4-11ea-9cd9-f81dd05b9828.png)

### Теперь логинимся уже с echo

![image](https://user-images.githubusercontent.com/49539029/91130623-982fe980-e6b4-11ea-8359-400cefa78aca.png)

Как видно на скриншоте, получаем мы забавные знаки вопроса в ромбиках вместо нашего пароля. Есть решение данной проблемы?

**Comment by TUFounder** [comment]
Ставить проверку на ру символы

**Comment by gravit0** [comment]
Скрипт:
```
<?php
echo $_GET['password'];
```
Запрос: `test.php?username=%login%&password=%password%&ip=%ip%`
Кодировка скрипта - UTF-8
Локаль и на сервере и на лаунчере - UTF-8(обе системы Linux)
Русские символы корректно отображаются

**Comment by Lewui** [comment]
Забыл указать версию лаунчера, 5.1.7-1 stable. И это может быть из-за ОС? Я тестировал на Windows Pro многоязычной, локаль по умолчанию русский.

**Comment by Lewui** [comment]
Дa, как и ожидалось это из-за системы, установил линукс (убунту 20.04) все отлично передается, даже без русской локали

**Comment by Lewui** [comment]
Что по итогу делать юзерам на виндоус?

**Comment by TUFounder** [comment]
Не использовать win или ставить проверки...

**Comment by JoCat** [comment]
> Что делать

Не использовать русские символы в паролях логично же 🤣
