### ISSUE TITLE
Не появляется файл eula.txt после создания самого сервера в Gravitlauncher

### ISSUE THREAD

**Issue by MizereSozora** [GravitLauncher/Launcher#416]
Я всё делал как обычно:скачал сам лаунчер, настроил его, потом перешел к серверу, создал до него папку, закинул serverwrapper и public.key... потом пробовал кидать несколько ядер(SpongeForge,Kcauldron). На всякий случай попробовал кинуть ядро Spigot. Сервер на версии 1.7.10. Когда попробовал запустить на ядре Spigot у меня сразу вылетел start.bat, а когда попробовал другие, он показал много строчек с кодом и закрылся(ну так и должно было быть), но файл eula.txt никак не хотел появляться, а без него зайти не получается, то есть сервер создан, но зайти на него невозможно.

**Comment by microwin7** [comment]
1. `вылетел start.bat` - мы не ванги, чтоб знать, что у вас там написало
2. Если вы не можете запустить сервер без привязки к лаунчеру и требуете с нас eula.txt, то вы не туда обратились.
3. Spigot на 1.7.10 запускать? Вы серьёзно?
4. Читайне нормально wiki на сайте или обратитесь за помощью в дискорд сервер Гравита https://discord.gg/nja8Vss

**Comment by gravit0** [comment]
Добавьте pause в ваш start.bat и обратитесь в discord сервер с логами. Issue используется только для багов и предложений по **лаунчеру**
