### ISSUE TITLE
Не работают опциональные моды!

### ISSUE THREAD

**Issue by ucnovegnik** [GravitLauncher/Launcher#419]
Опциональные моды в меню лаунчера отображаются, все хорошо, но при запуске не убираются!
Помогите пожалуйста.

  "updateOptional": [
    {
       "type": "FILE",
       "list": ["mods/1.7.10/tabby.jar"],
       "info": "Мод на чат",
       "visible": true,
       "mark": true,
       "permissions": 0,
       "name": "TabbyChat"
    }
  ],

**Comment by microwin7** [comment]
Проверьте индексы профилей, они не должны повторяться

**Comment by ucnovegnik** [comment]
У меня один сервер

**Comment by LoomeL** [comment]
saveprofile команда

**Comment by ucnovegnik** [comment]
Они в лаунчере есть, но при отключении их, клиент все равно с ними запускается

**Comment by gravit0** [comment]
На вики инструкции к опциональным модам для 5.1.7
Для конвертации профиля в новый формат, используемый 5.1.8 используйте saveprofiles
Об этом написано в release notes 5.1.8
