### ISSUE TITLE
Ошибка при сборке

### ISSUE THREAD

**Issue by coldfeudal** [GravitLauncher/Launcher#426]
При сборке лаунчера через setup.sh (точно по инструкции, несколько раз перепроверено) появляется следующая ошибка: https://pastebin.com/Mneu42tx

**Comment by microwin7** [comment]
![Screenshot_20201216_191451](https://user-images.githubusercontent.com/12544425/102375008-0b969780-3fd3-11eb-9488-3c7cff97cb73.jpg)

**Comment by coldfeudal** [comment]
Где меняется? В shell скрипте подобного не нашел. Вручную ставить бы не хотелось

**Comment by mogafk** [comment]
Вобщем здесь https://oss.sonatype.org/content/repositories/snapshots/pro/gravit/launcher/launcher-client-api/
нет 5.1.8-SHAPSHOT и ошибка выглядит вполне нормальной

Почему бы не поправить предположительно тут https://github.com/GravitLauncher/LauncherRuntime версию снапшота?

(сорян я вобще не шарю в вашей джавистской теме)

**Comment by mogafk** [comment]
Вобщем предположительно делаем следующее.
1) Запускаем setup-master
2) он создает две директории src и srcRuntime
и кидает ошибку вида
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find pro.gravit.launcher:launcher-core:5.1.8-SNAPSHOT.
   ....
   
   > Could not find pro.gravit.launcher:launcher-ws-api:5.1.8-SNAPSHOT.
     Searched in the following locations:
     ...
   > Could not find pro.gravit.launcher:launcher-client-api:5.1.8-SNAPSHOT.
     Searched in the following locations:
     ...
```
3) Открывает setup-master.sh и комментим строки
```
git clone -b $COMMIT_LAUNCHER  https://github.com/GravitLauncher/Launcher.git src;
git clone -b $COMMIT_RUNTIME https://github.com/GravitLauncher/LauncherRuntime.git srcRuntime;
```
4) Открываем src/build.gradle меняем version = '5.1.8' на version = '5.1.9'
5) Открываем srcRuntime/build.gradle и меняем 5.1.8 на 5.1.9
```
    implementation "pro.gravit.launcher:launcher-core:5.1.8-SNAPSHOT"
    implementation "pro.gravit.launcher:launcher-ws-api:5.1.8-SNAPSHOT"
    implementation "pro.gravit.launcher:launcher-client-api:5.1.8-SNAPSHOT"
```
6) Запускаем setup-master.sh

**Comment by gravit0** [comment]
Неактуально после релиза 5.1.9
