### ISSUE TITLE
Проблема со скинами

### ISSUE THREAD

**Issue by sanik** [GravitLauncher/Launcher#427]
Первый запуск лаунчера после рестарта LauncheServer все хорошо а уже при повторе запуска именно Launcher выкидывает ошибку и скин не грузит
https://pastebin.com/0cWweDs5

**Comment by gravit0** [comment]
Эта ошибка означает, что сервер вернул код, отличный от 200 и 404, либо вернул не картинку. Это не ошибка лаунчсервера, проверяйте конфигурацию и логи сервера, с которого берете скины

**Comment by sanik** [comment]
Странность в том что после рестарта лаунчсервера первый заход все ок. А второй опять ошибка. Очень я сомниваюсь что скин точно со второго раза недоступен

**Comment by microwin7** [comment]
Подтверждаю, есть проблема и у меня, но ошибку отловить не могу, в лаунчсервере всё чисто, если дебаг пытаюсь лаунчера сделать, то ошибки как не бывало, голова на сцену прогружается тогда нормально
