### ISSUE TITLE
Не видит javafx

### ISSUE THREAD

**Issue by IlliaKisil** [GravitLauncher/Launcher#428]
Здравствуйте, помогите, когда делаю build, всегда выдаёт что мол javafx не установлен(скрин https://imgur.com/q1Fw0OP), хотя он установлен и корректно работает на примере HelloFX.java

**Comment by gravit0** [comment]
В папке с вашей jdk в папке jmods отсутствуют jmod'ы javafx. Их можно скачать с официального сайта openjfx
