### ISSUE TITLE
Переход на Vue 3

### ISSUE THREAD

**Issue by egorsgn3** [GravitLauncher/Launcher#429]
На данный момент у SimpleCabinet'a используется Vue 2. Поскольку Vue 2 уже довольно таки старенькая, я хочу предложить перейти на Vue 3, так как Vue 3 более оптимизирована и в нём присутствует Composition API.

**Comment by gravit0** [comment]
Я следила за прогрессом с начала разработки кабинета. bootstrap-vue пока что не совместим с Vue 3, отслеживать состояние можно тут:
https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

**Comment by gravit0** [comment]
Issue по фронтенду SImpleCabinet нужно создавать в репозитории https://github.com/SimpleCabinet/SimpleCabinetFrontend
