### ISSUE TITLE
Спам ошибкой при включении автовхода в лаунчере, а затем краш игры

### ISSUE THREAD

**Issue by TrolPro** [GravitLauncher/Launcher#431]
[crash-2021-01-16_02.22.22-client.txt](https://github.com/GravitLauncher/Launcher/files/5823365/crash-2021-01-16_02.22.22-client.txt)
Help pls

**Comment by Zaxar163** [comment]
Не относится к лаунчеру.
Если кому интересно, ошибка: java.lang.NullPointerException: Tesselating block in world
