### ISSUE TITLE
[ERROR] java.lang.IllegalArgumentException: Invalid username:

### ISSUE THREAD

**Issue by TrolPro** [GravitLauncher/Launcher#432]
Ошибка вылезает в лаунчсервере, при входе на сервер с любого ника (Не важно латиница это или просто арабские цифорки)
![image](https://user-images.githubusercontent.com/77401755/104788098-5a864700-57a2-11eb-9007-378fea3c83e9.png)
Тут использовалось 2 разных ника
- TrolPro
- 123

**Comment by gravit0** [comment]
Эту ошибку вызывает один из плагинов или модов. 
В memory auth handler UUID специального формата и при запросе другого UUID плагином или модом вы получите оштбку. 
Используйте хранение в БД вместо memory.
