### ISSUE TITLE
MacOS Java

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#435]
Исправить поиск java на MacOS
Разные попытки установить в настройках лаунчсервера максимальную джаву для лаунчера, не привели к результатам. Так же параметр setMaxVersion не помог. Установлена 14 HotSpot и после 8 281. Так же говорят что имеются проблемы с запуском даже на 11 джаве, хоть в настройках допустимо и выше, но требует только 8

**Comment by gravit0** [comment]
Параметр setMaxVersion работает только для .exe . Поиск подходящей java работает только на Windows
Для Linux и MacOS используется та джава, с которой запускает .jar пользователь
