### ISSUE TITLE
Не запускается билд

### ISSUE THREAD

**Issue by playgamesgo** [GravitLauncher/Launcher#436]
Когда запускаю .exe или .jar лаунчера , он не запускается

Я запустил лаунчер в режиме дебага и вот что мне выводит:
java -Xmx256M -Dlauncher.debug=true -javaagent:launcher.jar  -jar launcher.jar
Launcher Agent
GravitLauncher (fork sashok724's Launcher) Launcher v5.1.4-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
2021.03.03 18:20:34 [DEBUG] Testing stacktrace
2021.03.03 18:20:34 [DEBUG] Verifying class loader
2021.03.03 18:20:34 [DEBUG] Verifying JVM architecture
2021.03.03 18:20:34 [ERROR] java.lang.SecurityException: Class pro.gravit.launcher.ziBercrAftFTum not signed
2021.03.03 18:20:34 [INFO] Launcher for project ZiberCraft
2021.03.03 18:20:34 [INFO] If need debug output use -Dlauncher.debug=true
2021.03.03 18:20:34 [INFO] If need stacktrace output use -Dlauncher.stacktrace=true
2021.03.03 18:20:34 [INFO] Restart Launcher with JavaAgent...
2021.03.03 18:20:34 [DEBUG] Found Java 9+ ( 14.0.2 )
2021.03.03 18:20:34 [DEBUG] Commandline: [C:\Program Files\Java\jdk-14.0.2\bin\java.exe, -Dlauncher.debug=true, -Dlauncher.stacktrace=false, -Dlauncher.dev=false, -Djdk.attach.allowAttachSelf, -XX:+DisableAttachMechanism, -Xmx256M, -cp, C:\Users\pplay\OneDrive\Робочий ст?л\l\updates\Launcher.jar, pro.gravit.launcher.zIBERCraFT9X3D]
2021.03.03 18:20:34 [DEBUG] Testing stacktrace
2021.03.03 18:20:34 [DEBUG] Verifying class loader
2021.03.03 18:20:34 [DEBUG] Verifying JVM architecture
GravitLauncher (fork sashok724's Launcher) Launcher v5.1.4-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
Exception in thread "main" java.lang.SecurityException: Class pro.gravit.launcher.zIBERCraFT9X3D not signed
        at pro.gravit.launcher.zIBERCraFT9X3D.ZibERCRaftoAyT(Unknown Source)
        at pro.gravit.launcher.zIBERCraFT9X3D.main(Unknown Source)

**Comment by gravit0** [comment]
См #417

**Comment by old21** [comment]
Нужно подписать лаунчер. Для этого нужно установить модуль Generate certeficate module. Далее перезапускаете ваш ЛаунчСервер и прописываете команду  **generatecertificate** после некоторого времяни в консоли у вас появиться конфиг. Этот конфиг вы должны заменить в LaunchServer.json. Полная инструкция: https://github.com/GravitLauncher/LauncherModules/blob/master/GenerateCertificate_module/README.md

**Comment by playgamesgo** [comment]
а куда вставлять конфигурацию 

конфигурация сертификатов {
  "enabled": true,
  "keyStore": "C:\\Users\\pplay\\OneDrive\\Робочий ст?л\\launcher\\launcherCodeSign.p12",
  "keyStoreType": "PKCS12",
  "keyStorePass": "e4cbd941305c798af40571668e15459e",
  "keyAlias": "launchercodesign",
  "keyPass": "e4cbd941305c798af40571668e15459e",
  "metaInfKeyName": "SIGNUMO.RSA",
  "metaInfSfName": "SIGNUMO.SF",
  "signAlgo": "SHA256WITHRSA"
}

лаунч сервер конфиг {
  "projectName": "launcher",
  "mirrors": [
    "https://mirror.gravit.pro/"
  ],
  "binaryName": "Launcher",
  "copyBinaries": true,
  "env": "STD",
  "auth": {
    "std": {
      "isDefault": true,
      "provider": {
        "whitelist": [],
        "type": "accept"
      },
      "handler": {
        "type": "memory"
      },
      "textureProvider": {
        "skinURL": "http://example.com/skins/%username%.png",
        "cloakURL": "http://example.com/cloaks/%username%.png",
        "type": "request"
      },
      "displayName": "Default"
    }
  },
  "protectHandler": {
    "profileWhitelist": {},
    "allowUpdates": [],
    "type": "std"
  },
  "components": {
    "regLimiter": {
      "message": "Превышен лимит регистраций",
      "excludeIps": [],
      "exclude": [],
      "rateLimit": 3,
      "rateLimitMillis": 36000000,
      "type": "regLimiter"
    },
    "authLimiter": {
      "message": "Превышен лимит авторизаций",
      "exclude": [],
      "rateLimit": 3,
      "rateLimitMillis": 8000,
      "type": "authLimiter"
    }
  },
  "launch4j": {
    "enabled": true,
    "setMaxVersion": false,
    "maxVersion": "1.8.999",
    "minVersion": "1.8.0",
    "downloadUrl": "http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html",
    "productName": "GravitLauncher",
    "productVer": "5.1.5.5",
    "fileDesc": "GravitLauncher 5.1.5",
    "fileVer": "5.1.5.5",
    "internalName": "Launcher",
    "copyright": "© GravitLauncher Team",
    "trademarks": "This product is licensed under GPLv3",
    "txtFileVersion": "%s, build %d",
    "txtProductVersion": "%s, build %d"
  },
  "netty": {
    "fileServerEnabled": true,
    "sendExceptionEnabled": true,
    "ipForwarding": false,
    "showHiddenFiles": false,
    "launcherURL": "http://212.109.196.196:9274/Launcher.jar",
    "downloadURL": "http://212.109.196.196:9274/%dirname%/",
    "launcherEXEURL": "http://212.109.196.196:9274/Launcher.exe",
    "address": "ws://212.109.196.196:9274/api",
    "bindings": {},
    "performance": {
      "usingEpoll": false,
      "bossThread": 2,
      "workerThread": 8
    },
    "binds": [
      {
        "address": "0.0.0.0",
        "port": 9274
      }
    ],
    "logLevel": "DEBUG"
  },
  "launcher": {
    "guardType": "no",
    "attachLibraryBeforeProGuard": false,
    "compress": true,
    "warningMissArchJava": true,
    "enabledProGuard": true,
    "stripLineNumbers": true,
    "deleteTempFiles": true,
    "proguardGenMappings": true
  },
  "certificate": {
    "enabled": false
  },
  "sign": {
    "enabled": false,
    "keyStore": "pathToKey",
    "keyStoreType": "JKS",
    "keyStorePass": "mypass",
    "keyAlias": "myname",
    "keyPass": "mypass",
    "metaInfKeyName": "SIGNUMO.RSA",
    "metaInfSfName": "SIGNUMO.SF",
    "signAlgo": "SHA256WITHRSA"
  },
  "startScript": ".\\start.bat"

}
