### ISSUE TITLE
Проблема с читами

### ISSUE THREAD

**Issue by Futsunomitama** [GravitLauncher/Launcher#437]
Запустил сервер, быстро обнаружил что так называемые читы с инжектом проходят сквозь защиту, накатил GravitGuard - не помогло. Есть ли другие варианты решения проблемы?

**Comment by old21** [comment]
Написать свою защиту.)

**Comment by playgamesgo** [comment]
> Запустил сервер, быстро обнаружил что так называемые читы с инжектом проходят сквозь защиту, накатил GravitGuard - не помогло. Есть ли другие варианты решения проблемы?

online-mod ровно true или нет?

**Comment by Zaxar163** [comment]
Issue жива? Если нет закрою, так как вопрос и никакой конкретики.

**Comment by JoCat** [comment]
> Issue жива? Если нет закрою, так как вопрос и никакой конкретики.

Закрывай XD
