### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by GeneralViski** [GravitLauncher/Launcher#439]
2021.04.11 20:10:42 [ERROR] java.lang.IllegalArgumentException: Can't find commo                                  n super class of [pro/gravit/repackage/io/netty/channel/group/DefaultChannelGrou                                  pFuture] (with 3 known super classes) and [pro/gravit/repackage/io/netty/channel                                  /group/VoidChannelGroupFuture] (with 1 known super classes)
Все версии лаунчера пробывал, не одна не работает по итогу и ошибки вся связанные с джавой

**Comment by GeneralViski** [comment]
Сделал 1 в 1 все по инструкции и теперь вот

  Class       = [pro/gravit/launcher/MinecrafT67I0P]
  Method      = [MINecrafT8fObR(Ljava/util/function/Consumer;Ljavafx/scene/layou                   t/Pane;ZLjavafx/scene/layout/Pane;Ljavafx/scene/Scene;Ljava/lang/String;Ljava/ut                   il/function/BiConsumer;)V]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super cl                   ass of [javafx/stage/Screen] (with 1 known super classes) and [pro/gravit/launch                   er/minecraft0hbNf] (with 1 known super classes))
Unexpected error while preverifying:
  Class       = [pro/gravit/launcher/MinecrafT67I0P]
  Method      = [MINecrafT8fObR(Ljava/util/function/Consumer;Ljavafx/scene/layou                   t/Pane;ZLjavafx/scene/layout/Pane;Ljavafx/scene/Scene;Ljava/lang/String;Ljava/ut                   il/function/BiConsumer;)V]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super cl                   ass of [javafx/stage/Screen] (with 1 known super classes) and [pro/gravit/launch                   er/minecraft0hbNf] (with 1 known super classes))
2021.04.11 20:30:45 [ERROR] java.lang.IllegalArgumentException: Can't find commo                   n super class of [javafx/stage/Screen] (with 1 known super classes) and [pro/gra                   vit/launcher/minecraft0hbNf] (with 1 known super classes)
build

**Comment by microwin7** [comment]
И где же JavaFX?

**Comment by GeneralViski** [comment]
Теперь другая проблема, после билда EXE файл на секунду появляется и изчезает :/

**Comment by GeneralViski** [comment]
2021.04.11 23:38:38 [INFO]  Compiling resources
2021.04.11 23:38:38 [INFO]  Linking
2021.04.11 23:38:38 [INFO]  Wrapping
2021.04.11 23:38:38 [INFO]  Successfully created /home/generalviski/launcher-modules/build/Launcher-launch4j-0.exe
2021.04.11 23:38:38 [INFO]  Task launch4j processed from 84 millis
2021.04.11 23:38:38 [INFO] Build successful from 85 millis
2021.04.11 23:38:38 [INFO] Syncing launcher binaries
2021.04.11 23:38:38 [INFO] Syncing launcher binary file
2021.04.11 23:38:38 [INFO] Syncing launcher EXE binary file
Хотя вот ошибок нету

**Comment by GeneralViski** [comment]
И остается ток Launcher Clear

**Comment by egorsgn3** [comment]
Ты дурак? Ты компилируешь не так. У всех остальных все отлично компилируется.

**Comment by gravit0** [comment]
Готовые файлы jar/exe находятся в updates
Папка build будет удалена в 5.2.0 что бы не путались
