### ISSUE TITLE
1.16 join server error

### ISSUE THREAD

**Issue by demon1076** [GravitLauncher/Launcher#446]
Я поставил authlib 2, Launcherauthlib. Настроил Serverwrapper по гайду https://launcher.gravit.pro/serverbuild для 1.16.4+, но при входе на сервер выдаёт ошибку lost connection: Internal Exception: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils. Не могу понять, что не так, и в гугле нет инфы никакой про это..

**Comment by egorsgn** [comment]
Дак ты блять бубун? У тебя либы нету и классов ее.

**Comment by demon1076** [comment]
> 
> 
> Дак ты блять бубун? У тебя либы нету и классов ее.

какой именно? всё сделал по гайду на вики, но всё равно траблы.

**Comment by dimadencep** [comment]
Ты слепой? Глаза разуй дед java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
Это значит что класса org/apache/commons/lang3/StringUtils нет представляешь?
Я хз куда ты его заснул или съел,
Но руки у тебя явно не прямые, и твои оговорочки "Настроил Serverwrapper по гайду" тут не работают

**Comment by BlindWizard** [comment]
Оставлю коммент для тех, кто, как и я, напорется на этот прикол))
В документации написано следующее: "Докиньте файлы библиотеки apache lang3 в classpath или ServerWrapper.jar, удалив перед этим стандартную authlib из minecraft.jar" - в разделе Spigot/Paper. Для нубов типо меня непонятно, что делать.

В случае, если вы пользуетесь этим ядром, вам нужно пропатчить ваш ServerWrapper.jar.
Для этого качаем исходную либу по ссылке https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
Открываем commons-lang3-3.12.0.jar и переносим оттуда все файлы в ServerWrapper.jar. Перезапускаем сервер и все работает.
