### ISSUE TITLE
Ошибка авторизации dev версия

### ISSUE THREAD

**Issue by Anhelm** [GravitLauncher/Launcher#447]
1. GravitLauncher 5.2.0 (dev)
2. Конфигурация LaunchServer.json без digest выдает следующий ответ при попытки авторизироваться:
https://pastebin.com/9EbgCqVn
3.  Конфигурация LaunchServer.json с digest выдает следующий ответ при попытки авторизироваться:
https://pastebin.com/uapsKg8m

[launchServer_с_digest.txt](https://github.com/GravitLauncher/Launcher/files/6645362/launchServer_._digest.txt)
[LaunchServer_без_digest.txt](https://github.com/GravitLauncher/Launcher/files/6645358/LaunchServer_._digest.txt)

**Comment by gravit0** [comment]
Исправили. Должно помочь
