### ISSUE TITLE
Перевод конфигов на json

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#45]
Требуется, чтоб сделать удобнее жизнь ибо формат json везде, а конфиги сашка - custom.

**Comment by Zaxar163** [comment]
Стало требоваться websocket`ами....

**Comment by Zaxar163** [comment]
Ишуя не забыта.

**Comment by gravit0** [comment]
В работе

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/49b085278cf0ce034e8367ca76b50316aca7cb7d
https://github.com/GravitLauncher/Launcher/commit/7c35cb0a34f0c3281baa3933a1fefd4160ba4860
https://github.com/GravitLauncher/Launcher/commit/79891d711e77232b1b9bb9119ca7c99b43dd6792
https://github.com/GravitLauncher/Launcher/commit/123250246c06b8aee41411574beba04f9949d0ef
https://github.com/GravitLauncher/Launcher/commit/2c06cdec24eae8f895c29e77d42c4ec93809d7e0
https://github.com/GravitLauncher/Launcher/commit/137b83f428d8081c13e40f54bf05c156328fa0f3
https://github.com/GravitLauncher/Launcher/commit/28cb9b0f23538f726469c0ff059147c8ddffa54f
https://github.com/GravitLauncher/Launcher/commit/08d7f61a19df8a144ab4acb4584ff33ae719a12e
https://github.com/GravitLauncher/Launcher/commit/c65124a21e5ed0d2676b0cfa764214749b75c86d
https://github.com/GravitLauncher/Launcher/commit/f58d387d9255b55259c18bc61f432477294558b1
