### ISSUE TITLE
Нет скина на черепе

### ISSUE THREAD

**Issue by alowave223** [GravitLauncher/Launcher#450]
Проблема/Баг заключается в том, что черепа игроков отображаются без их скинов, было бы все равно, если бы на версиях 1.15.2 и 1.16.5 (Возможно и на других, конкретно на этих проверял) из-за этого клиент не зависал на добрую секунду. Сервер в онлайн моде, у всех скины отображаются, все хорошо, версия лаунчера 5.2.0 но скины на черепах не отображаются и на прошлых версиях. Проверял в ванили, такая проблема присутствует если выдать себе череп несуществующего игрока, так же виснет на секунду, если наоборот - всё плавно и прекрасно.

**Comment by gravit0** [comment]
Пришлите более подробное описание
- Как настроено получение скинов(куда указывает URL) и есть ли там Cloudflare
- Логи с лаунчсервера
- Логи с сервера с включенным режимом DEV
- Логи с клиента с включенным режимом DEV
Еще желательно видео где было бы видно логи в реальном времени, что бы было видно на каком моменте идет зависание

**Comment by dimadencep** [comment]
Проблема блять вообще вспомнили про абсолютно никому нахуй не нужные черепа и все, трагедия, как жить.

**Comment by alowave223** [comment]
1. Получение скинов настроено было разными способами, с SSL от клауда, на обычный файл, сейчас в видео я показываю с файловым сервером на node js который находится по прямой ссылке http://ip:port/files без каких либо клаудов и прочего, скин отображается.
2. Все остальное в личные сообщения дискорда, мой дискорд: al?wav?#8709

**Comment by gravit0** [comment]
Проблема решена(в ЛС). Получение скинов без использования лаунчера имеет аналогичную проблему
В лаунчер добавлена возможность уменьшить влияние задержек при получении скинов для предотвращения подобных проблем
