### ISSUE TITLE
Шифрование рантайма.

### ISSUE THREAD

**Issue by SakuMai** [GravitLauncher/Launcher#451]
Модуль поставлен и все включено, вот такая красота появляется. В дебаге: 2021.07.15 20:07:05 [DEBUG] Pushed aone\scenes\settings\settings.css
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\servers\example.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\sv 1.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\dialogs\dialogs.css
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\background.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\background3.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\scenes\settings\settings.fxml
2021.07.15 20:07:05 [DEBUG] Pushed aone\scenes\login\logintotp.fxml
2021.07.15 20:07:05 [DEBUG] Pushed aone\components\components.css
2021.07.15 20:07:05 [DEBUG] Pushed aone\dialogs\info\dialog.fxml
2021.07.15 20:07:05 [DEBUG] Pushed aone\styles\global.css
2021.07.15 20:07:05 [DEBUG] Pushed aone\runtime_ru.properties
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\icons\checkbox1_off.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\scenes\update\update.fxml
2021.07.15 20:07:05 [DEBUG] Pushed aone\scenes\options\options.css
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\field.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\pbqps.png
2021.07.15 20:07:05 [DEBUG] Pushed aone\images\icons\checkbox_on.png
Jul 15, 2021 8:07:06 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not find stylesheet: enfs:login.css
Jul 15, 2021 8:07:07 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not find stylesheet: enfs:../../styles/global.css
Jul 15, 2021 8:07:07 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not find stylesheet: enfs:../../styles/variables.css
2021.07.15 20:07:07 [DEBUG] Scene login disabled (1)
Jul 15, 2021 8:07:07 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not find stylesheet: enfs:processing.css
2021.07.15 20:07:08 [INFO] Selected auth: std | method class pro.gravit.launcher.TipycrAFTpOnw2
2021.07.15 20:07:08 [INFO] Added std: Default
2021.07.15 20:07:09 [DEBUG] Scene login enabled (0)

Шо делать? Альфа 5.2.0 (Писать про не стабильность - идите к чОрту)

![image](https://user-images.githubusercontent.com/66568909/125828830-fcab8493-901d-409f-a686-9c19913e5bf6.png)

**Comment by Zaxar163** [comment]
Вы используете ветку dev. Вероятно вы сильно отстали от upstream. На 7ad308c работоспособность проверена. Всё работает. Обновляйтесь.

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/LauncherRuntime/commit/a6e7c96842dd9ef156f6448cb9f74b03740d442f
Исправлено
