### ISSUE TITLE
лаунчер выдаёт такую ошыбку

### ISSUE THREAD

**Issue by anymelovgames** [GravitLauncher/Launcher#452]
![image png 154212b29aae7e5c771db6396fd8dcc7 (1)](https://user-images.githubusercontent.com/72560856/126384346-5b2aeaed-1db2-44ff-a71c-a984f73f6f84.png)
#ошыбка

**Comment by dimadencep** [comment]
![monah_31340477_orig_-1](https://user-images.githubusercontent.com/66722732/126387658-d7e2d406-80cc-490a-9e0d-1bf6f7d5e94e.png)

**Comment by SashaGoncharov19** [comment]
![sc2jjgyqgui](https://user-images.githubusercontent.com/65261114/126388044-e80659ae-90d0-4a84-895a-ccbefe5fa5eb.jpg)

**Comment by dayd21git** [comment]
> ![image png 154212b29aae7e5c771db6396fd8dcc7 (1)](https://user-images.githubusercontent.com/72560856/126384346-5b2aeaed-1db2-44ff-a71c-a984f73f6f84.png)
> #ошыбка

Вероятно у тебя на стороне лаунчсервера либо закрыты порты, либо неправильно указан ip в LaunchServer.json.
Убедись, что это не localhost, а в binds указан стандартный адрес 0.0.0.0. Его трогать не нужно. Ты работаешь на vds?

**Comment by anymelovgames** [comment]
compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Exception in thread "main"

**Comment by dayd21git** [comment]
> compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
> at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
> at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
> Exception in thread "main"

Какая версия java? В терминале `java -version` пропиши.

**Comment by anymelovgames** [comment]
> > скомпилированная более поздней версией среды выполнения Java (версия файла классов 55.0), эта версия среды выполнения Java распознает только версии файлов классов до 52.0 
> > в java.lang.ClassLoader.defineClass1 (собственный метод) 
> > в java.lang.ClassLoader. defineClass (ClassLoader.java:756) 
> > в java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142) 
> > в java.net.URLClassLoader.defineClass (URLClassLoader.java:468) 
> > в java.net.URLCaclassLoader (URLClassLoader.java:468) в java.net.URLCaclassLoader (URLClassLassLassLoader. java: 74) 
> > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:369) 
> > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:363) 
> > в java.security.AccessController.doPrivileged (собственный метод) 
> > в java .net.URLClassLoader.findClass (URLClassLoader.java:362)
> > в java.lang.ClassLoader.loadClass (ClassLoader.java:418) 
> > в sun.misc.Launcher $ AppClassLoader.loadClass (Launcher.java:352) 
> > в java.lang.ClassLoader.loadClass (ClassLoader.java:351) 
> > на солнце. instrument.InstrumentationImpl.loadClassAndStartAgent (InstrumentationImpl.java:304) 
> > в sun.instrument.InstrumentationImpl.loadClassAndCallPremain (InstrumentationImpl.java:401) 
> > Исключение в потоке «main»
> 
> Какая версия java? В терминале `java -version`пропиши.

$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**Comment by anymelovgames** [comment]
> > скомпилированная более поздней версией среды выполнения Java (версия файла классов 55.0), эта версия среды выполнения Java распознает только версии файлов до 52.0 
> > в java.lang.ClassLoader.defineClass1 (собственный метод) 
> > в java.lang.ClassLoader. defineClass (ClassLoader.java:756) 
> > в java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142) 
> > в java.net.URLClassLoader.defineClass (URLClassLoader.java:468) 
> > в java.net.URLCaclassLoader (URLClassLoader.java:468 ) в java.net.URLCaclassLoader (URLClassLassLassLoader. java: 74) 
> > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:369) 
> > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:363)
> > в java.security.AccessController.doPrivileged (собственный метод) 
> > в java .net.URLClassLoader.findClass (URLClassLoader.java:362) 
> > в java.lang.ClassLoader.loadClass (ClassLoader.java:418) 
> > в sun.misc.Launcher $ AppClass .loadClass (Launcher.java:352) 
> > в java.lang.ClassLoader.loadClass (ClassLoader.java:351) 
> > на солнце. instrument.InstrumentationImpl.loadClassAndStartAgent (InstrumentationImpl.java:304) 
> > в sun.instrument.InstrumentationImpl.loadClassAndCallPremain (InstrumentationImpl.java:401) 
> > Исключение в потоке «main»
> 
> Какая версия java? В терминале `java -version`пропиши.

c системои виндовс

**Comment by anymelovgames** [comment]
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
 
--
юлик терентий
 
  
>Среда, 21 июля 2021, 14:33 +03:00 от day-d ***@***.***>:
> 
> 
>compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>at java.lang.ClassLoader.defineClass1(Native Method)
>at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
>at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
>at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
>at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
>at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
>at java.security.AccessController.doPrivileged(Native Method)
>at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
>at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
>at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
>at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
>at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
>at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
>Exception in thread "main"
Какая версия java? В терминале java -version пропиши.

**Comment by dayd21git** [comment]
> > > скомпилированная более поздней версией среды выполнения Java (версия файла классов 55.0), эта версия среды выполнения Java распознает только версии файлов классов до 52.0
> > > в java.lang.ClassLoader.defineClass1 (собственный метод)
> > > в java.lang.ClassLoader. defineClass (ClassLoader.java:756)
> > > в java.security.SecureClassLoader.defineClass (SecureClassLoader.java:142)
> > > в java.net.URLClassLoader.defineClass (URLClassLoader.java:468)
> > > в java.net.URLCaclassLoader (URLClassLoader.java:468) в java.net.URLCaclassLoader (URLClassLassLassLoader. java: 74)
> > > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:369)
> > > в java.net.URLClassLoader $ 1.run (URLClassLoader.java:363)
> > > в java.security.AccessController.doPrivileged (собственный метод)
> > > в java .net.URLClassLoader.findClass (URLClassLoader.java:362)
> > > в java.lang.ClassLoader.loadClass (ClassLoader.java:418)
> > > в sun.misc.Launcher $ AppClassLoader.loadClass (Launcher.java:352)
> > > в java.lang.ClassLoader.loadClass (ClassLoader.java:351)
> > > на солнце. instrument.InstrumentationImpl.loadClassAndStartAgent (InstrumentationImpl.java:304)
> > > в sun.instrument.InstrumentationImpl.loadClassAndCallPremain (InstrumentationImpl.java:401)
> > > Исключение в потоке «main»
> > 
> > 
> > Какая версия java? В терминале `java -version`пропиши.
> 
> $ java -version
> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

Для работы лаунчсервера требуется java8.

**Comment by Zaxar163** [comment]
http://launcher.gravit.pro
![image](https://user-images.githubusercontent.com/35835496/126520248-caccdb40-7e85-46cc-913d-2437b1051917.png)
А вообще такие вопросы лучше в Discord канал.
