### ISSUE TITLE
Неизвестная ошибка

### ISSUE THREAD

**Issue by SkyReglis** [GravitLauncher/Launcher#507]
Включен дебаг, в консоли видим такую ошибку в консоли лаунчера, как это отлаживать только бог знает

![image](https://user-images.githubusercontent.com/87978612/129399304-d8ae2251-6c41-45b8-9917-81efc2a8fa8b.png)

**Comment by microwin7** [comment]
Включите дебаг режим

**Comment by H4kt** [comment]
Ты прочел хоть сообщение выше?

**Comment by microwin7** [comment]
Покажите аргументы запуска, а так же "env" в конфиге LaunchServer.json

**Comment by H4kt** [comment]
Запуск дефолтный
```bash
#!/bin/bash
java -javaagent:LaunchServer.jar -jar LaunchServer.jar;
```

env: `STD`

**Comment by microwin7** [comment]
Включите дебаг режим по инструкции, тогда обращайтесь снова

**Comment by H4kt** [comment]
А команда `debug true` сделана тупо по приколу?

**Comment by H4kt** [comment]
Я уже не говорю о качестве кода в вашем проекте как бы...
Уже стало ясно, что использовать это на проде - самоубийство

**Comment by microwin7** [comment]
Версия лаунчсервера какая?

**Comment by microwin7** [comment]
Через параметр ENV
Выставите в конфигурации лаунчсервера параметр env в DEBUG

**Comment by microwin7** [comment]
`debug true` более не работает на 5.2.0

**Comment by microwin7** [comment]
Стактрейс не показывает

**Comment by H4kt** [comment]
Где об этом сказано?
Почему команда до сих пор существует тогда?

**Comment by microwin7** [comment]
в дискорд сервере об этом говорилось много раз точно

**Comment by H4kt** [comment]
Почему не в документации?

**Comment by microwin7** [comment]
Включайте и присылайте лог

**Comment by H4kt** [comment]
Опять же не вижу ответа на мой вопрос...

**Comment by H4kt** [comment]
> Через параметр ENV
> Выставите в конфигурации лаунчсервера параметр env в DEBUG

И тебя не смущает тот факт, что для этого нужно делать рестарт прямо на проде?

**Comment by microwin7** [comment]
как минимум дебаг был включен не совсем верно
команда полная `debug true true`

**Comment by microwin7** [comment]
о чём сказано на вики

**Comment by microwin7** [comment]
И версия лаунчсервера не была сказана до сих пор

**Comment by H4kt** [comment]
`debug true`
принтит в ответ
`debug: true`
`stacktrace: true`

Вот тебе трейс
```
2021.08.13 21:05:22 [ERROR] java.lang.NullPointerException
        at pro.gravit.utils.helper.CommonHelper.low(CommonHelper.java:31)
        at pro.gravit.launchserver.auth.handler.CachedAuthHandler.addEntry(CachedAuthHandler.java:80)
        at pro.gravit.launchserver.auth.handler.CachedAuthHandler.getEntry(CachedAuthHandler.java:130)
        at pro.gravit.launchserver.auth.handler.CachedAuthHandler.uuidToUsername(CachedAuthHandler.java:180)
        at pro.gravit.launchserver.socket.response.profile.ProfileByUUIDResponse.execute(ProfileByUUIDResponse.java:63)
        at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:169)
        at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:119)
        at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:70)
        at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:19)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by H4kt** [comment]
> И версия лаунчсервера не была сказана до сих пор

5.1.10-2 stable

**Comment by microwin7** [comment]
Извините, мы не предоставляем поддержку по не нашему коду
https://github.com/H4kt/GravitLauncherPatched/commit/f7613ed093f93637e0beb67bff9b2373dba3702a

**Comment by microwin7** [comment]
Может кто другой и подскажет что не так, я на этом всё

**Comment by H4kt** [comment]
Этот патч никак не связан с ошибкой

**Comment by H4kt** [comment]
Спокойно повторяется без него на чистом гравите

**Comment by H4kt** [comment]
Складывается ощущение, что вы сами просто не понимаете что происходит)

**Comment by microwin7** [comment]
Версия java `java -version` какая?

**Comment by H4kt** [comment]
`11.0.11`

**Comment by microwin7** [comment]
При каком событии эта ошибка возникает?

**Comment by H4kt** [comment]
Понятия не имеем
Сейчас тупо летит её спам

**Comment by microwin7** [comment]
Настройки AuthHandler покажите

**Comment by H4kt** [comment]
```
"type": "json",
"getUrl": "http://localhost:1337/auth/resolve",
"updateAuthUrl": "http://localhost:1337/auth/token/refresh",
"updateServerIdUrl": "http://localhost:1337/auth/updateServerId"
```

**Comment by microwin7** [comment]
Такая проблема уже была у одного пользователя, тоже использовал json, пробела видимо в этом, проблему тогда не выяснили (исследовал архив переписок)

**Comment by microwin7** [comment]
Что мешает использовать метод mysql?

**Comment by H4kt** [comment]
Нужно это как-то решать
Ибо модель ответа от сервака в точности по документации

**Comment by H4kt** [comment]
> Что мешает использовать метод mysql?

Как минимум алгоритм хеширования

**Comment by microwin7** [comment]
хеширования чего? это AuthHandler, а не AuthProvider

**Comment by H4kt** [comment]
Тут сорян, путаюсь в них ибо очень странно что это вообще два отдельных компонента.
Не понимаю вообще требования к использованию конкретного метода. Если уж вы предоставляете возможность использовать Rest API для этого, то соответственно должны его поддерживать.

**Comment by microwin7** [comment]
Лично не тестировал этот метод на 5.1.10, видел только раз как его используют и вроде не жаловались. Но Гравита говорила, что этот метод может быть проблемным и лучше не использовать.
Так же можете показать выходные данные, что отвечает скрипт, для сверки

**Comment by H4kt** [comment]
Пример ответа от API
`curl -H 'Content-Type: application/json' -X POST -d '{"username": "H4kt"}' http://localhost:1337/auth/resolve`
```
{"username":"H4kt","uuid":"3461fb72-4573-4111-948f-e9ad880ecf22","serverID":null,"accessToken":"*hidden*","permissions":1}```

**Comment by microwin7** [comment]
Почему null?

**Comment by microwin7** [comment]
ServerID может быть либо устаревшим, но быть, либо обновлённым, как помню

**Comment by H4kt** [comment]
> ServerID может быть либо устаревшим, но быть, либо обновлённым, как помню

Допустим аккаунт был только что создан

**Comment by microwin7** [comment]
Передавайте ""

**Comment by microwin7** [comment]
И скажите результат

**Comment by H4kt** [comment]
По всем стандартам json такое поле не может быть пустой строкой. В добавок к этому, проблема возникла только сегодня, до этого все работало стабильно.

**Comment by microwin7** [comment]
Возможно стоит презапустить лаунчсервер

**Comment by H4kt** [comment]
Пробовади несколько раз - бестолку

**Comment by microwin7** [comment]
> По всем стандартам json такое поле не может быть пустой строкой. В добавок к этому, проблема возникла только сегодня, до этого все работало стабильно.

![image](https://user-images.githubusercontent.com/12544425/129407233-22c58cf4-6fca-4b05-a3af-696ce9ef31a0.png)
Может

**Comment by H4kt** [comment]
> > По всем стандартам json такое поле не может быть пустой строкой. В добавок к этому, проблема возникла только сегодня, до этого все работало стабильно.
> 
> ![image](https://user-images.githubusercontent.com/12544425/129407233-22c58cf4-6fca-4b05-a3af-696ce9ef31a0.png)
> Может

Ты не совсем понял о чем я.
Это поле по сути дела энумерация и уж пустой строкой его передавать - это уже верх некорректности

**Comment by H4kt** [comment]
Тем более что может быть кейс отсутсвия значения в этом поле. Лаунчсервер должен корректно это обрабатывать.

**Comment by microwin7** [comment]
Ну у меня именно подозрения на то что может не верно понимать "null"

**Comment by microwin7** [comment]
> Тем более что может быть кейс отсутсвия значения в этом поле. Лаунчсервер должен корректно это обрабатывать.

там проверка есть на null, но может быть с типом проблема, попробовать не проблема

**Comment by microwin7** [comment]
Посмотрел код класса CachedAuthHandler.java
Проблема почти очевидна, что где-то null
Но тут похоже ошибка с ником или uuid, сделайте отладку в коде всех данных приходящих, но перед записью их в Entry

**Comment by gravit0** [comment]
> `debug true`
> принтит в ответ
> `debug: true`
> `stacktrace: true`
> 
> Вот тебе трейс
> 
> ```
> 2021.08.13 21:05:22 [ERROR] java.lang.NullPointerException
>         at pro.gravit.utils.helper.CommonHelper.low(CommonHelper.java:31)
>         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.addEntry(CachedAuthHandler.java:80)
>         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.getEntry(CachedAuthHandler.java:130)
>         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.uuidToUsername(CachedAuthHandler.java:180)
>         at pro.gravit.launchserver.socket.response.profile.ProfileByUUIDResponse.execute(ProfileByUUIDResponse.java:63)
>         at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:169)
>         at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:119)
>         at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:70)
>         at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:19)
>         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
>         at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>         at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
>         at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> ```

У вас username null. Это грубейшая ошибка со стороны скрипта или БД. Проверьте свою базу и скрипт на корректность, SQL запрос я думаю напишите сами

**Comment by gravit0** [comment]
Рекомендую перейти на JsonAuthCoreProvider в 5.2.0, AuthProvider/AuthHandler будут удалены в следующих релизах
https://github.com/GravitLauncher/Launcher/releases/tag/v5.2.0-stable

**Comment by H4kt** [comment]
> > `debug true`
> > принтит в ответ
> > `debug: true`
> > `stacktrace: true`
> > Вот тебе трейс
> > ```
> > 2021.08.13 21:05:22 [ERROR] java.lang.NullPointerException
> >         at pro.gravit.utils.helper.CommonHelper.low(CommonHelper.java:31)
> >         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.addEntry(CachedAuthHandler.java:80)
> >         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.getEntry(CachedAuthHandler.java:130)
> >         at pro.gravit.launchserver.auth.handler.CachedAuthHandler.uuidToUsername(CachedAuthHandler.java:180)
> >         at pro.gravit.launchserver.socket.response.profile.ProfileByUUIDResponse.execute(ProfileByUUIDResponse.java:63)
> >         at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:169)
> >         at pro.gravit.launchserver.socket.WebSocketService.process(WebSocketService.java:119)
> >         at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:70)
> >         at pro.gravit.launchserver.socket.handlers.WebSocketFrameHandler.channelRead0(WebSocketFrameHandler.java:19)
> >         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
> >         at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
> >         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> >         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> >         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> >         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> >         at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
> >         at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
> >         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
> >         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> >         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> >         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> >         at java.base/java.lang.Thread.run(Thread.java:829)
> > ```
> 
> У вас username null. Это грубейшая ошибка со стороны скрипта или БД. Проверьте свою базу и скрипт на корректность, SQL запрос я думаю напишите сами

Ни UUID ни username не null
По непонятной мне причине Gravit не умеет хандлить 404 от сервера, если вдруг аккаунт был удалён

**Comment by gravit0** [comment]
Код ответа игнорируется если в ответе содержится валидный JSON
Если вы передаете описание ошибки - тогда понятно почему у вас username null
Достаточно вернуть пустое тело ответа или написать свой провайдер с собственной обработкой

**Comment by H4kt** [comment]
> Код ответа игнорируется если в ответе содержится валидный JSON
> Если вы передаете описание ошибки - тогда понятно почему у вас username null
> Достаточно вернуть пустое тело ответа или написать свой провайдер с собственной обработкой

Код ответа должен проверятся всегда и в первую очередь.
