### ISSUE TITLE
Краш на авторизации

### ISSUE THREAD

**Issue by Mastaxys** [GravitLauncher/Launcher#509]
1. Установлен последний билд гравита.
2. настроена авторизация на "phppass" (стоит сайт на WordPress)
3. внесены все таблицы и зависимости в MySQL
4. собран лаунчер
5. при попытке авторизации если вписывать несуществующего пользователя, то так и пишет, что пользователь не найден.
Если же вписать существующий логин, то вне зависимости и верности пароля (даже пустой) вылетает краш (Fatal server error. Contact administrator)
6. В дебаглоге следующее: 
2021-08-21 09:14:27.983 [epollEventLoopGroup-3-1] ERROR pro.gravit.launchserver.socket.WebSocketService - WebSocket request processing failed
java.lang.NullPointerException: null
	at pro.gravit.launchserver.auth.core.MySQLCoreProvider.verifyPassword(MySQLCoreProvider.java:114) ~[LaunchServer.jar:?]
	
7. полный дебаглог: https://pastebin.com/FGZd7G1t

**Comment by gravit0** [comment]
Вы забыли указать passwordVerifier или не установили модуль Additional Hash

**Comment by gravit0** [comment]
Перепроверьте конфигурацию по вики

**Comment by Mastaxys** [comment]
Конфигурацию проверил, passwordVerifier  указан "type": "phpass".
пытаюсь поставить модуль AdditionalHash.
Так вот с конфигом проблема:
`  "binaryName": "Launcher",
  "copyBinaries": true,
  "cacheUpdates": true,
  "env": "STD",
  "auth": {
    "std": {
      "isDefault": true,
      "core": {
        "type": "mysql-bcrypt",
          "mySQLHolder": {
            "address": "localhost",
            "port": 3306,
            "username": "root",
            "password": "password",
            "database": "db?serverTimezone=UTC"
          },
        "passwordVerifier": {
          "type": "phpass"
        },
        "query": "SELECT password, name, permission FROM dle_users WHERE (email=? OR name=?)",
        "queryParams": [ "%login%", "%login%" ],
        "usePermission": true,
        "message": "Пароль неверный!"
      },
      "textureProvider": {
        "skinURL": "http://example.com/skins/%username%.png",
        "cloakURL": "http://example.com/cloaks/%username%.png",
        "type": "request"
      },
      "displayName": "Default"
    }
  },`
ЗЫ, настройки делаю под свою реальную базу.
выдает ошибку :
14:20:03.450 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.0-1 stable (build #1)
14:20:03.451 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
14:20:03.984 [INFO ] JLine2 terminal enabled
14:20:03.987 [INFO ] Reading LaunchServer config file
14:20:04.020 [INFO ] Reading LaunchServer runtime config file
14:20:04.028 [INFO ] Reading ECDSA keypair
14:20:04.032 [INFO ] Reading RSA keypair
Exception in thread "main" java.lang.NullPointerException: Auth std provider null
        at pro.gravit.launchserver.auth.AuthProviderPair.init(AuthProviderPair.java:84)
        at pro.gravit.launchserver.config.LaunchServerConfig.init(LaunchServerConfig.java:185)
        at pro.gravit.launchserver.LaunchServer.<init>(LaunchServer.java:181)
        at pro.gravit.launchserver.LaunchServerBuilder.build(LaunchServerBuilder.java:91)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:187)
