### ISSUE TITLE
Не работает LogHelper

### ISSUE THREAD

**Issue by microwin7** [GravitLauncher/Launcher#519]
Вероятное место проблемы
```public static void addOutput(OutputEnity output) {
        impl.addOutput(output);
    }

    public static void addExcCallback(Consumer<Throwable> output) {
        EXCEPTIONS_CALLBACKS.add(Objects.requireNonNull(output, "output"));
    }

    public static void addOutput(Output output, OutputTypes type) {
        addOutput(new OutputEnity(Objects.requireNonNull(output, "output"), type));
    }
 ```
 При попытке (в модуле DiscordIntegration
 LogHelper.OutputEnity webLog = new LogHelper.OutputEnity(DSIntegrationModule::sendMsg, LogHelper.OutputTypes.PLAIN);
 В DSIntegrationModule::sendMsg передаётся пустое сообщение

**Comment by microwin7** [comment]
Отладка принимает из output
Как и
```
LogHelper.OutputEnity STD_OUTPUT = new LogHelper.OutputEnity(System.out::println, LogHelper.OutputTypes.PLAIN);
LogHelper.addOutput(STD_OUTPUT);
```
такое
help
pro.gravit.launchermodules.discordintegration.MessageListener$$Lambda$495/0x0000000100533040@3a0d0c5c
pro.gravit.launchermodules.discordintegration.MessageListener$$Lambda$496/0x0000000100533440@fe73c45

Из класса LogHelper
```
public OutputEnity(Output output, OutputTypes type) {
            System.out.println(output);
            this.output = output;
            this.type = type;
        }
```

**Comment by gravit0** [comment]
Вы не должны использовать LogHelper в модулях для лаунчсервера. Вместо этого для логгирования используйте уже настроенный log4j, а для получения лога - LogAppender
Пример можно найти в модуле RemoteControlModule
