### ISSUE TITLE
Ошибка запуска клиента 1.17.1 forge

### ISSUE THREAD

**Issue by DintyGadget** [GravitLauncher/Launcher#525]
Версия и ошибка полученная через Debug-консоль лаунчера:
- forge v. 37.0.97
```GravitLauncher (fork sashok724's Launcher) Client Launcher v5.2.4-2 stable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021.10.18 20:00:14 [WARN] JLine2 isn't in classpath, using std
2021.10.18 20:00:14 [INFO] Reading EC keypair
2021.10.18 20:00:14 [INFO] Using Sessions
2021.10.18 20:00:14 [INFO] 16.0.1+9-24
2021.10.18 20:00:14 [INFO]  DirWatcher C:\Users\DintyPCBigCow\AppData\Roaming\PonyWave\updates\asset1.17.1
2021.10.18 20:00:14 [INFO]  DirWatcher C:\Users\DintyPCBigCow\AppData\Roaming\PonyWave\updates\Modding
2021.10.18 20:00:15 [ERROR] java.lang.ExceptionInInitializerError
2021.10.18 20:00:15 [INFO] WebSocket client disconnect
Process exit code 0
```
Измененные/добавленные аргументы профиля:
```
"clientArgs": [
"--launchTarget",
"forgeclient",
"--fml.forgeVersion",
"37.0.97",
"--fml.mcVersion",
"1.17.1",
"--fml.forgeGroup",
"net.minecraftforge",
"--fml.mcpVersion",
"20210706.113038"
],

"mainClass": "cpw.mods.bootstraplauncher.BootstrapLauncher"
```

**Comment by Dancbeunny98** [comment]
Ждём поддержку лайнером

**Comment by DonorKrovi** [comment]
> 

причём тут вообще лаунчер?

**Comment by XionioXMaster** [comment]
> Forge 1.17 не поддерживается данным лаунчером: ![image](https://user-images.githubusercontent.com/66722732/137740460-61c2cbc3-2ade-4499-acee-2f2512659580.png)
> 
> Однако, у пользователя 𝓟𝓱𝓸𝓽𝓸𝓷 получилось его привязать: ![image](https://user-images.githubusercontent.com/66722732/137740644-ce4e1b71-47ca-40b7-8a2e-d912d4dbad1f.png) Он продает его, вы можете попробовать с ним поговорить.
> 
> Вы можете добавить в аргументы:
> 
> ```
> "jvmArgs": [
> 	"-DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-,37.0.90.jar",
> 	"-DmergeModules=jna-5.8.0.jar,jna-platform-58.0.jar,java-objc-bridge-1.0.0.jar",
> 	"-DlibraryDirectory=libraries",
> 	"-Djava.library.path=natives",
> 	"-p","libraries/cpw/mods/bootstraplauncher/0.1.17/bootstraplauncher-0.1.17.jar;libraries/cpw/mods/securejarhandler/0.9.54/securejarhandler-0.9.54.jar;libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar;libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar;libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar;libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar;libraries/org/ow2/asm/asm/9.1/asm-9.1.jar",
> 	"--add-modules",
> 	"ALL-MODULE-PATH",
> 	"--add-opens",
> 	"java.base/java.util.jar=cpw.mods.securejarhandler",
> 	"--add-exports",
> 	"java.base/sun.security.util=cpw.mods.securejarhandler",
> 	"--add-exports",
> 	"jdk.naming.dns/com.sun.jndi.dns=java.naming"
>   ]
> ```
> 
> И получите ошибку которая может решится только патчем forge или одного из его компонентов Вы можете подождать некоторое время, и возможно эта ошибка исправится сама.

Есть варик написать коллективно на гит форджа с просьбой о патче? Просто я не особо понимаю что им написать

**Comment by dimadencep** [comment]
> Есть варик написать коллективно на гит форджа с просьбой о патче? Просто я не особо понимаю что им написать

Смысл? Да и ради твоих "прихотей" я делать ничего не буду

**Comment by dimadencep** [comment]
> Решить можно только патчем библиотеки Forge Bootstraper

Так пропатчи, там ничего сложного нету https://github.com/McModLauncher/bootstraplauncher

**Comment by XionioXMaster** [comment]
> > Есть варик написать коллективно на гит форджа с просьбой о патче? Просто я не особо понимаю что им написать
> 
> Смысл? Да и ради твоих "прихотей" я делать ничего не буду

да мне пофиг на тебя чел...

**Comment by XionioXMaster** [comment]
> > Решить можно только патчем библиотеки Forge Bootstraper
> 
> Так пропатчи, там ничего сложного нету https://github.com/McModLauncher/bootstraplauncher

Да-да-да, особенно ты сможешь

**Comment by egorsgn** [comment]
> > > Решить можно только патчем библиотеки Forge Bootstraper
> > 
> > Так пропатчи, там ничего сложного нету https://github.com/McModLauncher/bootstraplauncher
> 
> Да-да-да, особенно ты сможешь

Сынок непробритой шлюшанки зач ты выписываешь??

**Comment by XionioXMaster** [comment]
> > > > Решить можно только патчем библиотеки Forge Bootstraper
> > > 
> > > 
> > > Так пропатчи, там ничего сложного нету https://github.com/McModLauncher/bootstraplauncher
> > 
> > 
> > Да-да-да, особенно ты сможешь
> 
> Сынок непробритой шлюшанки зач ты выписываешь??

клоун даже фейк акк на гите сделал что бы оскорбить, очень остроумно.
