### ISSUE TITLE
"pro.gravit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.LaunchServer)" because "this.core" is null

### ISSUE THREAD

**Issue by Felicitas12** [GravitLauncher/Launcher#526]
"pro.gravit.launchserver.auth.core.AuthCoreProvider.init(pro.gravit.launchserver.LaunchServer)" because "this.core" is null
модулей нет, просто когда меняю "reject" на "accept", вылетает такая ошибка, тоже самое если туда подставлю в место "core": {
        "type": "accept"
      }
вот это
"std": {
      "core": {
        "type": "mysql",
        "mySQLHolder": {
          "address": "localhost",              // адрес mysql сервера
          "port": 3306,                        // порт mysql сервера
          "username": "launchserver",          // имя пользователя
          "password": "password",              // пароль пользователя
          "database": "db?serverTimezone=UTC", // база данных (до ?), после — параметры базы данных, в этом примере — установка серверного часового пояса
          "timezone": "UTC",                   // установка клиентского часового пояса
          "useHikari": true                    // Использовать HikariCP
        },
        "passwordVerifier": {                  // Ваш PasswordVerifier
          "algo": "SHA256",
          "type": "digest"
        },
        "table": "users",                      // таблица
        "tableHwid": "hwids",
        "uuidColumn": "uuid",                  // название столбца с uuid
        "usernameColumn": "username",          // название столбца с именами пользователей
        "passwordColumn": "password",          // название столбца с паролем пользователя
        "accessTokenColumn": "accessToken",    // название столбца с accessToken
        "hardwareIdColumn": "hwidId",          // название столбца с ID записи в таблице hwids
        "serverIDColumn": "serverID"           // название столбца с serverID
      },
      "isDefault": true,
      "displayName": "Default"
    }

**Comment by MrHatter89** [comment]
"type": "accept" более не существует в новой версии, для этого можешь использовать модуль FileAuthSystem (в нём есть возможность включить авторегистрацию пользователя)

**Comment by MrHatter89** [comment]
https://github.com/GravitLauncher/LauncherModules/tree/master/FileAuthSystem_module
подробнее к сожалению не могу что-то сказать, только то что там написано в описании модуля. Остальную информацию лучше получить в дискорд канале гравита.
