### ISSUE TITLE
[Предложение] Клиент 1.16.5

### ISSUE THREAD

**Issue by XionioXMaster** [GravitLauncher/Launcher#531]
Здравствуйте, не могли бы вы обновить клиент Forge до его последней актуальной версии на данный момент?

Если качать его из mirror гравита мы получим очень старую и уже не актуальную версию.
https://mirror.gravit.pro/clients/

**Comment by Dbarkovski** [comment]
Что мешает самому обновить? Там же ничего сложного вообще нет.

**Comment by LeonusDH** [comment]
> Здравствуйте, не могли бы вы обновить клиент Forge до его последней актуальной версии на данный момент?
> 
> Если качать его из mirror гравита мы получим очень старую и уже не актуальную версию. https://mirror.gravit.pro/clients/

1. Для подобных предложений, есть дискорд сервер, с разделом предложений.
2. Клиент Forge 1.16.5, есть в закрепе в offtop в официальном дискорд сервере, хоть и с некоторыми условностями, которые указаны.
3. Последняя актуальная версия Forge (1.17.1), требует модификаций библиотек. На данный момент, у разработчика, есть более важные дела. Возможно, обновление будет на зеркале, но точной даты нет.

**Comment by Dbarkovski** [comment]
Для ленивых обновил и залил на зеркало себе.

**Comment by XionioXMaster** [comment]
> Для ленивых обновил и залил на зеркало себе.

можно зеркало?

**Comment by Dbarkovski** [comment]
Minemirror.tk

**Comment by gravit0** [comment]
Новые клиенты собраны и ожидают релиза 5.2.8
