### ISSUE TITLE
HD скины не отображаться корректно, онлайн-одиночная игра

### ISSUE THREAD

**Issue by XionioXMaster** [GravitLauncher/Launcher#533]
![image](https://user-images.githubusercontent.com/86433158/141938240-85f06abc-8afa-4782-be0f-fad6a9635dba.png)

HD плащи и простые скины отображаются, но вот HD скины просто превращаются в фарш.

Использовал https://launcher.gravit.pro/clientbuild#authlib1

Последняя стабильная версия гравита.

**Comment by microwin7** [comment]
Вы не указали откуда скачан и какой версии клиент. Так же, какие файлы сами меняли в libraries

**Comment by gravit0** [comment]
Для работы HD скинов вы должны установить Optifine/Sodium (какие версии поддерживают HD скины уточняйте сами)
Если у вас slim скин то вы должны использовать AuthCoreProvider либо TextureProvider с поддержкой slim скинов, а так же у вас долженг быть authlib 1/2 от 5.2.0 и выше
