### ISSUE TITLE
Резкая остановка скачивания клиента

### ISSUE THREAD

**Issue by JeffAdventure** [GravitLauncher/Launcher#534]
При резкой остановке скачивания клиента, закрытии лаунчера, медленной скорости и еще миллионе причин остановки загрузки, порой бывает такое что выбивает в ошибку Exception class java.util.concurrent.CompletionException: java.io.EOFException: N-n bytes remaining

Пример, скачивал сборку свою, с модами, после отмены скачивания, закрытия лаунчера и с последующим удалением клиента и перезапуском ошибка остается той же.
Exception class java.util.concurrent.CompletionException: java.io.EOFException: 108 bytes remaining

Удаление клиента не помогло, удаление ассетов не помогло.
Прикрепляю изображение ошибки ибо до стадии запуска клиента не дошло.
Ошибка наблюдается еще с ранних стадий GravitLauncher.
![image](https://user-images.githubusercontent.com/15940351/143491210-c6abd10f-7dfd-4b05-9372-8d0e53ac2819.png)

**Comment by gravit0** [comment]
Исправляется командой `syncup`
Пожалуйста не забывайте синхронизировать updates после изменений

**Comment by Kostyadayn** [comment]
чел ты крут

**Comment by BangRoiz** [comment]
syncup

**Comment by BangRoiz** [comment]
помогите пожалуйста

**Comment by SuperA001** [comment]
@gravit0 В данный момент у меня идентичная проблема. Дело в моде насколько я понял его просто не хочет загружать лаунчер, хотя мод самописный, он отлично и без ошибок запускается на Forge 1 16 5. Скомпилирован с помощью JDK 1.8
