### ISSUE TITLE
ошыбка помогите 

### ISSUE THREAD

**Issue by yuliitezary** [GravitLauncher/Launcher#536]
21:02:29.416 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.6-1 stable (build #1)
21:02:29.425 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
Exception in thread "main" java.lang.RuntimeException: Module OneLauncher required ClientLauncherCore. ClientLauncherCore not found
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.checkDepend(SimpleModuleManager.java:109)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.initModules(SimpleModuleManager.java:82)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:90)
Для продолжения нажмите любую клавишу . . .
![изображение](https://user-images.githubusercontent.com/94526027/144111199-bdd21a16-b1a3-46bf-848b-16bdc8b9fb5b.png)

**Comment by yuliitezary** [comment]
> 21:02:29.416 [INFO ] GravitLauncher (fork sashok724's Launcher) LaunchServer v5.2.6-1 stable (build #1) 21:02:29.425 [INFO ] License for LaunchServer GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher Exception in thread "main" java.lang.RuntimeException: Module OneLauncher required ClientLauncherCore. ClientLauncherCore not found at pro.gravit.launcher.modules.impl.SimpleModuleManager.checkDepend(SimpleModuleManager.java:109) at pro.gravit.launcher.modules.impl.SimpleModuleManager.initModules(SimpleModuleManager.java:82) at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:90) Для продолжения нажмите любую клавишу . . . ![изображение](https://user-images.githubusercontent.com/94526027/144111199-bdd21a16-b1a3-46bf-848b-16bdc8b9fb5b.png)

**Comment by fid3n** [comment]
how 2 fix
