### ISSUE TITLE
Не работает с macOS 12

### ISSUE THREAD

**Issue by Madaspe** [GravitLauncher/Launcher#545]
Логи лаунчера - https://pastebin.com/BYE5zi3k

$ java -version
`java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)`

Администрация проекта не может ничего с этим сделать, отвечают что проблема именно в Гравити лаунчере

**Comment by Madaspe** [comment]
Доп инфа, с джавой версии 1.8.0_231 все работает

**Comment by gravit0** [comment]
Лаунчер никак не влияет на майнкрафт, за исключением процесса загрузки классов. Судя по логу ошибки, проблема в lwjgl. Попробуйте пересобрать нативы или обновить lwjgl если это возможно(это может сделать только администратор проекта)
Если есть какие то настройки - попробуйте их поменять
