### ISSUE TITLE
Нестабильная работа gravit launcher с версией 1.17.1 с ядрами papermc/purpur.

### ISSUE THREAD

**Issue by RitaSister** [GravitLauncher/Launcher#548]
Здраствуйте, я думаю возможно известна вам эта проблема, что нет стабильной поддержки бумаги или пурпура на гравит лаунчере и из-за этого WorldGuard плагин на paper\purprur не работает вовсе.

**Comment by RitaSister** [comment]
[22:49:17 INFO]: [WorldGuard] Disabling WorldGuard v7.0.5+3827266
[22:49:17 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[22:49:17 INFO]: [WorldGuard] Known tasks:
Claiming region 'testtt'

**Comment by Dbarkovski** [comment]
Интересно, конечно, но зачем на 1.17.1 запускать WorldGuard который её не поддерживает?
WorldGuard v7.0.5+3827266 - только для 1.16.5
Поставь версию https://dev.bukkit.org/projects/worldguard/files/3461546 - в ней уже должна быть поддержка 1.17-1.18 судя по ченджлогам.

**Comment by RitaSister** [comment]
Факт в том, что нет поддержки адвекватной uuid

**Comment by DonorKrovi** [comment]
> Факт в том, что нет поддержки адвекватной uuid

у меня всё работает как часики

**Comment by RitaSister** [comment]
отпиши в дискорде пожалуйста RitaSister#0664

**Comment by XionioXMaster** [comment]
> ###

такая же проблема, сервер мгновенно нагружает на 100% и он падает.

**Comment by dimadencep** [comment]
Сначала попробуйте без привязки к gravitlauncher

**Comment by xstmass** [comment]
Проблема тут, в использовании паперовских штучек: https://github.com/EngineHub/WorldGuard/blob/3cb4abdbf71867cbd8d6c565a4e9d253969e60bb/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/BukkitWorldGuardPlatform.java#L248

**Comment by VacheLorian** [comment]
Та же проблема… Решение, по типу переписать плагин на использование ONLY_NAME - бред, возвращающий в каменный век. После этого как минимум удалять оффлайн игроков из привата невозможно.

**Comment by gravit0** [comment]
Вопросы по серверным ядрам не относятся к лаунчеру. Предоставьте более подробную информацию если проблема всё ещё актуальна
Полные логи ошибок, точные версии плагинов и ядра, а так же проверьте работоспособность без привязки к лаунчеру
