### ISSUE TITLE
Бан игроков по железу

### ISSUE THREAD

**Issue by JoValid** [GravitLauncher/Launcher#550]
Приветствую. Объясните пожалуйста как делать бан игроков по железу. Обыскал основной сайт Гравита, но не нашел информации об этом. Буду очень признателен.

**Comment by MatweyCat** [comment]
Для начала в protectHandler (конфиг лаунчсервера) делаешь enableHardwareFeature на true, а type на advanced
```
  "protectHandler": {
    "profileWhitelist": {},
    "allowUpdates": ["java8-windows-64", "etc-java"],
    "enableHardwareFeature": true,
    "type": "advanced"
  },
```

**Comment by gravit0** [comment]
По умолчанию в новых версиях стоит тип advanced. Достаточно просто включить проверку HWID
