### ISSUE TITLE
Реализация двух и более картинок для сервера в runtime

### ISSUE THREAD

**Issue by drobot123** [GravitLauncher/Launcher#551]
Как реализовать, чтобы для каждого сервера была своя картинка? В profiles полазил и не нашёл. Можете подсказать?

**Comment by LeonusDH** [comment]
Прочесть вики...

**Comment by drobot123** [comment]
Я прочитал и не нашёл данного пункта. Можете ссылку скинуть?

**Comment by LeonusDH** [comment]
Вариантов не много:
Либо ты слепой, либо ты ничего не искал
https://launcher.gravit.pro/runtime#entities

**Comment by drobot123** [comment]
Спасибо. Я искал в profile.
