### ISSUE TITLE
Отладка runtime

### ISSUE THREAD

**Issue by drobot123** [GravitLauncher/Launcher#552]
Простите, что такой глупый по вашей квалификации вопрос, но я не могу разобраться, как включить отладку в runtime. 
Для отладки рантайма из IDEA укажите следующие параметры:

Модуль: JavaRuntime.main
Аргументы jvm: -Dlauncherdebug.modules=pro.gravit.launcher.client.JavaRuntimeModule (если параметры не отображаются, нажмите Modify Options —> Add VM options)
Main Class: pro.gravit.launcher.debug.DebugMain

Я не пользовался II, поэтому не могу разобраться где и как это настроить. Помогите, если не трудно новичку. Спасибо

**Comment by dimadencep** [comment]
[launcher.gravit.pro/runtime/#отладка-рантайма](https://launcher.gravit.pro/runtime/#%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D1%80%D0%B0%D0%BD%D1%82%D0%B0%D0%B8%D0%BC%D0%B0)

**Comment by gravit0** [comment]
Откройте `Run` -> `Edit Configurations` и там создайте новую конфигурацию с типом Application, где и укажите все параметры
