### ISSUE TITLE
Своя версия майнкрафта.

### ISSUE THREAD

**Issue by MRDen3000YT** [GravitLauncher/Launcher#554]
Добрый день! Я изменил исходный код майнкрафта с помощью MCP и хочу залить его в лаунчер? Как мне это сделать?

**Comment by egorsgn** [comment]
> Добрый день! Я изменил исходный код майнкрафта с помощью MCP и хочу залить его в лаунчер? Как мне это сделать?

Не лезь туда, куда не знаешь.

**Comment by gravit0** [comment]
Замените файл `minecraft.jar` и выполните синхронизацию
