### ISSUE TITLE
Не качает моды с версией forge

### ISSUE THREAD

**Issue by freeze2222** [GravitLauncher/Launcher#555]
Здравствуйте, решил сделать по документации лаунчер для сервера с модами forge 1.12.2, уже пол часа пытаюсь понять как туда моды добавить, в доках ни слова нет про это. Копирую в updates/Hi-tech/mods/1.12.2 моды - ничего, лаунчер качает пустую папку. Так-же лежит какой-то файл MODS.txt, как я понял туда надо вписать моды которые надо загружать т.к если его удалить лаунчер не будет качать версию, но когда вписываю туда название мода ничего не меняется(
Помогите пожалуйста и, если можно, напишите в доках как устанавливать forge версии.
Спасибо!

**Comment by JeffAdventure** [comment]
Для глупых, туда надо не вписывать название модов, а добавлять моды в саму папку... А файлик можешь удалить...

**Comment by drobot123** [comment]
syncup прописывай, когда файлы добавляешь, а также, когда profile редактируешь!

**Comment by gravit0** [comment]
Для скачивания с зеркала клиентов с forge укажите `-forge` при скачивании. Например: `1.12.2-forge`
Моды вы должны положить в папку прямо в mods если не указано иное
Не забывайте использовать `syncup` при каждом обновлении для синхронизации
