### ISSUE TITLE
1.16.5 Запуск

### ISSUE THREAD

**Issue by silverfox0000** [GravitLauncher/Launcher#556]
Установлен полностью чистый клиент `1.16.5-forge` но при запуске выдаёт
 `[ERROR] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException` (При включенной Отладке в самом лаунчере) 
 Пробовал заменять библиотеки, версию форджа но ничего не помогало и ошибка была одной и той-же притом что стактрейса где ошибка не было
 
LaunchServer version: 5.2.8

P.S Не у меня одного проблемы с этой версией клиента [Тык](https://discord.com/channels/853340557522370561/853340558470414358/937773987327508501)

**Comment by dimadencep** [comment]
Руки кривые у тебя, закройте этот issue
