### ISSUE TITLE
Ошибка Gravit Laucher

### ISSUE THREAD

**Issue by MBandito** [GravitLauncher/Launcher#557]
![image](https://user-images.githubusercontent.com/98589454/151932528-30cd50a6-d5bf-4996-9fae-acedb85bd7c4.png)
Выдаёт ошибку при включении что делать??
Пытаюсь подключиться к базе данных сайта

**Comment by Frysuni** [comment]
Конфиг лаунчсервера покажите

**Comment by MagTemTenebrius** [comment]
1. Советую перейти на более новую версию.
2. Неверно настроен раздел авторизации в конфиг файле лаунчсервера.

**Comment by TheXaver** [comment]
Офтоп

**Comment by gru2007** [comment]
Auth std provider null - Тип авторизации std пуст

Другими словами конфиг настроен неверно.

**Comment by gru2007** [comment]
Перед тем как открывать ошибку на гите. Стоит хотяб в переводчик забить ошибку....
