### ISSUE TITLE
Использование своего User-Agent

### ISSUE THREAD

**Issue by JoCat** [GravitLauncher/Launcher#558]
Уже не в первый раз наблюдаются проблемы у людей, которые хостят сайты на веб помойках.

Предложение: использовать свой юзер-агент при отправке запросов, ибо на различных хостах может работать blacklist по юзер-агентам (напр. CF, Reg.ru, etc.)

**Comment by JoCat** [comment]
Ниже пример работы с веб-хостингом Reg.ru

При наличии в User-Agent вхождения слово Java:
![image](https://user-images.githubusercontent.com/13483132/152745478-9bb1fe18-abc0-41fd-9b44-b69f1af14229.png)

При его отсутствии:
![image](https://user-images.githubusercontent.com/13483132/152745531-8a7c1386-573b-4058-8a68-181da7fbef2d.png)

**Comment by microwin7** [comment]
https://github.com/GravitLauncher/Launcher/blob/master/LauncherCore/src/main/java/pro/gravit/launcher/HTTPRequest.java

**Comment by microwin7** [comment]
https://github.com/GravitLauncher/LauncherRuntime/blob/master/src/main/java/pro/gravit/launcher/client/gui/SkinManager.java 159 строка

**Comment by microwin7** [comment]
https://github.com/GravitLauncher/LauncherRuntime/pull/90

**Comment by dimadencep** [comment]
Сагласен

**Comment by microwin7** [comment]
https://github.com/GravitLauncher/Launcher/blob/master/LauncherCore/src/main/java11/pro/gravit/launcher/HTTPRequest.java

**Comment by microwin7** [comment]
> https://github.com/GravitLauncher/Launcher/blob/master/LauncherCore/src/main/java11/pro/gravit/launcher/HTTPRequest.java

https://github.com/GravitLauncher/Launcher/pull/560/commits/6c8ba831c267af2e1d383589722399ce073223ed

**Comment by microwin7** [comment]
> https://github.com/GravitLauncher/Launcher/blob/master/LauncherCore/src/main/java/pro/gravit/launcher/HTTPRequest.java

https://github.com/GravitLauncher/Launcher/pull/561/commits/cbeb02950af3b008556f1c628a53dd2e0d97f1fb

**Comment by microwin7** [comment]
> https://github.com/GravitLauncher/LauncherRuntime/blob/master/src/main/java/pro/gravit/launcher/client/gui/SkinManager.java 159 строка

https://github.com/GravitLauncher/LauncherRuntime/pull/93/commits/c7cac193e893a822ee167832d53fcb8e6812947e

**Comment by microwin7** [comment]
Issues можно закрывать, правки возможные внесены, на клиент мы влиять не сможем и не будем, встраивая User-Agent. На данный момент с таким обходом запроса, в игре скин всё равно не появится, только в лаунчере аватар.

P.S. Не используйте shared хостинги

**Comment by JoCat** [comment]
Да за игру вроде никто и не говорил, это проблема на совести админов. С вашей же стороны имеет смысл данным жестом уменьшить количество надоедливых вопросов в саппорт. В принципе вы это и сделали. Вопрос только в ишью https://github.com/GravitLauncher/LauncherRuntime/pull/93

**Comment by microwin7** [comment]
Извиняюсь, не точно выразился, со своей стороны мы сделали что посчитали возможным

**Comment by JoCat** [comment]
Увидел, приняли последний реквест, думаю ишью можно закрывать
