### ISSUE TITLE
Проверить причины зависания клиента при получении скина для голов и исправить по возможности

### ISSUE THREAD

**Issue by JoCat** [GravitLauncher/Launcher#559]
Баг тривиальный.
При запросе на получение скина головы зависает игра, причина вероятнее всего кроется в том, что запрос выполняется синхронно блокируя основной поток игры.

Путь запроса:
так как бошки привязываются к никнейму, то перед тем как получить скин нужно узнать uuid игрока
делается это через POST запрос:
`https://api.mojang.com/profiles/minecraft` (https://wiki.vg/Mojang_API#Usernames_to_UUIDs)
после чего, после полученного uuid делается GET запрос на получение скина:
`https://sessionserver.mojang.com/session/minecraft/profile/<uuid>` (https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape)
Похоже на то, что проблема появляется как раз на этапе первого запроса, ибо у меня при разработке лаунчера была аналогичная ситуация))
Судя по всему в коде лаунчера есть этот запрос, но не факт что он работает корректно, либо проблема кроется в серверах.
В общем нужно смотреть.

___

К слову этот баг трижды упоминался в гилде, но похоже как обычно всем было лень заводить ишью, поэтому придётся мне))
![image](https://user-images.githubusercontent.com/13483132/152746994-b60ff8af-d8e2-44e0-a047-b7853aeca3ed.png)
![image](https://user-images.githubusercontent.com/13483132/152747091-5a4ae85f-9cb1-400e-bd9f-065b1935d842.png)
![image](https://user-images.githubusercontent.com/13483132/152747180-82dba0d7-f87f-4ae7-8495-5f478a947aec.png)
![image](https://user-images.githubusercontent.com/13483132/152747269-90dcab26-a316-4765-967b-bf757e4e5d99.png)
![image](https://user-images.githubusercontent.com/13483132/152747360-5cab8b2b-ad82-495c-883e-d6c1731b6470.png)
![image](https://user-images.githubusercontent.com/13483132/152747470-875cd30e-2ff2-46af-84ff-0a596df6debc.png)
![image](https://user-images.githubusercontent.com/13483132/152747499-871f8f2f-30c9-43a0-ad07-40791e3bea2c.png)

**Comment by dimadencep** [comment]
Сагласен

**Comment by microwin7** [comment]
Если что, добавлю, вчера в саппорте речь про ЛолиСервер шла, но возможно это и в других ядрах сделано не верно

**Comment by microwin7** [comment]
Игрок должен видеть свою голову со скином, но к примеру на папере или спиготе, когда тестил, около года назад, была такая проблема, что свою видно, а если зайти с другого акка, то будет не моя голова, а того человека, что смотрит на эту голову

**Comment by dimadencep** [comment]
> Если что, добавлю, вчера в саппорте речь про ЛолиСервер шла, но возможно это и в других ядрах сделано не верно

Я через эсентиалс выдавал голову, выдалась Алекс и лагало оч, с офлайн млдом бошки некоторые со скином гиваются, тот же нотч

**Comment by dimadencep** [comment]
Головы конечно не нужная дичь но все же

**Comment by gravit0** [comment]
Проблема найдена и будет исправлена в ближайшем обновлении.
Метод получения uuid из username тут не причем - проблема была в специфическом методе установки texture properties, доставшейся нам в наследство. Мне эта реализация сразу не понравилась, но я решила - "работает - не трогай"
Я подготовила сборки 1.7.10, 1.12.2 и 1.16.5, но что бы всё протестировать требуется время

**Comment by gravit0** [comment]
Клиенты обновлены
