### ISSUE TITLE
1.7.10 Forge CoFHCore issue.

### ISSUE THREAD

**Issue by lexaSvarshik** [GravitLauncher/Launcher#562]
[Client thread/TRACE] [CoFHCore/CoFHCore]: Sending event FMLPreInitializationEvent to mod CoFHCore

And loading is crashing here.

exit code -1073740940
crash log is already on my GitHub
Java updated, drivers too.

Everything works fine on offcial minecraft launcher, but GravitLauncher crashes. Are somebody knows where are the bug?

**Comment by gravit0** [comment]
Please attach the full log and a detailed description of the error.

**Comment by lexaSvarshik** [comment]
> Please attach the full log and a detailed description of the error.
https://github.com/lexaSvarshik/LOGS-babkaCubes here logs.
 
Ошибку выдает постоянно одну и ту же. Лаунчер автоматически подгружает последнюю версию мода с курсФорджа; джава тестировалась ра3ная (либерика и оракл), дрова стоят последние на компьютере. Всё равно та же ошибка. 
Саму сборку запускал на оф. лаунчере, там спокойно загружает и пускает в сингл. На ВиртуалБоксе в лаунчере со скрипом запустилось, но вместо OpenGL была использована Mesa3D. Сейчас на компе стоит 2.1 GL но вряд ли проблема в этом.

**Comment by microwin7** [comment]
Если ещё актуально, попробуйте открыть файл config/splash.properties
Значение "enabled" установить в false

**Comment by microwin7** [comment]
Хотя предположу что характеристики ПК не подходят для игры, заметил такой пункт
Memory: 139557736 bytes (133 MB) / 301989888 bytes (288 MB) up to 1073741824 bytes (1024 MB)

**Comment by microwin7** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/3139857-cofhcore-issue
Так же вы подавали запрос на форум, к сожалению мы бы хотели бы тоже посмотреть что будет на другом каком-либо лаунчере с вашей сборкой, но там ответа не последовало. Прошу ответить на данный Issue ближайшее время

**Comment by lexaSvarshik** [comment]
Поздно, но я тут. Проблема была в системе/кривой сборке Винды. На Linux Manjaro завелось без проблем, как и на Win10.
