### ISSUE TITLE
[5.1.12 LTS] Не выполняется подключение к серверам через разные методы авторизации

### ISSUE THREAD

**Issue by dimadencep** [GravitLauncher/Launcher#565]
В версии 5.1.12 lts при нескольких типах авторизации вход на сервер работает только через один - тот через который авторизуется игровой сервер

При подключении без отладки (Л. Сервера) появляется ошибка - Не удалось проверить имя пользователя, при этом консоль сервера лаунчера пуста
Если же включить отладку (Л. Сервера) мы увидим ошибку - Службы аутентификации отключены. Повторите попытку позже, при этом в консоли игрового сервера мы увидим: Internal authHandler error, а сервер лаунчера поймает null [тут](https://github.com/GravitLauncher/Launcher/blob/support/5.1.X/LaunchServer/src/main/java/pro/gravit/launchserver/socket/response/auth/CheckServerResponse.java#L35)

[Отладка игрового сервера до включения отладки сервера лаунчера](https://www.toptal.com/developers/hastebin/zagawahode.md)
[Отладка игрового сервера после включения отладки сервера лаунчера](https://www.toptal.com/developers/hastebin/vutodiduba.md)
[Отладка сервера лаунчера](https://www.toptal.com/developers/hastebin/gihugikoqo.properties)
[Параметр auth в конфиге сервера лаунчера](https://www.toptal.com/developers/hastebin/azurepuqoq.lua)

Сразу отвечу на глупые вопросы:
С authlib все в порядке, как я указал выше: работает только через один - тот через который авторизуется сервер
Ядро сервера не важно, так как эта проблема активна на нескольких ядрах: forge, paper, loliserver, mohist а так же spigot
Версии всех компонентов данного продукта соответствуют

**Comment by gravit0** [comment]
Так и должно быть - вход на сервер работает с тем типом authId, с которым вы вошли на сервер ServerWrapper'ом. В 5.1.12 по другому никак нельзя

**Comment by microwin7** [comment]
Вход может быть осуществлён, только при использовании одинаковых данных БД, к примеру если serverID и accessToken будут настроены в разных авторизациях и смотреть на одни и те же данные, так же ник и uuid должен совпадать. Любой другой вариант будет принимать только вход с аналогичной подключённой authID

**Comment by dimadencep** [comment]
> Так и должно быть - вход на сервер работает с тем типом authId, с которым вы вошли на сервер ServerWrapper'ом. В 5.1.12 по другому никак нельзя

А зачем тогда вообще нужно несколько методов авторизации?
