### ISSUE TITLE
[Ошибка] Оффлайн лаунчер

### ISSUE THREAD

**Issue by danpaf** [GravitLauncher/Launcher#573]
Лаунчер стоит на хостинге
1. Метод авторизации стоит bcrypt
2. Модуль установлен
3. Все билдиться, лог чистый
4. При заходе в лаунчер - пишет что оффлайн.

mysql

**Comment by Enchald** [comment]
Проверь, может быть запущено 2 LS

**Comment by gravit0** [comment]
Это не ошибка лаунчера. Проверьте порты и ваш firewall
