### ISSUE TITLE
При установке / первом запуске launcherserver

### ISSUE THREAD

**Issue by 1YablochnIK1** [GravitLauncher/Launcher#580]
Пишет следующию ошибку: (Установка производилась на винду для тестов на локалке)

https://pastebin.com/L68gLg8J

**Comment by Frysuni** [comment]
Рядом с LaunchServer.jar должна быть папка libraries.
Ее взять ты можешь из артефактов с гита, либо при самостоятельном билде она тоже создается.
С такими проблемами обращайся в саппорт в дискорде гравитлаунчера, тикет закрой.
