### ISSUE TITLE
Возможность авторизации по Email

### ISSUE THREAD

**Issue by bigenergy** [GravitLauncher/Launcher#59]
Как насчет возможности авторизации по мылу игрока, вместо его ника? 
Можно реализовать через authHandler, допустим если у игрока в бд стоит настройка isMailLogin, то будет пропускать авторизацию только по его мылу, это повысит безопасность аккаунтов, так как Email знает только игрок.

**Comment by gravit0** [comment]
В чем проблема изменить SQL запрос или настройки CMS? Issue невалиден

**Comment by bigenergy** [comment]
> В чем проблема изменить SQL запрос или настройки CMS? Issue невалиден

Проблема в том, если сделать авторизацию лишь по мылу, то лаунчер авторизирует игрока по мылу, а ника в игре не будет, разве не так?

**Comment by gravit0** [comment]
Не так. Внимательнее изучайте схему авторизации

**Comment by bigenergy** [comment]
Получается, при authProvider: "request", строка response: "OK:(?<username>.+)"; задает никнейм?
Т.е. если на веб стороне я сделаю все что нужно для этого, я могу просто отдавать лаунчеру "ОК:никнейм"?

**Comment by gravit0** [comment]
Именно так
