### ISSUE TITLE
Ошибка при обновлении лаунчера

### ISSUE THREAD

**Issue by serega404** [GravitLauncher/Launcher#593]
При попытке авто-обновления лаунчер показывает ошибку, которая говорит что сервер ответил кодом 400 на запрос обновленного бинарника.

Проблема заключается в том что с новой версии символы в названии лаунчера при скачивании не экранируются.
Баг исполняется если в названии бинарника лаунчера есть пробел.
```
"GET /updates/Moy Launcher.exe HTTP/1.1" 400 150 "-" "-" # Запрос лаунчера
"GET /updates/Moy%20Launcher.exe HTTP/1.1" 200 8442714 "-" "Wget/1.21"
```
Удачный вариант:
```
"GET /updates/MoyLauncher.exe HTTP/1.1" 400 150 "-" "-"
```

**Comment by Frysuni** [comment]
Добавьте %20 в конфигурацию Netty и закройте тикет, Вам ответили в дискорде.
