### ISSUE TITLE
Ошибка при запуске лаунчера после перезагрузки LaunchServer

### ISSUE THREAD

**Issue by jeka13201** [GravitLauncher/Launcher#595]
java.io.IOException: Invalid update (launcher needs update, but link has old launcher), check LaunchServer config...
лаунчер нужно обновлять после каждого перезапуска LaunchServer что-ли?

**Comment by microwin7** [comment]
Не запускайте несколько экземпляров лаунчсервера
ps ax | grep java
И убейте
