### ISSUE TITLE
Возможность указать через конфиг запуск launch4j от имени администратора

### ISSUE THREAD

**Issue by realkarmakun** [GravitLauncher/Launcher#604]
Альтернативно дать возможность в конфиге указывать манифест файл для самостоятельного включения запуска от имени админа (https://stackoverflow.com/questions/19037339/run-java-file-as-administrator-with-full-privileges)

**Comment by gravit0** [comment]
Лаунчер не должен требовать привилегий администратора

**Comment by realkarmakun** [comment]
Ладно справедливо на самом деле. Я самостоятельно подкрутил загрузку манифеста, так что если кому то понадобиться, они смогут это сделать самостоятельно. Закрываю это
