### ISSUE TITLE
Exception class java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by Stepawkas** [GravitLauncher/Launcher#606]
Here is such an error when starting the game
Exception class java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: pro.gravit.launcher.client.ClientLauncherProcess.<init>(Ljava/nio/file/Path;Ljava/nio/file/Path;Ljava/nio/file/Path;Ljava/nio/file/Path;Lpro/gravit/launcher/profiles/ClientProfile;Lpro/gravit/launcher/profiles/PlayerProfile;Lpro/gravit/launcher/profiles/optional/OptionalView;Ljava/lang/String;Lpro/gravit/launcher/hasher/HashedDir;Lpro/gravit/launcher/hasher/HashedDir;Lpro/gravit/launcher/hasher/HashedDir;)V

**Comment by gravit0** [comment]
Please use compatible runtime and launchserver
Runtime for 5.3.0 is not compatible with runtime 5.2.13 and vice versa
