### ISSUE TITLE
Certificate Pinning Bug

### ISSUE THREAD

**Issue by Clercq** [GravitLauncher/Launcher#608]
![image](https://user-images.githubusercontent.com/50501391/187054050-d569659e-8415-43c2-b5f8-c8a03d6b3001.png)
У вас в новом LauncherUpdated.class нет поддержки Certificate Pinning

Приложу скриншот как загружается все остальное:
![image](https://user-images.githubusercontent.com/50501391/187054061-aab407d2-0294-4606-8ebd-6d35fc44ee47.png)

Это приводит к ошибкам на старых жабах, да и фичу делает бесполезной. 

Кроме того, в мастере тоже самое.

**Comment by Clercq** [comment]
![image](https://user-images.githubusercontent.com/50501391/187054088-6ca8ed1b-9692-4bab-a1ab-c4c60597786b.png)
Скриншот с мастера

**Comment by gravit0** [comment]
Исправила
