### ISSUE TITLE
Authlib 1.12.2

### ISSUE THREAD

**Issue by leadertv** [GravitLauncher/Launcher#628]
Два дня ломаю голову. Через офлайн режим пускает на сервер, а оффлайн не пускает.
1) Какой Authlib нужно использовать для сервера CatServer 1.12.2? В зеркале непонятно с какой ветке надо скачать нужный.
2) Из содержимого со скачанного LauncherAuthlib нужно патчить в AuthlibXXX? 

В зеркале нет патченного CatServer 1.12.2 увы.

**Comment by microwin7** [comment]
Читайте на вики патч клиента, там всё расписано https://launcher.gravit.pro

**Comment by leadertv** [comment]
> Читайте на вики патч клиента, там всё расписано https://launcher.gravit.pro

В том то и дело, что понятно и одновременно не понятно.
Перепробовал разные варианты. Оффлайн - пускает на сервер, а при онлайн - нет.
[User Authenticator #1/ERROR]: Couldn't verify username because servers are unavailable
Ядро CatServer1.12.2

**Comment by viblyadok** [comment]
Попробуй скачать фикс LauncherWrapper и кинуть его по пути server\libraries\net\minecraft\launchwrapper\1.12 с переименованием на исходный враппер.

**Comment by microwin7** [comment]
@leadertv
```
-Dcatserver.skipCheckLibraries=true
```
 [./libraries/launchwrapper-1.12.jar](https://mirror.gravitlauncher.com/5.2.x/compat/launchwrapper-1.12-5.0.x-fixed.jar)

**Comment by leadertv** [comment]
Благодарю, можно закрыть вопрос, сделал всё более внимательно ещё в декабре, и всё заработало.
