### ISSUE TITLE
Не компилируется лаунчер в exe файл

### ISSUE THREAD

**Issue by AltronMaxX** [GravitLauncher/Launcher#644]
Сделал всё как по инструкции, создаётся и обновляется только jar файл. При добавлении пустого exe файла сервер просто удаляет его.

**Comment by Lertey** [comment]
Включи laun4g: true

**Comment by AltronMaxX** [comment]
Но где это включить?

**Comment by egorsgn** [comment]
В пизде

чт, 9 мар. 2023 г., 22:34 Max ***@***.***>:
