### ISSUE TITLE
Добавить базовый HWID HANDLER

### ISSUE THREAD

**Issue by NITDroid1995** [GravitLauncher/Launcher#67]
#HWID handler
hwidHandler: "mysql";
hwidHandlerConfig: {
    fetchAll: false; 
    address: "localhost"; 
    port: 3306; 
    username: "launcher"; 
    password: "launcher";
    database: "Mine1?serverTimezone=UTC"; 
    query: "SELECT banned,name FROM dle_users WHERE ( hwid_hdd=? AND hwid_cpu=? AND hwid_bios=? ) OR ( name=? AND banned=1)";
    queryParams: [ "%hwid_hdd%", "%hwid_cpu%", "%hwid_bios%" ,"%login%"];
    queryUpd: "UPDATE dle_users SET hwid_hdd = ?, hwid_cpu = ?, hwid_bios = ? WHERE name=?";
    queryParamsUpd: [ "%hwid_hdd%", "%hwid_cpu%", "%hwid_bios%", "%login%" ];
    queryBan: "UPDATE dle_users SET banned = ? WHERE hwid_hdd = ? AND hwid_cpu = ? AND hwid_bios = ?";
    queryParamsBan: [ "%isBanned%", "%hwid_hdd%", "%hwid_cpu%", "%hwid_bios%" ];
    querySelect: "SELECT hwid_hdd,hwid_cpu,hwid_bios FROM dle_users WHERE name=?";
    queryParamsSelect: [ "%login%" ];
    isBannedName: "banned";
    loginName: "name";
    hddName: "hwid_hdd";
    cpuName: "hwid_cpu";
    biosName: "hwid_bios";
    banMessage: "Ваш аккаунт заблокирован!";
};

Данный конфиг работает на DLE. Но если у Вас голова есть, то поменяв пару строк, можно сделать абсолютно под любую другую CMS (Бог маркетинга)

**Comment by TheXaver** [comment]
также прошу добавить hwid handler с request запросом

**Comment by gravit0** [comment]
Не понимаю сути вашего issue

**Comment by NITDroid1995** [comment]
Ну вот. СТали инвалидами 🗡

**Comment by gravit0** [comment]
Проблема касалась Wiki
Проблема решена
На RequestHWIDHandler нужно создать отдельный issue
