### ISSUE TITLE
Не работает верификация пользователей через PostgreSQL

### ISSUE THREAD

**Issue by Jlucu4ka228** [GravitLauncher/Launcher#676]
У меня настроен гравит сервер v5.4.3-1. В нём полностью настроено подключение PostgreSQL, при попытке авторизации в лаунчере всё работает корректно: существуюих пользователей при правильном пароле авторизует, несуществующих - нет. Но при попытке войти на привязанный к лаунчеру сервер, соединение прерывается по причине Failed to verify username, хотя гравит сервер выдаёт строчку `[DEBUG] joinServer: USERNAME accessToken: TOKEN serverID: ID`. 
Протестированы сервера: fabric 1.19.2, paper 1.19.2, paper 1.16.5. В первых двух опция `enforce-secure-profile` отключена.

Иными словами, соединение где оно нужно присутствует (игровой сервер подключается к гравит серверу, при выключении последнего игровой сервер говорит об отключении от вебсокета), но проверить имя пользователя, судя по ошибке, сервер не в состоянии.

Все колонки в конфигурации подключения БД введены верно, ошибок SQL нет.

**Comment by microwin7** [comment]
Должен быть checkServer и JoinServer, если checkServer нет, значит проблема в привязанном сервере, проверь что сделал всё верно. А именно заменил fabric-loader если это фабрик сервер, либо же токен сервера мог быть от старого лаунчсервера

**Comment by microwin7** [comment]
Вижу что paper, значит вероятнее всего ключ или привязка неверная, убедись что LaunchAuthlib был именно 1.19.1

**Comment by Jlucu4ka228** [comment]
Проблема решена, я смотрел на старое вики https://gravit-launcher.ru, в котором не говорится о LaunchAuthlib. Спасибо, впредь буду смотреть на новую вики!

**Comment by microwin7** [comment]
> Проблема решена, я смотрел на старое вики https://gravit-launcher.ru, в котором не говорится о LaunchAuthlib. Спасибо, впредь буду смотреть на новую вики!

Это вообще не наше вики

**Comment by microwin7** [comment]
Наше оффициальное вики: https://gravitlauncher.com/
Резервное от саппорта: https://gravit-support.ru/
