### ISSUE TITLE
Не отображаются скины.

### ISSUE THREAD

**Issue by Sarto4ek** [GravitLauncher/Launcher#682]
Поставил сервер на 1.12.2 forge добавил к нему authlib + serverwrapper 
online-mod стоит на true
В LauncheServer.json скин провайдер настроен 
`      },
      "textureProvider": {
        "skinURL": "https://адрес.ru/skins/%username%.png",
        "cloakURL": "https://адрес.ru/cloaks/%username%.png",
        "type": "request"
      },`
В лаунчере скин отображается (аватарка головы)
а на сервере нет

**Comment by Sarto4ek** [comment]
![Screenshot_2](https://github.com/GravitLauncher/Launcher/assets/135160245/b10353f5-a003-4ea9-a759-152dc8214b39)
пример на версии 1.16.5

**Comment by pron1mo** [comment]
В server.properties стоит `online-mode: true`?

**Comment by Sarto4ek** [comment]
Стоит `online-mode=true`

**Comment by gru2007** [comment]
Ну у меня все нормально работало, так что тут ты что-то неправильно настроил, а не в лаунчере проблема

**Comment by microwin7** [comment]
Для тех кто может наткнуться на этот Issue позже. Обычно причина в CloudFlare, он блокирует User-Agent джавы.
это можно проверить с помощью команды:
```
curl -I "Java/1." "ссылка на png"
```
Если код ответа 1010, то это как раз CloudFlare
Для решения необходимо настроить исключения в WAF и/или PageRules, в зависимости от режима защиты от DDos
