### ISSUE TITLE
Mariadb. Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by Pavel7811** [GravitLauncher/Launcher#690]
Добрый день! Использую сервер с Opensuse Tumbleweed. В качестве БД использую 11.0.2-MariaDB, client 15.2 for Linux (x86_64). 

При авторизации возникает следующая ошибка:

22:51:18.253 [ERROR] SQL error
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'transaction_isolation'
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[HikariCP-5.0.1.jar:?]

Полный текст ошибки разместил здесь:
https://pastebin.com/DyXZjjXn

**Comment by microwin7** [comment]
> Добрый день! Использую сервер с Opensuse Tumbleweed. В качестве БД использую 11.0.2-MariaDB, client 15.2 for Linux (x86_64).
> 
> При авторизации возникает следующая ошибка:
> 
> 22:51:18.253 [ERROR] SQL error com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'transaction_isolation' at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[HikariCP-5.0.1.jar:?]
> 
> Полный текст ошибки разместил здесь: https://pastebin.com/DyXZjjXn

Не так давно проверял на более новых версиях, этот параметр вернули, в какой точно 11.x версии только не помню. На ПК стоит 11.2.2 и работает
