### ISSUE TITLE
Добавить кнопку отправить характеристики ПК

### ISSUE THREAD

**Issue by wolfys** [GravitLauncher/Launcher#70]
Пришла интересная идея по отправке характеристик компьютера на сервер где находится лаунчер или сайт, к примеру можно генерировать стандартный файл от dxdiag и отправлять его или выдирать их каким-то другим способом.
Зачем? У меня крайне не стандартные тяжелые сборки и игроки часто жалуются что у них всё глючит и прочие вещи происходит, увы определить виновато железо или что-то у меня я не могу, по этому пришлось написать мини прогу которая формирует файл от dxdiag и его грузит игрок на форум, но это СЛОЖНО для них. 
Отправлять или файлом или просто характеристики писать в базу с указанием ника игрока естественно. 
Сорян за русский у меня с ним беда :))

**Comment by wolfys** [comment]
Еще раз распишу зачем характеристики отдельно от краша, суть в следующем игрок запускает на компе типа (p4 1.8 gz, 1 gb озу, 256 видео) сборку из лаунчера типа FTB Infinty Evolved логично что она падает, не обязательно с крашем видел такое  и у игрока куча вопросов, а у меня не запускает игра что делать помогите!!! - Нужно получить харки его пк, метод такой писать инструкцию как их посмотреть и отправить что нужно или автоматизировать их отправку на сервер или чтобы пользователь цеплял какой-то txt файл или не txt без разницы к теме на форуме, на сайте - логично кнопкой проще было бы

**Comment by gravit0** [comment]
Из Java кода без Native API можно вытянуть только максималное колличество ОЗУ, и то не совсем документированным образом.
До CPU или его частоты без натив библиотек не добраться

**Comment by gravit0** [comment]
Вы можете использовать HWID_CPU что бы вытянуть информацию о CPU
