### ISSUE TITLE
Клиент 1.12.2 закрывается с ошибкой лаунчера. Крашлога нет.

### ISSUE THREAD

**Issue by Mr-Krab** [GravitLauncher/Launcher#78]
Протестировано на Win 7, 8.1
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Версия лаунчера 4.0.7
Версия Minecraft 1.12.2
Версия Forge 14.23.5.2770

При наличии на клиенте мода Mekanism клиент выбивает даже при входе в одиночку. Подозреваю, что есть несостыковки в работе лаунчера со звуковым сервером этого мода, но это не точно. При входе на сервер(конечно же с этим модом) происходит то же самое. Сервер при этом впорядке, но я коннект через WaterFall провожу, так что не могу сказать как повел бы себя сервер в связке с лаунчером.

У одного из игроков стало выбивать приблизительно через 10 минут игры с подобной ошибкой, мода Mekanism, при этом не было уже.

Вот логи:
[Краш клиента с модом Mecanism.zip](https://github.com/GravitLauncher/Launcher/files/2604760/Mecanism.zip)
[лог игрока с непонятным  крашем клиента.log](https://github.com/GravitLauncher/Launcher/files/2604761/default.log)
В самом конце красуется вот такое
[STDERR]: [ru.gravit.launcher.Qs606nNpcDgUfhUCSOMtTWIo:fh2JGScJzdc4Ci28lt15v9Cx:70]: Threat UNKNOWN_APC_DESTINATION

**Comment by Mr-Krab** [comment]
Потенциально не актуально, протестирую еще несколько раз, если проблема будет повторяться, то открою снова.

**Comment by roma8888madambovari-dev** [comment]
/[](url)

![Image](https://github.com/user-attachments/assets/3cd0fd33-38be-473c-87d0-a660e8fe754b)

**Comment by roma8888madambovari-dev** [comment]
[ ] анна ****
