### ISSUE TITLE
Тригер для бана на сайте, при бане из лаунчера (ADD TO WIKI)

### ISSUE THREAD

**Issue by NITDroid1995** [GravitLauncher/Launcher#79]
Данный тригер работает на DLE но если вы шарите, то в полне сможете переписать его на другие CMS.
Начнем.
Для начала необходимо в таблице dle_users создать новую колонку с названием banLauncher для взаимодействия. Ибо ДЛЕ использует yes-no , а лаунчер 1-0.
Значение по умолчанию 0.
Вот запрос:
```sql
ALTER TABLE `dle_users`
	ADD COLUMN `banLauncher` INT NULL DEFAULT '0' AFTER `banned`;
```
Теперь открываем LaunchServer.cfg
В разделе #HWID handler
заменяем все `banned `на `banLauncher`
![image](https://user-images.githubusercontent.com/23436336/48854910-795c3f00-edcc-11e8-8181-b3e848d34dad.png)

Теперь создаем тригер с параметрами : `BEFORE UPDATE` на таблицу `dle_users`
![image](https://user-images.githubusercontent.com/23436336/48854654-d86d8400-edcb-11e8-8785-ce8074799a19.png)

В содержимое тригера добавляем:
```sql
BEGIN
IF NEW.banLauncher = 1 THEN
SET NEW.banned = 'yes';
set @id=(SELECT user_id FROM dle_users WHERE name = NEW.name);
    set @days=0;
    set @date=0;
INSERT INTO dle_banned (users_id, days, date, ip, descr) VALUES (@id, @days, @date, '','Ваш аккаунт заблокирован по множественным жалобам пользователей. Дальнейшее создание аккаунтов- приведет к повторной блокировке. Ваш IP занесен в черный список');
END IF;
IF NEW.banLauncher = 0 THEN
SET NEW.banned = '';
set @id=(SELECT user_id FROM dle_users WHERE name = NEW.name);
DELETE FROM dle_banned WHERE users_id = @id LIMIT 5;
END IF;
END
```
Теперь если в сокете прописать команду `ban test` 
![image](https://user-images.githubusercontent.com/23436336/48854767-21253d00-edcc-11e8-8450-15dfee66331b.png)
![image](https://user-images.githubusercontent.com/23436336/48854793-31d5b300-edcc-11e8-8eed-90674bb8cceb.png)

То он будет забанен на сайте и в лаунчере, бан соответсвенно по железу.
команда `unban test` соответсвенно разбанит этого пользователя
![image](https://user-images.githubusercontent.com/23436336/48854818-3f8b3880-edcc-11e8-9d82-83e6705c67fe.png)
![image](https://user-images.githubusercontent.com/23436336/48854824-46b24680-edcc-11e8-8651-89b3183680e7.png)

**Comment by gravit0** [comment]
Не актуально в 4.1
