### ISSUE TITLE
Разделение Launcher

### ISSUE THREAD

**Issue by Zaxar163** [GravitLauncher/Launcher#8]
Изменить Gradle скрипты сборки в соответствии с таким разделением:

LauncherModule - запуск клиента/gui
ClientModule - authlib, avanguard
ServerModule - ServerWrapper/authlib
Log4j включать только в LauncherModule

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/Launcher/commit/f83afcd8e106a665c9254b6501757b077ec2f027
https://github.com/GravitLauncher/Launcher/commit/b71df6ca01290e6c3e7463340d484992f4ef7804
https://github.com/GravitLauncher/Launcher/commit/e44264d554f5cc989a9072db20ff3fa19e041259
